***************A05.目前作業記錄管理
CLOSE ALL
CLEAR 
FLG='0'
FCH=''
AREA1='A04_1'
AREA2='A04'
CHK=''
IF !USED('A01')
   SELE 0
   USE A01 INDE A01
ELSE 
   SELE A01
ENDIF
SET ORDER TO A01   
IF !USED('A02')
   SELE 0
   USE A02 INDE A02
ELSE 
   SELE A02
ENDIF
SET ORDER TO A021
SEEK sys_oper+'A05'         
IF !USED('A04')
   SELE 0
   USE A04 INDE A04
ELSE 
   SELE A04
ENDIF
SET ORDER TO 1      
SELECT A04.F01,A01.F03 FROM A01,A04 WHERE A04.F01 = A01.F01 AND A04.F01 <> 'zzzzz'  GROUP BY A04.F01 ORDER BY A04.F01 INTO CURSOR A04_1 READWRITE 
SELECT A04_1
INDE ON F01 TAG A04_11
GO TOP
***
A05FORM=CREATEOBJECT("TKA05")
A05FORM.SHOW  
DEFINE CLASS TKA05 AS FORM
  CAPTION='A05.目前作業紀錄'
*!*	  AUTOCENTER=.T.
  CONTROLBOX=.F.
  BORDERSTYLE=1  
  MAXBUTTON=.F.
  MINBUTTON=.F.
  MOVABLE=.F.
  CLOSABLE=.F.
  CONTROLCOUNT=57
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*550
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WIDTH=INT_015*789
  WINDOWTYPE=1
  NAME='TKA05'
  ADD OBJECT SHAPE1 AS SHAPE1 WITH;
      AUTOCENTER=.T.
  ADD OBJECT SHAPE2 AS SHAPE2 WITH;
      AUTOCENTER=.T.
  ADD OBJECT SHAPE3 AS SHAPE3 WITH;
      AUTOCENTER=.T.
  ADD OBJECT LBL_REC AS LBL_REC WITH;
      AUTOCENTER =.T.,;
      CAPTION='可使用人數'
  ADD OBJECT REC_COUNT AS REC_COUNT  WITH;
      CAPTION=STR(RECCOUNT())      
  ADD OBJECT LBLF01 AS LABEL WITH;
      LEFT=INT_015*244,;
      TOP=INT_015*27,;
      WIDTH=INT_015*50,;
      CAPTION='人員編號'
  ADD OBJECT LBLF031 AS LABEL WITH;      
      LEFT=INT_015*244,;
      TOP=INT_015*52,;
      WIDTH=INT_015*50,;
      CAPTION='人員姓名'   
  ADD OBJECT LBLF02 AS LABEL WITH;
      LEFT=INT_015*244,;
      TOP=INT_015*77,;
      WIDTH=INT_015*50,;
      CAPTION='程式編號'
  ADD OBJECT LBLF03 AS LABEL WITH;
      LEFT=INT_015*244,;
      TOP=INT_015*102,;
      WIDTH=INT_015*50,; 
      CAPTION='程式說明'   
  ADD OBJECT LBLF04 AS LABEL WITH;
      LEFT=INT_015*244,;
      TOP=INT_015*127,;
      WIDTH=INT_015*50,;
      CAPTION='進入時間'
  ADD OBJECT TXTF01 AS TEXTBOX WITH;      
      LEFT=INT_015*295,;
      TOP=INT_015*23,;
      WIDTH=INT_015*49,;
      MAXLENGTH=5,;
      NAME='TXTF01'  
  ADD OBJECT TXTF031 AS TEXTBOX WITH;
      AUTOSIZE=.T.,;
      LEFT=INT_015*295,;
      TOP=INT_015*48,;
      WIDTH=INT_015*68,;
      MAXLENGTH=8,;
      NAME='TXTF031'                 
  ADD OBJECT TXTF02 AS TEXTBOX WITH;
      LEFT=INT_015*295,;
      TOP=INT_015*73,;
      WIDTH=INT_015*49
      MAXLENGTH=3
  ADD OBJECT TXTF03 AS TEXTBOX WITH;
      LEFT=INT_015*295,;
      TOP=INT_015*98,;
      WIDTH=INT_015*177,;            
      NAME='TXTF03'                      
  ADD OBJECT TXTF04 AS TEXTBOX WITH;
      LEFT=INT_015*295,;
      TOP=INT_015*123,;
      WIDTH=INT_015*177,;            
      MAXLENGTH=24,;
      NAME='TXTF04'                 
  ADD OBJECT KEY_LIST AS KEY_LIST WITH;
      AUTOCENTER=.T.
  ADD OBJECT GRID1 AS GRID1 WITH;
      COLUMNCOUNT=2,;            
      RECORDSOURCE='A04_1',;      
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2'
  ADD OBJECT GRID2 AS GRID2 WITH;
      COLUMNCOUNT=3,;            
      RECORDSOURCE='A04',; 
      LINKMASTER='A04_1',;
      RELATIONALEXPR='F01',;
      CHILDORDER='A041',;  
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2',;
      COLUMN3.NAME='COLUMN3'    
  ADD OBJECT CMDGROUP AS CMDGROUP WITH;
      AUTOSIZE=.T.              
  ADD OBJECT ORPGROUP AS ORPGROUP WITH;    
      AUTOSIZE=.T.
  PROC INIT
       THISFORM.ORPGROUP.NEW_BOTT.ENABLED=.F.   
       THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
       THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)   &&判斷有無刪除的權限
       THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
       THISFORM.SETALL('HEIGHT',INT_015*25,'TEXTBOX')
       THISFORM.SETALL('HEIGHT',INT_015*17,'LABEL')
       THISFORM.SETALL('FONTSIZE',INT_015*9,'TEXTBOX')
       THISFORM.SETALL('FONTSIZE',INT_015*9,'LABEL')       
       THISFORM.SETALL('READONLY',.T.,'TEXTBOX')
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'COLUMN')  
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'HEADER')  
       THISFORM.GRID2.SETALL('FONTSIZE',INT_015*9,'COLUMN')  
       THISFORM.GRID2.SETALL('FONTSIZE',INT_015*9,'HEADER')         
       THISFORM.GRID1.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)
       THISFORM.GRID2.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)
       THISFORM.GRID1.COLUMN1.WIDTH=INT_015*50
       THISFORM.GRID1.COLUMN2.WIDTH=INT_015*70
       THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='人員編號'
       THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='人員姓名'
       THISFORM.GRID1.COLUMN1.CONTROLSOURCE='A04_1.F01'
       THISFORM.GRID1.COLUMN2.CONTROLSOURCE='A04_1.F03'
       THISFORM.GRID2.COLUMN1.WIDTH=INT_015*50
       THISFORM.GRID2.COLUMN2.WIDTH=INT_015*100
       THISFORM.GRID2.COLUMN3.WIDTH=INT_015*120
       THISFORM.GRID2.COLUMN1.HEADER1.CAPTION='作業編號'
       THISFORM.GRID2.COLUMN2.HEADER1.CAPTION='作業說明'
       THISFORM.GRID2.COLUMN3.HEADER1.CAPTION='進入時間'
       THISFORM.GRID2.COLUMN1.CONTROLSOURCE='A04.F02'
       THISFORM.GRID2.COLUMN2.CONTROLSOURCE='A04.F03'      
       THISFORM.GRID2.COLUMN3.CONTROLSOURCE='A04.F04'  
       THISFORM.GRID1.READONLY=.T.       
       THISFORM.GRID1.SETFOCUS
       IF THISFORM.GRID1.ACTIVEROW=0
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
       ELSE
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.      
       ENDIF              
       JK='人員編號'
  ENDPROC     
  PROC KEY_LIST.INIT 
       WITH THIS 
           .ADDITEM('依人員編號排列')
       ENDWITH      
  ENDPROC 
  PROC GRID1.AFTERROWCOLCHANGE
       LPARAMETERS nColIndex
       THISFORM.TXTF01.VALUE=A04_1.F01
       THISFORM.TXTF031.VALUE=A04_1.F03
       THISFORM.TXTF02.VALUE=A04.F02
       THISFORM.TXTF03.VALUE=A04.F03
       THISFORM.TXTF04.VALUE=A04.F04
       IF THISFORM.GRID1.ACTIVEROW=0
           THISFORM.CMDGROUP.ENABLED=.F.
           THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
           THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
           THISFORM.SETALL('VALUE','','TEXTBOX')
       ELSE
           THISFORM.CMDGROUP.ENABLED=.T.
           THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
           THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.T.    
       ENDIF          
       THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
       FCH=THISFORM.ACTIVECONTROL.NAME
       JK=THIS.COLUMN1.HEADER1.CAPTION
        CHK=THISFORM.TXTF01.VALUE
       THISFORM.REFRESH
  ENDPROC 
  PROC GRID2.AFTERROWCOLCHANGE
       LPARAMETERS nColIndex
       SELECT A04
       THISFORM.TXTF02.VALUE=A04.F02
       THISFORM.TXTF03.VALUE=A04.F03
       THISFORM.TXTF04.VALUE=A04.F04
       THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
       FCH=THISFORM.ACTIVECONTROL.NAME
       CHK=''
*!*	       THISFORM.REFRESH
  ENDPROC   
  PROC ORPGROUP.DEL_BOTT.CLICK
      IF ALLTRIM(FCH) = 'GRID1'
          IF MESSAGEBOX('是否確定要刪除此人員所有登入系統資料',4+32+256,'請確認')=6
               DELETE FROM A04 WHERE A04_1.F01 = A04.F01 
               SELECT A04
               APPEND BLANK 
               LOCK()
               IF RLOCK()        
                   REPLACE  F01 WITH 'zzzzz'
                   REPLACE  F02 WITH ''
                   REPLACE  F03 WITH ''
                   REPLACE  F04 WITH ''
               ELSE
                   DO file_impact      
               ENDIF    
               UNLOCK      
               SELECT A04_1
               DELETE      
               THISFORM.GRID1.SETFOCUS
               IF THISFORM.GRID1.ACTIVEROW=0
                    THISFORM.CMDGROUP.ENABLED=.F.
                    THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
                    THISFORM.SETALL('VALUE','','TEXTBOX')
                ELSE
                    THISFORM.CMDGROUP.ENABLED=.T.
                    THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.T.    
                ENDIF    
          ENDIF     
     ELSE
          IF MESSAGEBOX('是否確定要刪除此筆資料',4+32+256,'請確認')=6
               SELECT A04
               DELETE      
               THISFORM.GRID2.SETFOCUS
               IF THISFORM.GRID2.ACTIVEROW=0
                    SELECT A04_1
                    DELETE 
                    THISFORM.CMDGROUP.ENABLED=.F.
                    THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
                     THISFORM.GRID1.SETFOCUS
                ELSE
                    THISFORM.CMDGROUP.ENABLED=.T.
                    THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.T.    
                ENDIF    
          ENDIF  
     ENDIF  
  ENDPROC
ENDDEFINE        

**************************************************刪除資料前檢查是否仍有關聯資料在其他資料表格中
PROCEDURE DELE_SHURE 
     SELE A04
     R=RECNO()
     LOCK()
     IF RLOCK()        
        REPL F01 WITH 'zzzzz'
        REPL F02 WITH ''
        REPL F03 WITH ''
        REPL F04 WITH ''
        UNLOCK
  
     ELSE
       DO FILE_IMPACT    
     ENDIF      
ENDPROC     
************************************************
