***程式名稱:C08.客戶訂單取消作業
CLOSE ALL
CLEAR 
FLG='0'
FCH=''
CHK=''
CHK_STR=''
R=0
QTY=0
TQTY=0
FTTL=0
TPQTY=0
AREA1='C08_1'
AREA2='C08'
IF !USED('A09')
   SELE 0
   USE A09
ELSE
   SELE A09
ENDIF
SET ORDER TO 1
IF !USED('A23')
    SELE 0
    USE A23
ELSE 
   SELE A23
ENDIF
SET ORDER TO 1         
A24='A24'+LEFT(DTOS(DATE()),6)     &&單號暫存檔
IF !USED('&A24')
   SELE 0
   USE (A24) ALIA A24
ELSE
   SELE A24
ENDIF
SET ORDER TO 1      
IF !USED('C09')                  &&取消紀錄檔   
   SELE 0
   USE C09
ELSE
   SELE C09
ENDIF
SET ORDER TO 1      

****         
SELE A23
SET ORDER TO 1
SEEK LEFT(DTOS(DATE()),6)+'01'


****              
IF !USED('C00')                  &&幣別檔
   SELE 0
   USE C00
ELSE
   SELE C00
ENDIF
SET ORDER TO 1
      
IF ! USED('A01')
   SELE 0
   USE A01 INDE A01
ELSE
   SELE A01
ENDIF      
SET ORDER TO A01
IF !USED('A02')
   SELE 0
   USE A02 INDE A02
ELSE
   SELE A02
ENDIF
SET ORDER TO A021      
SEEK SYS_OPER+'C08'
IF !USED('A14')
   SELE 0
   USE A14
ELSE 
   SELE A14
ENDIF
SET FILTER TO F04='*'
SET ORDER TO 1     
IF !USED('B01')
   SELE 0
   USE B01 INDE B01
ELSE
   SELE B01
ENDIF
SET ORDER TO 1     
IF !USED('C01')
   SELE 0
   USE C01 INDE C01
ELSE
   SELE C01
ENDIF
SET ORDER TO C011
IF !USED('C05')
   SELE 0   
   USE C05
ELSE
   SELE C05
ENDIF
SET ORDER TO C054
IF !USED('C03')
   SELE 0
   USE C03 INDE C03
ELSE
   SELE C03
ENDIF
SET ORDER TO C031
IF !USED('C04')
   SELE 0
   USE C04 INDE C04
ELSE
   SELE C04
ENDIF
SET ORDER TO C041
C08='C08'+LEFT(DTOS(DATE()),6)
C081='C081'+LEFT(DTOS(DATE()),6)
IF !USED('&C08')
   SELE 0
   USE (C08) ALIA C08
ELSE
   SELE C08
ENDIF
SET ORDER TO 1      
SET RELA TO F03 INTO B01
CREATE CURSOR C08_1;
(F01 C(10),F02 C(2),F06 C(5),F09 C(5),F10 C(1),F11 C(17),F21 C(60),F90 C(17))
INDE ON F01 TAG C08_11
INDE ON F06+F01 TAG C08_12
SELE F01,F02,F06,F09,F10,F11,F21,F90 FROM C08 GROUP BY F01 ORDER BY F01 INTO CURSOR C08_2
SELE C08_2
GO TOP
DO WHILE !EOF()
   SELE C08_1
   APPEND BLANK
   REPL F01 WITH C08_2.F01
   REPL F02 WITH C08_2.F02
   REPL F06 WITH C08_2.F06
   REPL F09 WITH C08_2.F09
   REPL F10 WITH C08_2.F10
   REPL F11 WITH C08_2.F11
   REPL F21 WITH C08_2.F21
   REPL F90 WITH C08_2.F90
   SELE C08_2
   SKIP   
ENDDO
SELE C08_2
USE   
SELE C08_1
SET ORDER TO 1
SET RELA TO F06 INTO C01
C08FORM=CREATEOBJECT("TKC08")
C08FORM.SHOW  
DEFINE CLASS TKC08 AS FORM
  CAPTION='C08.客戶訂單取消申請單'
*!*	  AUTOCENTER=.T.
  CONTROLBOX=.F.
  BORDERSTYLE=1  
  MAXBUTTON=.F.
  MINBUTTON=.F.
  MOVABLE=.F.
  CLOSABLE=.F.
  CONTROLCOUNT=57
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*550
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WIDTH=INT_015*791
  WINDOWTYPE=1
  NAME='TKC08'
  ADD OBJECT SHAPE1 AS SHAPE1 WITH;
      AUTOCENTER=.T.
  ADD OBJECT LBL_REC AS LBL_REC WITH;
      AUTOCENTER =.T.
  ADD OBJECT REC_COUNT AS REC_COUNT  WITH;
      CAPTION=STR(RECCOUNT())        
  ADD OBJECT SHAPE2 AS SHAPE2 WITH;
      AUTOCENTER=.T.
  ADD OBJECT SHAPE3 AS SHAPE3 WITH;
      AUTOCENTER=.T.
  ADD OBJECT PAGEFRAME1 AS PAGEFRAME WITH;
      LEFT=INT_015*236,;
      WIDTH=INT_015*540,;
      HEIGHT=INT_015*200,;
      FONTSIZE=INT_015*9,;
      PAGECOUNT=2,;
      TABSTRETCH=1,;
      ACTIVEPAGE=1,;
      VISIBLE=.T.,;
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;   
      PAGE1.NAME='PAGE1',;
      PAGE1.VISIBLE=.T.,;
      PAGE1.CAPTION='表頭資料',;
      PAGE2.NAME='PAGE2',;
      PAGE2.VISIBLE=.T.,;
      PAGE2.CAPTION='表身詳細資料內容'   
  ADD OBJECT KEY_LIST AS KEY_LIST WITH;
      AUTOCENTER=.T.,;
      WIDTH=INT_015*130
  ADD OBJECT MTH_LIST AS MTH_LIST WITH;
      AUTOCENTER=.T.
  ADD OBJECT GRID1 AS GRID1 WITH;
      COLUMNCOUNT=3,;            
      RECORDSOURCE='C08_1',;      
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2',;      
      COLUMN3.NAME='COLUMN3'    
  ADD OBJECT GRID2 AS GRID2 WITH;
      COLUMNCOUNT=7,;            
      RECORDSOURCE='C08',; 
      LINKMASTER='C08_1',;
      RELATIONALEXPR='F01',;
      CHILDORDER=C081,;  
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2',;
      COLUMN3.NAME='COLUMN3',;
      COLUMN4.NAME='COLUMN4',;
      COLUMN5.NAME='COLUMN5',;
      COLUMN6.NAME='COLUMN6',;
      COLUMN7.NAME='COLUMN7'
  ADD OBJECT CMDGROUP AS CMDGROUP WITH;
      AUTOSIZE=.T.              
  ADD OBJECT ORPGROUP AS ORPGROUP WITH;    
      AUTOSIZE=.T.
  ADD OBJECT SHRGROUP AS SHRGROUP WITH;
      TOP=INT_015*165,;
      LEFT=INT_015*570          
  ADD OBJECT ANS_BOTT AS COMMANDBUTTON WITH;
      TOP=INT_015*490,;
      LEFT=INT_015*15,;
      HEIGHT=INT_015*25,;
      WIDTH=INT_015*40,;      
      FONTSIZE=INT_015*9,;
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;         
      TOOLTIPTEXT='確認取消訂單!快速鍵->ALT+A',;
      CAPTION='\<A.確認',;
      NAME='ANS_BOTT'                           
  PROCEDURE PAGEFRAME1.PAGE1.INIT     
     THIS.ADDOBJECT('LBLF01','LABEL')
     WITH THIS.LBLF01
          .VISIBLE=.T.
          .LEFT=INT_015*14
          .TOP=INT_015*13
          .WIDTH=INT_015*50
          .CAPTION='取消單號'          
     ENDWITH
     THIS.ADDOBJECT('LBLF06','LABEL')
     WITH THIS.LBLF06
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*38
         .WIDTH=INT_015*50
         .CAPTION='客戶編號'
     ENDWITH
     THIS.ADDOBJECT('LBLF061','LABEL')
     WITH THIS.LBLF061
         .VISIBLE=.T.
         .LEFT=INT_015*115
         .TOP=INT_015*38
         .AUTOSIZE=.T.
     ENDWITH     
     THIS.ADDOBJECT('LBLF09','LABEL')
     WITH THIS.LBLF09
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*63
         .WIDTH=INT_015*50
         .CAPTION='業務人員'
     ENDWITH    
     THIS.ADDOBJECT('LBLF091','LABEL')
     WITH THIS.LBLF091
         .VISIBLE=.T.
         .LEFT=INT_015*115
         .TOP=INT_015*63
         .AUTOSIZE=.T. 
     ENDWITH      
     THIS.ADDOBJECT('LBLF21','LABEL')
     WITH THIS.LBLF21
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*138
         .WIDTH=INT_015*50
         .CAPTION='備        註'
     ENDWITH    
     THIS.ADDOBJECT('LBLF02','LABEL')
     WITH THIS.LBLF02
         .VISIBLE=.T.
         .LEFT=INT_015*368
         .TOP=INT_015*13
         .WIDTH=INT_015*50
         .CAPTION='取消日期'
     ENDWITH    
     THIS.ADDOBJECT('LBLF10','LABEL')
     WITH THIS.LBLF10
         .VISIBLE=.T.
         .LEFT=INT_015*368
         .TOP=INT_015*38
         .WIDTH=INT_015*50
         .CAPTION='確  認  碼'
     ENDWITH    
     THIS.ADDOBJECT('PASS_CND','LABEL')
     WITH THIS.PASS_CND
         .VISIBLE=.T.
         .LEFT=INT_015*419
         .TOP=INT_015*38
         .AUTOSIZE=.T.
     ENDWITH         
     THIS.ADDOBJECT('LBLTTL1','LABEL')
     WITH THIS.LBLTTL1
         .VISIBLE=(A02.F10='*')
         .LEFT=INT_015*368
         .TOP=INT_015*63
         .WIDTH=INT_015*50
         .CAPTION='金額總計'
     ENDWITH              
     THIS.ADDOBJECT('LBLTTL11','LABEL')
     WITH THIS.LBLTTL11
         .VISIBLE=(A02.F10='*')
         .LEFT=INT_015*419
         .TOP=INT_015*63
         .AUTOSIZE=.T.
     ENDWITH                        
     THIS.ADDOBJECT('LBLF11','LABEL')
     WITH THIS.LBLF11
         .VISIBLE=.T.
         .LEFT=INT_015*368
         .TOP=INT_015*120
         .WIDTH=INT_015*50
         .CAPTION='安全資料'
     ENDWITH    
     THIS.ADDOBJECT('LBLF111','LABEL')
     WITH THIS.LBLF111
         .VISIBLE=.T.
         .LEFT=INT_015*419
         .TOP=INT_015*120
         .AUTOSIZE=.T.
     ENDWITH    
     THIS.ADDOBJECT('LBLF90','LABEL')
     WITH THIS.LBLF90
         .VISIBLE=.T.
         .LEFT=INT_015*368
         .TOP=INT_015*145
         .WIDTH=INT_015*50
         .CAPTION='確認人員'
     ENDWITH    
     THIS.ADDOBJECT('LBLF901','LABEL')
     WITH THIS.LBLF901
         .VISIBLE=.T.
         .LEFT=INT_015*419
         .TOP=INT_015*145
         .AUTOSIZE=.T.
     ENDWITH         
     THIS.ADDOBJECT('TXTF01','TEXTBOX')          
     WITH THIS.TXTF01
          .VISIBLE=.T.
          .LEFT=INT_015*64
          .TOP=INT_015*9
          .WIDTH=INT_015*81
          .HEIGHT=INT_015*25
          .MAXLENGTH=10
     ENDWITH        
     THIS.ADDOBJECT('TXTF06','TXTF06')          
     WITH THIS.TXTF06
          .VISIBLE=.T.
          .LEFT=INT_015*64
          .TOP=INT_015*34
          .WIDTH=INT_015*49
          .HEIGHT=INT_015*25        
          .MAXLENGTH=5
     ENDWITH             
     THIS.ADDOBJECT('TXTF09','TXTF09')          
     WITH THIS.TXTF09
          .VISIBLE=.T.
          .LEFT=INT_015*64
          .TOP=INT_015*59
          .WIDTH=INT_015*49
          .HEIGHT=INT_015*25        
          .MAXLENGTH=5
     ENDWITH     
     THIS.ADDOBJECT('TXTF21','TEXTBOX')     
     WITH THIS.TXTF21
          .VISIBLE=.T.
          .LEFT=INT_015*64
          .TOP=INT_015*134
          .WIDTH=INT_015*250
          .HEIGHT=INT_015*25
          .MAXLENGTH=60
     ENDWITH      
     THIS.ADDOBJECT('TXTF02','TEXTBOX')          
     WITH THIS.TXTF02
          .VISIBLE=.T.
          .LEFT=INT_015*418
          .TOP=INT_015*9
          .WIDTH=INT_015*40
          .HEIGHT=INT_015*25
          .MAXLENGTH=2
     ENDWITH        
  ENDPROC   
  PROCEDURE PAGEFRAME1.PAGE2.INIT
	THIS.ADDOBJECT('LBLF03','LABEL')
	WITH THIS.LBLF03  
	     .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*18
	     .WIDTH=INT_015*50
         .CAPTION='料品編號'
    ENDWITH  
    THIS.ADDOBJECT('LBLF031','LABEL')
    WITH THIS.LBLF031
         .VISIBLE=.T.
         .LEFT=INT_015*327
	     .TOP=INT_015*18
	     .AUTOSIZE=.T.
	ENDWITH     
    THIS.ADDOBJECT('LBLF07','LABEL')
    WITH THIS.LBLF07
         .VISIBLE=.T.
	     .LEFT=INT_015*14
	     .TOP=INT_015*43
	     .WIDTH=INT_015*50
	     .CAPTION='訂單編號'
	ENDWITH     
    THIS.ADDOBJECT('LBLF04','LABEL')
    WITH THIS.LBLF04
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*68
         .WIDTH=INT_015*50
         .CAPTION='計價數量'         
    ENDWITH     
    THIS.ADDOBJECT('LBLF13','LABEL')
    WITH THIS.LBLF13
         .VISIBLE=.T.    
         .LEFT=INT_015*14
         .TOP=INT_015*93
         .WIDTH=INT_015*50
         .CAPTION='無價數量'       
    ENDWITH    
    THIS.ADDOBJECT('LBLF12','LABEL')
    WITH THIS.LBLF12
         .VISIBLE=.T.           
         .LEFT=INT_015*14
         .TOP=INT_015*118
         .WIDTH=INT_015*50
         .CAPTION='備註資料'
    ENDWITH             
    THIS.ADDOBJECT('LBLF14','LABEL')    
    WITH THIS.LBLF14
         .VISIBLE=.F.           
         .LEFT=INT_015*328
         .TOP=INT_015*43
         .WIDTH=INT_015*50
         .CAPTION='幣        別'
    ENDWITH     
    THIS.ADDOBJECT('LBLF16','LABEL')    
    WITH THIS.LBLF16
         .VISIBLE=.F.           
         .LEFT=INT_015*328
         .TOP=INT_015*68
         .WIDTH=INT_015*50
         .CAPTION='匯        率'
    ENDWITH         
    THIS.ADDOBJECT('LBLF15','LABEL')      
    WITH THIS.LBLF15
         .VISIBLE=.F.       
         .LEFT=INT_015*328
         .TOP=INT_015*93
         .WIDTH=INT_015*50
         .CAPTION='單        價'
    ENDWITH     
    THIS.ADDOBJECT('LBLF17','LABEL')
    WITH THIS.LBLF17
         .VISIBLE=.F.           
         .LEFT=INT_015*328
         .TOP=INT_015*118
         .WIDTH=INT_015*50
         .CAPTION='金額小計'
    ENDWITH  
    THIS.ADDOBJECT('LBLF171','LABEL')    
    WITH THIS.LBLF171
         .VISIBLE=.F.           
         .LEFT=INT_015*379
         .TOP=INT_015*118
         .AUTOSIZE=.T.
    ENDWITH         
    THIS.ADDOBJECT('LBLF11','LABEL')
    WITH THIS.LBLF11
        .VISIBLE=.T.           
        .LEFT=INT_015*14
        .TOP=INT_015*148
        .WIDTH=INT_015*50
        .CAPTION='安全資料'         
    ENDWITH    
    THIS.ADDOBJECT('LBLF111','LABEL')
    WITH THIS.LBLF111
        .VISIBLE=.T.           
        .LEFT=INT_015*65
        .TOP=INT_015*148
        .AUTOSIZE=.T.
    ENDWITH    
	THIS.ADDOBJECT('TXTF03','TXTF03')
	WITH THIS.TXTF03      
	     .VISIBLE=.T.
	     .LEFT=INT_015*65
	     .TOP=INT_015*14
	     .WIDTH=INT_015*261
	     .HEIGHT=INT_015*25
	     .MAXLENGTH=43
	     .NAME='TXTF03'                    
	ENDWITH     
	THIS.ADDOBJECT('TXTF07','TXTF07')
	WITH THIS.TXTF07      
	     .VISIBLE=.T.
	     .LEFT=INT_015*65
	     .TOP=INT_015*39
	     .WIDTH=INT_015*119
	     .HEIGHT=INT_015*25
	     .MAXLENGTH=10
	     .NAME='TXTF07'         
	ENDWITH     
	THIS.ADDOBJECT('TXTF04','TEXTBOX')
	WITH THIS.TXTF04
	     .VISIBLE=.T.
	     .LEFT=INT_015*65
	     .TOP=INT_015*64
	     .WIDTH=INT_015*100
	     .HEIGHT=INT_015*25
	     .INPUTMASK='999999999999'
	     .NAME='TXTF04'	    
	ENDWITH     
    THIS.ADDOBJECT('TXTF13','TEXTBOX')
    WITH THIS.TXTF13
         .VISIBLE=.T.           
         .LEFT=INT_015*65
         .TOP=INT_015*89
         .WIDTH=INT_015*100
         .HEIGHT=INT_015*25
         .INPUTMASK='999999999999'
         .NAME='TXTF13'
    ENDWITH     
    THIS.ADDOBJECT('TXTF12','TEXTBOX')
    WITH THIS.TXTF12
         .VISIBLE=.T.           
         .LEFT=INT_015*65
         .TOP=INT_015*114
         .WIDTH=INT_015*250
         .HEIGHT=INT_015*25
         .MAXLENGTH=100
         .NAME='TXTF12'
    ENDWITH         
    THIS.ADDOBJECT('TXTF14','TEXTBOX')
    WITH THIS.TXTF14
         .VISIBLE=.F.           
         .LEFT=INT_015*379
         .TOP=INT_015*39
         .WIDTH=INT_015*49         
         .HEIGHT=INT_015*25
         .MAXLENGTH=4
         .NAME='TXTF14'                            
    ENDWITH         
    THIS.ADDOBJECT('CRCY','CRCY')
    THIS.ADDOBJECT('TXTF16','TEXTBOX')
    WITH THIS.TXTF16
         .VISIBLE=.F.           
         .LEFT=INT_015*379
         .TOP=INT_015*64
         .WIDTH=INT_015*100
         .HEIGHT=INT_015*25
         .INPUTMASK='9999.999999'
         .NAME='TXTF16'                            
    ENDWITH     
    
    THIS.ADDOBJECT('TXTF15','TEXTBOX')
    WITH THIS.TXTF15
         .VISIBLE=.F.           
         .LEFT=INT_015*379
         .TOP=INT_015*89
         .WIDTH=INT_015*100
         .HEIGHT=INT_015*25
         .INPUTMASK='9999999.999999'
         .NAME='TXTF15'                            
    ENDWITH     
  ENDPROC       
 PROC INIT       
       THISFORM.PAGEFRAME1.PAGE1.FONTITALIC=.T.
       THISFORM.PAGEFRAME1.PAGE1.FORECOLOR=RGB(0,0,255)      
       THISFORM.PAGEFRAME1.PAGE1.FONTSIZE=INT_015*10
       THISFORM.PAGEFRAME1.PAGE2.FONTSIZE=INT_015*10  
       THISFORM.SETALL('HEIGHT',INT_015*25,'TEXTBOX')
       THISFORM.SETALL('HEIGHT',INT_015*17,'LABEL')
       THISFORM.SETALL('FONTSIZE',INT_015*9,'TEXTBOX')
       THISFORM.SETALL('FONTSIZE',INT_015*9,'LABEL')       
       THISFORM.SETALL('READONLY',.T.,'TEXTBOX')
       THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION=''
       THISFORM.SHRGROUP.VISIBLE=.F.
       THISFORM.SHRGROUP.ENABLED=.F.       
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'COLUMN')
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'HEADER')    
       THISFORM.GRID1.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)
       THISFORM.GRID2.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)
       THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='取消單號'
       THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='客戶編號'
       THISFORM.GRID1.COLUMN3.HEADER1.CAPTION='客戶簡稱'
       THISFORM.GRID1.COLUMN1.CONTROLSOURCE='C08_1.F01'
       THISFORM.GRID1.COLUMN2.CONTROLSOURCE='C08_1.F06'
       THISFORM.GRID1.COLUMN3.CONTROLSOURCE='C01.F05'
       THISFORM.GRID1.COLUMN1.WIDTH=INT_015*81
       THISFORM.GRID1.COLUMN2.WIDTH=INT_015*49
       THISFORM.GRID1.COLUMN3.WIDTH=INT_015*60
       THISFORM.GRID1.SETALL("DYNAMICBACKCOLOR","IIF(C08_1.F10<>'2',RGB(255,0,0),'')","COLUMN")         
       THISFORM.GRID2.SETALL('FONTSIZE',INT_015*9,'COLUMN')
       THISFORM.GRID2.SETALL('FONTSIZE',INT_015*9,'HEADER')        
       THISFORM.GRID2.COLUMN1.HEADER1.CAPTION='料品編號'
       THISFORM.GRID2.COLUMN2.HEADER1.CAPTION='品名規格'
       THISFORM.GRID2.COLUMN3.HEADER1.CAPTION='訂單編號'
	   THISFORM.GRID2.COLUMN4.HEADER1.CAPTION='計價數量'
	   THISFORM.GRID2.COLUMN5.HEADER1.CAPTION='無價數量'
	   THISFORM.GRID2.COLUMN6.HEADER1.CAPTION='備註說明'
	   THISFORM.GRID2.COLUMN7.HEADER1.CAPTION='安全資料'
	   THISFORM.GRID2.LINKMASTER='C08_1'
       THISFORM.GRID2.RELATIONALEXPR='F01'
	   THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C08.F03'
	   THISFORM.GRID2.COLUMN2.CONTROLSOURCE='B01.F02'
	   THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C08.F07'
	   THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C08.F04'
	   THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C08.F13'
	   THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C08.F12'
	   THISFORM.GRID2.COLUMN7.CONTROLSOURCE='C08.F11'
	   THISFORM.GRID2.COLUMN1.WIDTH=INT_015*149
	   THISFORM.GRID2.COLUMN2.WIDTH=INT_015*140
       THISFORM.GRID2.COLUMN3.WIDTH=INT_015*75
       THISFORM.GRID2.COLUMN4.WIDTH=INT_015*70
       THISFORM.GRID2.COLUMN5.WIDTH=INT_015*70
       THISFORM.GRID2.COLUMN6.WIDTH=INT_015*100
       THISFORM.GRID2.COLUMN7.WIDTH=INT_015*135
       THISFORM.GRID1.READONLY=.T.      
       THISFORM.GRID2.READONLY=.T.            
       THISFORM.GRID1.SETFOCUS
       IF THISFORM.GRID1.ACTIVEROW=0
          THISFORM.CMDGROUP.ENABLED=.F.
          THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
          THISFORM.ANS_BOTT.ENABLED=.F.
       ELSE
          THISFORM.CMDGROUP.ENABLED=.T.      
          THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.) .AND. C08_1.F10<>'2'  &&判斷有無修改的權限
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)  .AND. C08_1.F10<>'2' &&判斷有無刪除的權限
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限       
          THISFORM.ANS_BOTT.ENABLED=IIF(C08_1.F10='2',.F.,.T.)  .AND. IIF(A02.F11='*',.T.,.F.) .AND. !THISFORM.SHRGROUP.ENABLED
       ENDIF          
       THISFORM.KEY_LIST.DISPLAYVALUE='依取消單號排列'      
       JK='取消單號'
       SELE C08_1
       THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE=C08_1.F01
  ENDPROC       
  PROCEDURE PAGEFRAME1.PAGE1.ACTIVATE
     R=0
     SELE C08_1   
     IF THISFORM.SHRGROUP.VISIBLE=.F.
        THISFORM.GRID1.SETALL("DYNAMICBACKCOLOR","IIF(C08_1.F10<>'2',RGB(255,0,0),'')","COLUMN")         
        THISFORM.GRID1.ENABLED=.T.   
        THISFORM.GRID1.SETFOCUS   
        THISFORM.KEY_LIST.ENABLED=.T.
        THISFORM.MTH_LIST.ENABLED=.T.
     ELSE
       THISFORM.KEY_LIST.ENABLED=.F.   
       THISFORM.MTH_LIST.ENABLED=.F.   
     ENDIF                  
        THISFORM.PAGEFRAME1.PAGE1.FONTITALIC=.T.
        THISFORM.PAGEFRAME1.PAGE1.FORECOLOR=RGB(0,0,255)
        THISFORM.PAGEFRAME1.PAGE2.FONTITALIC=.F.
        THISFORM.PAGEFRAME1.PAGE2.FORECOLOR=RGB(0,0,0)          
    IF THISFORM.GRID1.ACTIVEROW=0 .AND. THISFORM.SHRGROUP.ENABLED=.F.
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.F.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
        THISFORM.ANS_BOTT.ENABLED=.F.
        THISFORM.PAGEFRAME1.PAGE1.SETALL('VALUE','','TEXTBOX')        
        THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE=''
        THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE=''
        THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE=''
        THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE=''
        THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE=''   
        THISFORM.PAGEFRAME1.PAGE1.LBLF061.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE1.LBLF091.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION=''   
        THISFORM.PAGEFRAME1.PAGE1.LBLF111.CAPTION=''                  
        THISFORM.PAGEFRAME1.PAGE1.LBLF901.CAPTION='' 
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL11.CAPTION='' 
        THISFORM.PAGEFRAME1.PAGE2.ENABLED=.F.      
     ELSE
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.T.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
        THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.)  .AND. C08_1.F10<>'2' &&判斷有無修改的權限
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)   .AND. C08_1.F10<>'2' &&判斷有無刪除的權限
        THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)    &&判斷有無列印的權限  
        THISFORM.ANS_BOTT.ENABLED=IIF(C08_1.F10='2',.F.,.T.) .AND. IIF(A02.F11='*',.T.,.F.) .AND. !THISFORM.SHRGROUP.ENABLED
        THISFORM.PAGEFRAME1.PAGE2.ENABLED=.T.
     ENDIF   
     THISFORM.ORPGROUP.NEW_BOTT.ENABLED=IIF(A02.F04='*',.T.,.F.);
     .AND. !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F07,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.)
  ENDPROC
  PROCEDURE PAGEFRAME1.PAGE2.ACTIVATE
       SELE C08 
    IF THISFORM.SHRGROUP.ENABLED=.F.
        THISFORM.GRID2.READONLY=.T.     
        THISFORM.GRID2.SETFOCUS   
     ENDIF  
        THISFORM.PAGEFRAME1.PAGE1.FONTITALIC=.F.
        THISFORM.PAGEFRAME1.PAGE1.FORECOLOR=RGB(0,0,0)
        THISFORM.PAGEFRAME1.PAGE2.FONTITALIC=.T.
        THISFORM.PAGEFRAME1.PAGE2.FORECOLOR=RGB(0,0,255)          
     IF THISFORM.GRID2.ACTIVEROW=0 .AND. THISFORM.SHRGROUP.ENABLED=.F.
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.F.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
        THISFORM.ANS_BOTT.ENABLED=.F.
        THISFORM.PAGEFRAME1.PAGE2.SETALL('VALUE','','TEXTBOX')
        THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE=''
        THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=''
        THISFORM.PAGEFRAME1.PAGE2.LBLF171.CAPTION='0'
     ELSE
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.T.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
        THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.) .AND. C08.F10<>'2'  &&判斷有無修改的權限
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)  .AND. C08.F10<>'2' &&判斷有無刪除的權限
        THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)  &&&&判斷有無列印的權限  
        IF A02.F10='*' &&判斷有無查看單價的權限
	        THISFORM.PAGEFRAME1.PAGE2.LBLF14.VISIBLE=.T.
	        THISFORM.PAGEFRAME1.PAGE2.TXTF14.VISIBLE=.T.
	        THISFORM.PAGEFRAME1.PAGE2.LBLF15.VISIBLE=.T.
	        THISFORM.PAGEFRAME1.PAGE2.TXTF15.VISIBLE=.T.
	        THISFORM.PAGEFRAME1.PAGE2.LBLF16.VISIBLE=.T.
	        THISFORM.PAGEFRAME1.PAGE2.TXTF16.VISIBLE=.T.
	        THISFORM.PAGEFRAME1.PAGE2.LBLF17.VISIBLE=.T.
	        THISFORM.PAGEFRAME1.PAGE2.LBLF171.VISIBLE=.T.
	    ENDIF       
        THISFORM.ANS_BOTT.ENABLED=IIF(C08.F10='2',.F.,.T.) .AND. IIF(A02.F11='*',.T.,.F.) .AND. !THISFORM.SHRGROUP.ENABLED
     ENDIF   
     R=RECNO('&AREA1')
     THISFORM.GRID1.SETALL("DYNAMICBACKCOLOR","IIF(RECNO('&AREA1')=R,RGB(255,255,0),'')","COLUMN")
     THISFORM.GRID1.ENABLED=.F.     
     THISFORM.ORPGROUP.NEW_BOTT.ENABLED=IIF(A02.F04='*',.T.,.F.)   .AND. C08_1.F10<>'2' &&判斷有無新增的權限
     THISFORM.KEY_LIST.ENABLED=.F.     
     THISFORM.MTH_LIST.ENABLED=.F.     
  ENDPROC             
  PROC KEY_LIST.INIT 
       WITH THIS 
           .ADDITEM('依取消單號排列')
           .ADDITEM('依客戶編號排列')
       ENDWITH      
  ENDPROC 
  PROC KEY_LIST.INTERACTIVECHANGE                 
       SELE C08_1 
       DO CASE
          CASE THIS.DISPLAYVALUE='依取消單號排列'
               SET ORDER TO 1 
               THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='取消單號'
               THISFORM.GRID1.COLUMN1.CONTROLSOURCE='C08_1.F01'
               THISFORM.GRID1.COLUMN1.WIDTH=INT_015*81
               THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='客戶編號'
               THISFORM.GRID1.COLUMN2.CONTROLSOURCE='C08_1.F06'
               THISFORM.GRID1.COLUMN2.WIDTH=INT_015*49
               THISFORM.GRID1.COLUMN3.HEADER1.CAPTION='客戶簡稱'
               THISFORM.GRID1.COLUMN3.CONTROLSOURCE='C01.F05'
               THISFORM.GRID1.COLUMN3.WIDTH=INT_015*60                       
          CASE THIS.DISPLAYVALUE='依客戶編號排列'
               SET ORDER TO 2
               THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='客戶編號'
               THISFORM.GRID1.COLUMN1.CONTROLSOURCE='C08_1.F06'
               THISFORM.GRID1.COLUMN1.WIDTH=INT_015*49
               THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='客戶簡稱'
               THISFORM.GRID1.COLUMN2.CONTROLSOURCE='C01.F05'
               THISFORM.GRID1.COLUMN2.WIDTH=INT_015*60
               THISFORM.GRID1.COLUMN3.HEADER1.CAPTION='取消單號'
               THISFORM.GRID1.COLUMN3.CONTROLSOURCE='C08_1.F01'
               THISFORM.GRID1.COLUMN3.WIDTH=INT_015*81                                                          
       ENDCASE 
       THISFORM.GRID1.SETFOCUS
  ENDPROC      
  PROC MTH_LIST.INTERACTIVECHANGE
       THISFORM.GRID1.RECORDSOURCE=''
       THISFORM.GRID2.RECORDSOURCE=''
       THISFORM.GRID2.LINKMASTER=''
       THISFORM.GRID2.RELATIONALEXPR=''
       THISFORM.GRID2.CHILDORDER=''
       SELE A24
       USE
       SELECT A23
       SEEK DTOS(CTOD(THIS.DISPLAYVALUE+'/01'))
       A24='A24'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       IF !USED('&A24')
          SELE 0
          USE (A24) ALIA A24
       ELSE
          SELE A24
       ENDIF
       SET ORDER TO 1             
       SELE C08
       SET RELA OFF INTO B01
       SET RELA OFF INTO C08_1
       USE
       SELE C08_1
       SET RELA OFF INTO C01
       USE
       C08='C08'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       C081='C081'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       IF !USED('&C08')
          SELE 0
          USE (C08) ALIA C08
       ELSE
          SELE C08
       ENDIF
       SET ORDER TO 1      
       SET RELA TO F03 INTO B01
       CREATE CURSOR C08_1;
       (F01 C(10),F02 C(2),F06 C(5),F09 C(5),F10 C(1),F11 C(17),F21 C(60),F90 C(17))
       INDE ON F01 TAG C08_11
       INDE ON F06+F01 TAG C08_12
       SELE F01,F02,F06,F09,F10,F11,F21,F90 FROM C08 GROUP BY F01 ORDER BY F01 INTO CURSOR C08_2
       SELE C08_2
       GO TOP
       DO WHILE !EOF()
          SELE C08_1
          APPEND BLANK
          REPL F01 WITH C08_2.F01
          REPL F02 WITH C08_2.F02
          REPL F06 WITH C08_2.F06   
          REPL F09 WITH C08_2.F09
          REPL F10 WITH C08_2.F10
          REPL F11 WITH C08_2.F11
          REPL F21 WITH C08_2.F21
          REPL F90 WITH C08_2.F90
          SELE C08_2
          SKIP
       ENDDO
       SELE C08_2
       USE   
       SELE C08_1
       SET ORDER TO 1
       SET RELA TO F06 INTO C01
       THISFORM.GRID1.RECORDSOURCE='C08_1'
       THISFORM.GRID2.RECORDSOURCE='C08'
       THISFORM.GRID2.LINKMASTER='C08_1'
       THISFORM.GRID2.RELATIONALEXPR='F01'      
       THISFORM.GRID2.CHILDORDER=C081  
	   THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C08.F03'
	   THISFORM.GRID2.COLUMN2.CONTROLSOURCE='B01.F02'
	   THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C08.F07'
	   THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C08.F04'
	   THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C08.F13'
	   THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C08.F12'
	   THISFORM.GRID2.COLUMN7.CONTROLSOURCE='C08.F11'            
       THISFORM.KEY_LIST.INTERACTIVECHANGE
	   THISFORM.PAGEFRAME1.ACTIVEPAGE=1
	   THISFORM.REFRESH
	   THISFORM.GRID1.SETFOCUS        
       IF THISFORM.GRID1.ACTIVEROW=0
          THISFORM.CMDGROUP.ENABLED=.F.
          THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
          THISFORM.ANS_BOTT.ENABLED=.F.
       ELSE
          THISFORM.CMDGROUP.ENABLED=.T.      
          THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.) .AND. C08_1.F10<>'2'  &&判斷有無修改的權限
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)  .AND. C08_1.F10<>'2' &&判斷有無刪除的權限
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限    
       ENDIF          
*!*	       THISFORM.KEY_LIST.DISPLAYVALUE='依出貨單號排列'      
*!*	       JK='訂單編號'
*!*	       SELE C08_1
*!*	       THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE=C08_1.F01	   
*       THISFORM.REFRESH       
  ENDPROC
  PROC GRID1.AFTERROWCOLCHANGE
       LPARAMETERS NCOLINDEX
       SELECT C08_1
       THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE=C08_1.F01
       THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE=C08_1.F06
       THISFORM.PAGEFRAME1.PAGE1.LBLF061.CAPTION=C01.F04
       THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE=C08_1.F09
       THISFORM.PAGEFRAME1.PAGE1.LBLF091.CAPTION=IIF(SEEK(C08_1.F09,'A01'),A01.F03,'')
       THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE=C08_1.F21    
       THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE=C08_1.F02
       THISFORM.PAGEFRAME1.PAGE1.PASS_CND.BACKCOLOR=IIF(C08_1.F10='2',RGB(0,255,0),RGB(255,0,0))
       THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION=IIF(C08_1.F10='2','    已確認    ','    未確認    ')
       THISFORM.PAGEFRAME1.PAGE1.LBLF111.CAPTION=C08_1.F11
       THISFORM.PAGEFRAME1.PAGE1.LBLF901.CAPTION=C08_1.F90
       THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.) .AND. C08_1.F10<>'2'  &&判斷有無修改的權限
       THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)  .AND. C08_1.F10<>'2' &&判斷有無刪除的權限
       THISFORM.ANS_BOTT.ENABLED=IIF(C08_1.F10='2',.F.,.T.) .AND. IIF(A02.F11='*',.T.,.F.)  .AND. !THISFORM.SHRGROUP.ENABLED 
       THISFORM.GRID1.HIGHLIGHTBACKCOLOR=IIF(C08_1.F10<>'2',RGB(255,0,0),RGB(58,186,152))
       THISFORM.PAGEFRAME1.PAGE1.LBLTTL11.CAPTION=TRANSFORM(TTL1(THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE),'@R 999999999.99')
       FCH=THISFORM.ACTIVECONTROL.NAME
       JK=THIS.COLUMN1.HEADER1.CAPTION  
       IF THIS.ACTIVEROW=0
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
       ELSE
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
       ENDIF   
       CHK=''     
*       THISFORM.REFRESH
  ENDPROC     
  PROC GRID2.AFTERROWCOLCHANGE
       LPARAMETERS NCOLINDEX
       SELECT C08
       THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE=C08.F03
       THISFORM.PAGEFRAME1.PAGE2.LBLF031.CAPTION=B01.F02
       THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=C08.F07       
       THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE=C08.F04
       THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE=C08.F13
       THISFORM.PAGEFRAME1.PAGE2.TXTF12.VALUE=C08.F12
       THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=C08.F14
       THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE=C08.F16       
       THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE=C08.F15
       THISFORM.PAGEFRAME1.PAGE2.LBLF171.CAPTION=TRANSFORM(F17,'99999999999.99')
       THISFORM.PAGEFRAME1.PAGE2.LBLF111.CAPTION=F11       
       IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
          THISFORM. CMDGROUP.SEEK_BOTT.ENABLED=.F.
       ENDIF   
       FCH=THISFORM.ACTIVECONTROL.NAME
       JK=THIS.COLUMN1.HEADER1.CAPTION
       CHK=THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE       
*       THISFORM.REFRESH
  ENDPROC 
  PROCEDURE ORPGROUP.NEW_BOTT.CLICK    
    THISFORM.KEY_LIST.ENABLED=.F. 
    THISFORM.MTH_LIST.ENABLED=.F. 
    THISFORM.ANS_BOTT.ENABLED=.F.
    IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1       
       THISFORM.GRID2.RECORDSOURCE=''
       THISFORM.GRID2.CHILDORDER=''
       THISFORM.PAGEFRAME1.PAGE1.SETALL('READONLY',.F.,'TEXTBOX')     &&處理表頭新增
       THISFORM.GRID1.ENABLED=.F.   
       THISFORM.GRID2.ENABLED=.F.   
*       IF INT_099=.T.
          H='C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
          SELE A24   
          SET ORDER TO 1
          SEEK H           
          IF FOUND() 
               PO_NO=F08
               RLOCK()
               DELE 
               UNLOCK
          ELSE
             SELE A09
             SEEK H            
             IF !FOUND()                                                  &&如果為本月第一張訂單則重頭開始編號
	         APPEND BLANK                                                
		 REPLACE  F01 WITH 'C007 '
	         REPLACE  F02 WITH  SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
	         REPLACE  F05 WITH 'CH'+F02
	         REPLACE  F06 WITH '業務取消單'
		 REPLACE  F08 WITH ALLTRIM(F05)+'0000'
             ENDIF
	     LOCK()
	    HX=VAL(RIGHT(F08,4))+1
	    PO_NO=LEFT(F08,6)+PADL(ALLTRIM(STR(HX)),4,'0')
	    REPLACE  F08 WITH PO_NO                                             &&記錄本訂單號碼,本月份後續的訂單號碼將以此往下編
	    UNLOCK
          ENDIF       
          THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE=PO_NO
          THISFORM.PAGEFRAME1.PAGE1.TXTF01.REFRESH
          THISFORM.PAGEFRAME1.PAGE1.TXTF01.READONLY=.T.
          THISFORM.PAGEFRAME1.PAGE1.TXTF06.SETFOCUS
        THISFORM.PAGEFRAME1.PAGE2.ENABLED=.F.
        THISFORM.PAGEFRAME1.PAGE1.TXTF06.READONLY=.F.        
        THISFORM.PAGEFRAME1.PAGE1.TXTF09.READONLY=.F.    
        THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE=''
        THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE=''
        THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE=''      
        THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE=RIGHT(DTOS(DATE()),2)
        THISFORM.PAGEFRAME1.PAGE1.LBLF061.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE1.LBLF091.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE1.LBLF111.CAPTION=''        
        THISFORM.PAGEFRAME1.PAGE1.LBLF901.CAPTION='' 
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL11.CAPTION=''         
     ELSE
        THISFORM.PAGEFRAME1.PAGE1.ENABLED=.F.              &&處理表身新增
        THISFORM.GRID2.ENABLED=.F.   
        THISFORM.PAGEFRAME1.PAGE2.SETALL('READONLY',.F.,'TEXTBOX')     
        THISFORM.PAGEFRAME1.PAGE2.CRCY.VISIBLE=IIF(A02.F10='*',IIF(A02.F08='*',.T.,.F.),.F.)
        THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE=INT_011
        THISFORM.PAGEFRAME1.PAGE2.CRCY.ENABLED=IIF(A02.F10='*',IIF(A02.F08='*',.T.,.F.),.F.)
        THISFORM.PAGEFRAME1.PAGE2.TXTF14.READONLY=IIF(A02.F08='*',.F.,.T.)
        THISFORM.PAGEFRAME1.PAGE2.TXTF15.READONLY=IIF(A02.F08='*',.F.,.T.)   
        THISFORM.PAGEFRAME1.PAGE2.TXTF16.READONLY=IIF(A02.F08='*',.F.,.T.)
        THISFORM.PAGEFRAME1.PAGE2.TXTF03.READONLY=.F.
        THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
        THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE=''          
        THISFORM.PAGEFRAME1.PAGE2.LBLF031.CAPTION=''                  
        THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE=0
        THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE=0
        THISFORM.PAGEFRAME1.PAGE2.TXTF07.READONLY=.F.
        THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=''
        THISFORM.PAGEFRAME1.PAGE2.TXTF12.VALUE=''
        THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE=0
        THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE=1
        THISFORM.PAGEFRAME1.PAGE2.LBLF171.CAPTION=TRANSFORM(0,'999999999999')
        THISFORM.PAGEFRAME1.PAGE2.LBLF111.CAPTION=''               
        THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE
     ENDIF   

  ENDPROC  
  PROCEDURE ORPGROUP.EDIT_BOTT.CLICK
     THISFORM.KEY_LIST.ENABLED=.F. 
     THISFORM.MTH_LIST.ENABLED=.F. 
     THISFORM.ANS_BOTT.ENABLED=.F.
     THISFORM.GRID1.ENABLED=.F.   
     THISFORM.GRID2.ENABLED=.F.   
     IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
        SELE C08_1
        PO_NO=C08_1.F01
        SELE RECNO() FROM C08 WHERE C08.F01=PO_NO AND F10<>'2' INTO ARRAY BK1
        JJ1=''                
        IF _TALLY>0                   
           FOR I= 1 TO ALEN(BK1)
               JJ1=JJ1+ALLTRIM(STR(BK1(I)))+','
           ENDFOR  
           KK1=STUFF(JJ1,RAT(',',JJ1,1),1,'')
           RLOCK(KK1,'C08')
           LL1=RLOCK(KK1,'C08')
        ELSE 
           =MESSAGEBOX('此單據已由別的工作站過帳中無法修改!',0+64,'提示訊息視窗')
           SELE C08_1           
           UNLOCK ALL
           REPL F10 WITH '2'
           THISFORM.SHRGROUP.ABANDON_BOTT.CLICK   
        ENDIF   
        IF LL1 =.T.
           THISFORM.PAGEFRAME1.PAGE1.SETALL('READONLY',.F.,'TEXTBOX')     &&處理表頭修改
           THISFORM.PAGEFRAME1.PAGE1.TXTF01.READONLY=.T.
           THISFORM.PAGEFRAME1.PAGE1.TXTF09.READONLY=.F.
           THISFORM.PAGEFRAME1.PAGE2.ENABLED=.F.
           THISFORM.PAGEFRAME1.PAGE1.TXTF06.SETFOCUS
        ELSE 
           DO FILE_IMPACT
           UNLOCK ALL
           THISFORM.SHRGROUP.ABANDON_BOTT.CLICK
        ENDIF   
     ELSE           
        THISFORM.PAGEFRAME1.PAGE1.ENABLED=.F.              
        SELE C08                                                      &&處理表身修改
        SELE RECNO() FROM C05 WHERE F01=C08.F07 AND F02=C08.F03 INTO ARRAY BK1
        JJ1=''                
        IF _TALLY>0                   
           FOR I= 1 TO ALEN(BK1)
               JJ1=JJ1+ALLTRIM(STR(BK1(I)))+','
           ENDFOR  
           KK1=STUFF(JJ1,RAT(',',JJ1,1),1,'')
           RLOCK(KK1,'C05')
           LL1=RLOCK(KK1,'C05')
        ELSE
           LL1=.T.   
        ENDIF 
           SELE C04
           SEEK C08.F07+C08.F03
           IF FOUND()
              RLOCK()
              LL2=RLOCK()
           ELSE
              LL2=.T.   
           ENDIF  
        IF RLOCK('C08') .AND. LL1=.T. .AND. LL2=.T.                                               
           THISFORM.PAGEFRAME1.PAGE2.SETALL('READONLY',.F.,'TEXTBOX') 
           THISFORM.PAGEFRAME1.PAGE2.CRCY.VISIBLE=IIF(A02.F10='*',IIF(A02.F08='*',.T.,.F.),.F.)          
           THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE=THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE
           THISFORM.PAGEFRAME1.PAGE2.CRCY.ENABLED=IIF(A02.F10='*',IIF(A02.F08='*',.T.,.F.),.F.)           
	       THISFORM.PAGEFRAME1.PAGE2.TXTF14.READONLY=IIF(A02.F08='*',.F.,.T.)
           THISFORM.PAGEFRAME1.PAGE2.TXTF15.READONLY=IIF(A02.F08='*',.F.,.T.)   
           THISFORM.PAGEFRAME1.PAGE2.TXTF16.READONLY=IIF(A02.F08='*',.F.,.T.)           
*           THISFORM.PAGEFRAME1.PAGE2.TXTF07.READONLY=EMPTY(A02.F09)            
           THISFORM.PAGEFRAME1.PAGE2.TXTF04.SETFOCUS
        ELSE  
           DO FILE_IMPACT 
           UNLOCK ALL
           THISFORM.SHRGROUP.ABANDON_BOTT.CLICK           
       ENDIF        
     ENDIF   
     RELEASE ALL LIKE BK*
  ENDPROC    
  PROC ORPGROUP.DEL_BOTT.CLICK                    &&刪除資料程序
       IF MESSAGEBOX('是否確定要刪除此筆資料',4+32+256,'請確認') = 6	        
          IF ALIA()='C08_1'           &&刪除整張訂單
             SELE C08_1             
                PO_NO=C08_1.F01
                SELE RECNO() FROM C08 WHERE C08.F01=PO_NO  AND C08.F10<>'2' INTO ARRAY BK1              
                JJ1=''                
                IF _TALLY>0   
                   FOR I= 1 TO ALEN(BK1)
                       JJ1=JJ1+ALLTRIM(STR(BK1(I)))+','
                   ENDFOR    
                   KK1=STUFF(JJ1,RAT(',',JJ1,1),1,'')              
                   RLOCK(KK1,'C08')
                   LL1=RLOCK(KK1,'C08')
                ELSE
                   LL1=.T.   
                ENDIF                   
                SELE RECNO() FROM C05 WHERE F01= ANY (SELE F07 FROM C08 WHERE F01=PO_NO) INTO ARRAY BK2
                JJ2=''                
                IF _TALLY>0                   
                    FOR I= 1 TO ALEN(BK2)
                        JJ2=JJ2+ALLTRIM(STR(BK2(I)))+','
                    ENDFOR  
                    KK2=STUFF(JJ2,RAT(',',JJ2,1),1,'')
                    RLOCK(KK2,'C05')
                    LL2=RLOCK(KK2,'C05')
                ELSE
                   LL2=.T.   
                ENDIF   
                SELE RECNO() FROM C04 WHERE F03+F04=ANY (SELE F07+F03 FROM C08 WHERE F01=PO_NO) INTO ARRAY BK3              
                JJ3=''                
                IF _TALLY>0   
                   FOR I= 1 TO ALEN(BK3)
                       JJ3=JJ3+ALLTRIM(STR(BK3(I)))+','
                   ENDFOR    
                   KK3=STUFF(JJ3,RAT(',',JJ3,1),1,'')              
                   RLOCK(KK3,'C04')
                   LL3=RLOCK(KK3,'C04')
                ELSE
                   LL3=.T.   
                ENDIF                   
                IF LL1 .AND. LL2 .AND. LL3=.T.
                   IF LEN(ALLTRIM(JJ1))>0 
                      SELE C08
                      FOR I= 1 TO ALEN(BK1)
                          GO BK1(I) 
                          SELE C05
                          SET ORDER TO C056                   
                          SEEK C08.F07+C08.F03
                            IF FOUND()
                               QTY=C08.F04+C08.F13
                               DO WHILE F01+F02=C08.F07+C08.F03 
                                  IF F05=0
                                     SKIP
                                  ELSE
                                     IF QTY>F05
                                        QTY=QTY+F05*(-1)   
                                        REPL F05 WITH 0     
                                        SKIP
                                     ELSE
                                        REPL F05 WITH F05+QTY*(-1)
                                        EXIT
                                     ENDIF  
                                  ENDIF                    
                               ENDDO                                  
                            ENDIF                               
                            SELE C04
                            SEEK C08.F07+C08.F03
                            IF FOUND()
                                REPLACE F23 WITH F23+(C08.F04+C08.F13)*(-1)
*                                REPL F19 WITH F19+(C08.F13)*(-1)
                            ENDIF    
                            SELE C08
                       ENDFOR                      
                   ELSE
                      =MESSAGEBOX('此張單據已由別的工作站過帳中,無法刪除!',0+64,'提示訊息視窗')
                      SELE C08_1
                      REPL F10 WITH '2'
                      UNLOCK ALL
                      RETURN   
                   ENDIF    
                   DELE FROM C08 WHERE C08.F01=PO_NO
                   SELE C08_1
                   DELE
                   UNLOCK ALL
                 IF INT_099=.T. .AND. SUBSTR(PO_NO,3,4)=SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
                      SELE A24
                      SET ORDER TO 1
                      SEEK 'C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)+PO_NO
                      IF !FOUND()
                          APPEND BLANK
                          LOCK()
                          REPLACE  F01 WITH 'C007 '
                          REPLACE  F02 WITH SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
		          REPLACE  F05 WITH 'CH'+F02
                          REPLACE  F06 WITH '業務取消單'
                          REPLACE  F08 WITH PO_NO
                          UNLOCK
                        ENDIF    
                  ENDIF  
                ELSE
                   DO FILE_IMPACT                  
                ENDIF
             THISFORM.GRID1.SETFOCUS
             IF THISFORM.GRID1.ACTIVEROW=0
                THISFORM.CMDGROUP.ENABLED=.F.
                THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
                THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.               
                THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
                THISFORM.ANS_BOTT.ENABLED=.F.
             ELSE      
                THISFORM.CMDGROUP.ENABLED=.T.
                THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.)  .AND. C08_1.F10<>'2' &&判斷有無修改的權限
                THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)   .AND. C08_1.F10<>'2' &&判斷有無刪除的權限
                THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限
                THISFORM.ANS_BOTT.ENABLED=IIF(C08_1.F10='2',.F.,.T.) .AND. IIF(A02.F11='*',.T.,.F.)  .AND. !THISFORM.SHRGROUP.ENABLED           
             ENDIF     
          ELSE        
              SELE C08                                                      &&刪除單筆資料及其出貨計劃        
              SELE RECNO() FROM C05 WHERE F01=C08.F07 AND F02=C08.F03 INTO ARRAY BK1
              JJ1=''                
                IF _TALLY>0                   
                    FOR I= 1 TO ALEN(BK1)
                        JJ1=JJ1+ALLTRIM(STR(BK1(I)))+','
                    ENDFOR  
                    KK1=STUFF(JJ1,RAT(',',JJ1,1),1,'')
                    RLOCK(KK1,'C05')
                    LL1=RLOCK(KK1,'C05')
                ELSE
                   LL1=.T.   
                ENDIF 
                SELE C04
                SET ORDER TO C041
                SEEK C08.F07+C08.F03
                IF FOUND()
                   RLOCK()
                   LL2=RLOCK()
                ELSE
                   LL2=.T.   
                ENDIF  
                 IF RLOCK('C08') .AND. LL1=.T. .AND. LL2=.T.
                    IF LEN(ALLTRIM(JJ1))>0
                       SELE C05
                       SET ORDER TO C056
                       SEEK C08.F07+C08.F03
                       IF FOUND()
                          QTY=C08.F04+C08.F13
                          DO WHILE C05.F01+C05.F02=C08.F07+C08.F03 
                             IF C05.F05=0
                                SKIP
                             ELSE
                                IF QTY>C05.F05
                                   QTY=QTY+C05.F05*(-1)   
                                   REPL C05.F05 WITH 0     
                                   SKIP
                                ELSE
                                   REPL C05.F05 WITH C05.F05+QTY*(-1)
                                   EXIT
                                ENDIF  
                             ENDIF                    
                           ENDDO                                  
                        ENDIF                                 
                     ENDIF                        
                     SELE C04
                     SEEK C08.F07+C08.F03
                     IF FOUND()
                        REPLACE  C04.F23 WITH C04.F23+(C08.F04+C08.F13)*(-1)
*                        REPL F19 WITH F19+(C08.F13)*(-1)
                     ENDIF                       
                     SELE C08
                     DELE
                     SKIP -1
                     IF BOF()
                        GO TOP
                     ENDIF   
                  ELSE
                    DO FILE_IMPACT                  
                  ENDIF     
              THISFORM.GRID2.SETFOCUS
              IF THISFORM.GRID2.ACTIVEROW=0         &&如果單身被刪空
                 SELE C08_1                        
                 PO_NO=C08_1.F01                    
                 DELE                               &&連表頭也要刪除
                 IF INT_099=.T. .AND. SUBSTR(PO_NO,3,4)=SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
                      SELE A24
                      SET ORDER TO 1
                      SEEK 'C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)+PO_NO
                      IF !FOUND()
                          APPEND BLANK
                          LOCK()
                          REPLACE  F01 WITH 'C007 '
                          REPLACE  F02 WITH SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
		                  REPLACE  F05 WITH 'CH'+F02
                          REPLACE  F06 WITH '業務取消單'
                          REPLACE  F08 WITH PO_NO
                          UNLOCK                 
                      ENDIF    
                 ENDIF
                 SELE C08_1
                 SKIP -1
                 IF BOF()
                    GO TOP
                 ENDIF   
                 THISFORM.PAGEFRAME1.ACTIVEPAGE=1 
                 THISFORM.REFRESH          
              ENDIF
          ENDIF
       ENDIF
       RELEASE ALL LIKE BK*   
  ENDPROC  
  PROCEDURE SHRGROUP.SHURE1_BOTT.CLICK               &&新增確認
      IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
         THISFORM.GRID2.RECORDSOURCE='C08'
         THISFORM.GRID2.CHILDORDER=C081
	     THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C08.F03'
	     THISFORM.GRID2.COLUMN2.CONTROLSOURCE='B01.F02'
	     THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C08.F07'
	     THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C08.F04'
	     THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C08.F13'
	     THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C08.F12'
	     THISFORM.GRID2.COLUMN7.CONTROLSOURCE='C08.F11'       
         SELE C08_1 
         COD=SYS(21)
         SET ORDER TO 1
         IF SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE,'C08_1')=.T.    &&如果單號重覆
             SELE A24
             SEEK 'C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)+THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE
             IF FOUND()
                 DO WHILE F01+F02+F08='C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)+THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE
                        RLOCK()
                        DELE
                        UNLOCK
                 ENDDO   
             ENDIF                   
             SELE A09
             SEEK 'C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
             IF FOUND()
                 RLOCK()
		         HX=VAL(RIGHT(F08,4))+1
   		         PO_NO=LEFT(F08,6)+PADL(ALLTRIM(STR(HX)),4,'0')
		         REPLACE  F08 WITH PO_NO                                             &&記錄本訂單號碼,本月份後續的訂單號碼將以此往下編
		         UNLOCK
		         THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE=PO_NO
		         THISFORM.PAGEFRAME1.PAGE1.TXTF01.REFRESH
             ENDIF   		           
       ENDIF
       IF SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE,'C01')=.F. .OR. EMPTY(THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE)
          =MESSAGEBOX('客戶基本主檔中無此編號請先建立!',0+64,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE1.TXTF06.SETFOCUS
          SET ORDER TO &COD
          RETURN            
       ENDIF       
       SELE RECNO() FROM C05 WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE AND F04>F05 INTO ARRAY RC1
       IF _TALLY=0       

             =MESSAGEBOX('此客戶已無出貨計劃可取消!',0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE1.TXTF06.SETFOCUS             
             SET ORDER TO &COD
             RETURN                        

       ENDIF   
       IF EMPTY(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/'+THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE))          
          =MESSAGEBOX('取消日期輸入錯誤!',0+64,'提示訊息視窗') 
          THISFORM.PAGEFRAME1.PAGE1.TXTF02.SETFOCUS
          SET ORDER TO &COD          
          RETURN
       ENDIF   
       SELE C08_1          
       APPEND BLANK
       LOCK()
       IF RLOCK()
          REPLACE F01 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE
          REPLACE F02 WITH PADL(ALLTRIM(THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE),2,'0')
          REPLACE F06 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE
          REPLACE F09 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE
          REPLACE F11 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
          REPLACE F21 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE    
       ENDIF
*       UNLOCK
       SEEK THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE
       SET ORDER TO &COD
       THISFORM.PAGEFRAME1.PAGE1.ENABLED=.F.
       THISFORM.PAGEFRAME1.PAGE2.ENABLED=.T.  
       THISFORM.PAGEFRAME1.ACTIVEPAGE=2
       THISFORM.ORPGROUP.NEW_BOTT.CLICK
       THISFORM.REFRESH
    ELSE
       IF SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'B01')=.F.                      &&表身新增確認
          =MESSAGEBOX('物料基本主檔中無此料號!',0+48,'提示訊息視窗')          
          THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
          RETURN
       ENDIF   
       IF  EMPTY(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE)
          =MESSAGEBOX('必須有訂單才可取消!',0+64,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF07.SETFOCUS
          RETURN
       ENDIF   
       
       IF SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE;
          +THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE,'C08')=.T. 
          =MESSAGEBOX('此訂單號碼及料號在此張取消單重複!',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE=''
          THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=''
          THISFORM.PAGEFRAME1.PAGE2.TXTF03.REFRESH
          THISFORM.PAGEFRAME1.PAGE2.TXTF07.REFRESH
          THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
          RETURN            
       ENDIF           
       IF SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C05','C057')=.F.
          =MESSAGEBOX('欲取消之資料錯誤!',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF07.SETFOCUS
          RETURN
       ENDIF
       
          SELECT RECNO() FROM C05 WHERE F01+F02=THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE AND ;
          F04-F05>0 AND !EMPTY(F15) INTO ARRAY RC2
          IF _TALLY>0
             RR1=''
             FOR I= 1 TO ALEN(RC2)
                 RR1=RR1+ALLTRIM(STR(RC2(I)))+','
             ENDFOR    
             SS1=STUFF(RR1,RAT(',',RR1,1),1,'')                           
             IF RLOCK(SS1,'C05')<>.T.
                DO file_impact
                THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
                RETURN
             ENDIF
          ELSE
             =MESSAGEBOX('出貨計劃無此筆資料!',0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
             RETURN          
          ENDIF      
          IF THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE>;
             IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),;
             C04.F10-C04.F23,0)
             =MESSAGEBOX('計價量不得大於未出貨數量';
             +ALLTRIM(STR(IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),;
             C04.F10-C04.F23,0))),0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF04.SETFOCUS
             RETURN
          ENDIF          
          IF THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE>;
             IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F16-C04.F19,0)
             =MESSAGEBOX('無價量不得大於未出貨數量';
             +ALLTRIM(STR(IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F16-C04.F19,0))),0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF13.SETFOCUS
             RETURN
          ENDIF                 
          IF THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE<=0;
             .OR. THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE>;
             IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F10-C04.F23,0)
             =MESSAGEBOX('計價量與無價量總合不得小於等於 0 或大於未出貨數量';
             +ALLTRIM(STR(IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F10-C04.F23,0))),0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF04.SETFOCUS
             RETURN
          ENDIF   
          IF EMPTY(THISFORM.PAGEFRAME1.PAGE2.TXTF12.VALUE)
             =MESSAGEBOX('備註不得空白,請必須註明取消原因與狀況!',0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF12.SETFOCUS
             RETURN
          ENDIF
      SELE C04
      SEEK THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE
      IF FOUND()
         IF RLOCK()
            REPLACE F23 WITH F23+(THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE)
         ELSE
            DO FILE_IMPACT
            RETURN  
         ENDIF   
      ENDIF         
       SELE C08
       APPEND BLANK
       LOCK()
       IF RLOCK()
          REPLACE F01 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE
          REPLACE F02 WITH PADL(ALLTRIM(THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE),2,'0')
          REPLACE F03 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE
          REPLACE F04 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE
          REPLACE F06 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE
          REPLACE F07 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE
          REPLACE F09 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE                    
          REPLACE F11 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
          REPLACE F12 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF12.VALUE
          REPLACE F13 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE          
          REPLACE F14 WITH THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE
          REPLACE F15 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE          
          REPLACE F16 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE                    
          REPLACE F17 WITH ROUND(IIF(THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE=1,THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE,;
          THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE),INT_069)
          REPLACE F21 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE   
      ENDIF
      UNLOCK ALL         
      SEEK THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE                                    
      THISFORM.GRID2.ENABLED=.T.
      THISFORM.GRID2.SETFOCUS  
      SELE C05                 
      SET ORDER TO C054                                                          &&寫入出貨計劃
      SEEK C08.F07+C08.F03
      IF FOUND()
         QTY=C08.F04+C08.F13
         DO WHILE F01+F02=C08.F07+C08.F03 
            IF F04-F05=0
               SKIP
            ELSE
               IF QTY>F04-F05
                  QTY=QTY+(F04-F05)*(-1)   
                  REPL F05 WITH F04     
                  SKIP
               ELSE
                  REPL F05 WITH F05+QTY
                  EXIT
               ENDIF  
            ENDIF                    
         ENDDO   
      ENDIF               
      THISFORM.ORPGROUP.NEW_BOTT.CLICK      
    ENDIF  
    RELEASE ALL LIKE RC*
  ENDPROC
  PROCEDURE SHRGROUP.SHURE2_BOTT.CLICK                          &&修改確認
     IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
       IF EMPTY(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/'+THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE))          
          =MESSAGEBOX('出貨日期輸入錯誤!',0+64,'提示訊息視窗') 
          THISFORM.PAGEFRAME1.PAGE1.TXTF02.SETFOCUS
          RETURN
        ENDIF           
           SELE C08
           SEEK C08_1.F01
           IF FOUND()
              DO WHILE F01=C08_1.F01
                 REPL F02 WITH PADL(ALLTRIM(THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE),2,'0')
                 REPL F09 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE
                 REPL F11 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')                 
                 REPL F21 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE
                REPLACE F21 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE  
                SKIP
              ENDDO    
           ENDIF        
        SELE C08_1
*        IF RLOCK() 
           REPL F02 WITH PADL(ALLTRIM(THISFORM.PAGEFRAME1.PAGE1.TXTF02.VALUE),2,'0')
           REPL F09 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE
           REPL F21 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF21.VALUE     
           REPL F11 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
           UNLOCK ALL
*        ELSE
*           DO FILE_IMPACT
*          RETURN   
*       ENDIF    
     ELSE                                                        &&表身修改確認     
       IF SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'B01')=.F.
          =MESSAGEBOX('物料基本主檔中無此料號!',0+48,'提示訊息視窗')          
          THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
          RETURN
       ENDIF   
          IF THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE<>C08.F03+C08.F07
             IF SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF01.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE;
                +THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE,'C08')=.T.            
                =MESSAGEBOX('此訂單號碼及料號在此張取消單重複!',0+48,'提示訊息視窗')
                THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
                RETURN            
             ENDIF    
          ENDIF           
       IF ALLTRIM(A02.F09)<>'*'  .OR. !EMPTY(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE)  &&如果沒有無訂單出貨的權限才做以下判斷
          IF SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C05')=.F.             
             =MESSAGEBOX('出貨計劃無此筆資料!',0+64,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF03.SETFOCUS
             RETURN
          ENDIF   

          IF THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE>;
             IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),;
             C04.F10-C04.F23+C08.F04,0)
             =MESSAGEBOX('計價量不得大於未出貨數量';
             +ALLTRIM(STR(IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),;
             C04.F10-C04.F23+C08.F04,0))),0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF04.SETFOCUS
             RETURN
          ENDIF          
          IF THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE>;
             IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F16-C04.F19,0) 
             =MESSAGEBOX('無價量不得大於未出貨數量';
             +ALLTRIM(STR(IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F16-C04.F19,0))),0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF13.SETFOCUS
             RETURN
          ENDIF                 
          IF THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE<=0;
             .OR. THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE>;
             IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F10-C04.F23+(C08.F04+C08.F13),0) 
             =MESSAGEBOX('計價量與無價量總合不得小於等於 0 或大於未出貨數量';
             +ALLTRIM(STR(IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F10-C04.F23+(C08.F04+C08.F13),0))),0+48,'提示訊息視窗')
             THISFORM.PAGEFRAME1.PAGE2.TXTF04.SETFOCUS
             RETURN
          ENDIF   
       ENDIF   
       SELE C04
       SEEK C08.F07+C08.F03
*       IF RLOCK('04') .AND. RLOCK('C04')      
*       IF RLOCK()
          SELE C05                 
          SET ORDER TO C056                                                          &&寫入出貨計劃
          SEEK C08.F07+C08.F03
          IF FOUND()
             QTY=C08.F04+C08.F13
             DO WHILE F01+F02=C08.F07+C08.F03 
                IF F05=0
                   SKIP
                ELSE
                   IF QTY>F05
                      QTY=QTY+F05*(-1)   
                      REPL F05 WITH 0     
                      SKIP
                   ELSE
                      REPL F05 WITH F05+QTY*(-1)
                      EXIT
                   ENDIF  
                ENDIF                    
             ENDDO   
          ENDIF                          
          SELE C04                                                              &&將訂單檔回復成為輸入前之狀態
          SEEK C08.F07+C08.F03
          IF FOUND()
             REPLACE F23 WITH F23+(C08.F04+C08.F13)*(-1)
          ENDIF   
           SELE C08                    
           REPLACE F03 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE
           REPLACE F04 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE
           REPLACE F07 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE
           REPLACE F11 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')                      
           REPLACE F12 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF12.VALUE
           REPLACE F13 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE
           REPLACE F14 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE
           REPLACE F15 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE
           REPLACE F16 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE
           REPLACE F17 WITH ROUND(IIF(THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE=1,THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE,;
           THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE),INT_069)
           SELE C04                                                                 &&寫回訂單檔    
           SEEK C08.F07+C08.F03
           IF FOUND()
              REPLACE F23 WITH F23+(C08.F04+C08.F13)
           ENDIF    
          SELE C05                 
          SET ORDER TO C054                                                          &&寫入出貨計劃
          SEEK C08.F07+C08.F03
          IF FOUND()
             QTY=C08.F04+C08.F13
             DO WHILE F01+F02=C08.F07+C08.F03 
                IF F04-F05=0
                  SKIP
                ELSE
                   IF QTY>F04-F05
                      QTY=QTY+(F04-F05)*(-1)   
                      REPL F05 WITH F04     
                      SKIP
                   ELSE
                      REPL F05 WITH F05+QTY
                      EXIT
                   ENDIF  
                ENDIF                    
             ENDDO   
          ENDIF                                    
          UNLOCK ALL
 *      ELSE
*         DO FILE_IMPACT
*          RETURN   
*       ENDIF   
    ENDIF   
    THISFORM.SHRGROUP.ABANDON_BOTT.CLICK    
  ENDPROC   
  PROCEDURE SHRGROUP.ABANDON_BOTT.CLICK
      THISFORM.SHRGROUP.ENABLED=.F.
      THISFORM.SHRGROUP.VISIBLE=.F.      
      THISFORM.ORPGROUP.ENABLED=.T.
      THISFORM.ORPGROUP.SETALL('FORECOLOR',RGB(0,0,0),'COMMANDBUTTON')
      THISFORM.CMDGROUP.ENABLED=.T.
      THISFORM.CMDGROUP.SETALL('ENABLED',.T.,'COMMANDBUTTON')
      THISFORM.CMDGROUP.SETALL('FORECOLOR',RGB(0,0,0),'COMMANDBUTTON')
      THISFORM.SETALL('READONLY',.T.,'TEXTBOX')  
      THISFORM.PAGEFRAME1.PAGE1.SETALL('READONLY',.T.,'TEXTBOX')  
      THISFORM.PAGEFRAME1.PAGE2.SETALL('READONLY',.T.,'TEXTBOX')  
      THISFORM.PAGEFRAME1.PAGE1.TXTF06.READONLY=.T.
      THISFORM.PAGEFRAME1.PAGE1.TXTF09.READONLY=.T.  
      THISFORM.PAGEFRAME1.PAGE2.TXTF03.READONLY=.T.   
      THISFORM.PAGEFRAME1.PAGE2.TXTF07.READONLY=.T.    
      THISFORM.PAGEFRAME1.PAGE2.TXTF04.READONLY=.T.
      THISFORM.PAGEFRAME1.PAGE2.CRCY.VISIBLE=.F.
      THISFORM.PAGEFRAME1.PAGE1.ENABLED=.T.
      THISFORM.PAGEFRAME1.PAGE2.ENABLED=.T.
      IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1    
          THISFORM.GRID1.ENABLED=.T.
          THISFORM.GRID2.ENABLED=.T.
         THISFORM.GRID1.SETFOCUS   
         THISFORM.KEY_LIST.ENABLED=.T.
         THISFORM.MTH_LIST.ENABLED=.T.      
      ELSE
         THISFORM.GRID1.ENABLED=.F.
         THISFORM.GRID2.ENABLED=.T.
         THISFORM.GRID2.SETFOCUS
         IF THISFORM.GRID2.ACTIVEROW=0
            SELE A24         
            SET ORDER TO 1
            SEEK 'C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)+PO_NO
            IF !FOUND()
                APPEND BLANK
                LOCK()
                REPLACE  F01 WITH 'C007 '
                REPLACE  F02 WITH SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
	        REPLACE  F05 WITH 'CH'+F02
                REPLACE  F06 WITH '業務取消單'
                REPLACE  F08 WITH PO_NO
                UNLOCK
            ENDIF    
            SELE C08_1
            DELE
            THISFORM.PAGEFRAME1.ACTIVEPAGE=1
            THISFORM.REFRESH  
         ENDIF   
      ENDIF       
      UNLOCK ALL
      THISFORM.ANS_BOTT.ENABLED=IIF(C08_1.F10='2',.F.,.T.) .AND. IIF(A02.F11='*',.T.,.F.)  .AND. !THISFORM.SHRGROUP.ENABLED             
  ENDPROC
  PROCEDURE SHRGROUP.FINISH_BOTT.CLICK
      IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
         IF THISFORM.GRID2.RECORDSOURCE<>'C08'
            THISFORM.GRID2.RECORDSOURCE='C08'
            THISFORM.GRID2.CHILDORDER=C081
  	        THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C08.F03'
	        THISFORM.GRID2.COLUMN2.CONTROLSOURCE='B01.F02'
	        THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C08.F07'
	        THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C08.F04'
	        THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C08.F13'
	        THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C08.F12'
	        THISFORM.GRID2.COLUMN7.CONTROLSOURCE='C08.F11'         
	     ENDIF   
	     IF INT_099=.T.
                 SELE A24         
                 SET ORDER TO 1
                 SEEK 'C007 '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)+PO_NO                 
                 IF !FOUND()
                     APPEND BLANK
                     LOCK()
                     REPLACE  F01 WITH 'C007 '
                     REPLACE  F02 WITH SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
		     REPLACE  F05 WITH 'CH'+F02
                     REPLACE  F06 WITH '業務取消單'
                     REPLACE  F08 WITH PO_NO
                     UNLOCK
                  ENDIF   
             ENDIF   
         SELE C08_1
         DO CASE 
            CASE THISFORM.KEY_LIST.DISPLAYVALUE='依取消單號排列'
                 SET ORDER TO 1
            CASE THISFORM.KEY_LIST.DISPLAYVALUE='依客戶邊號排列'
                 SET ORDER TO 2
         ENDCASE   
       ENDIF  
       THISFORM.SHRGROUP.ABANDON_BOTT.CLICK
  ENDPROC     
  PROC ANS_BOTT.CLICK     &&過帳程序  
       &&C05(出貨計劃)->F04,F05
       &&C04(客戶訂單表身)->開單未出帳量(F23),已出貨量(F09),未出貨累積量(F10),計價已出量(F18),無價已出量(F19)
       &&C03(客戶訂單表頭)->是否已有出貨行為(F08)
       &&C01(客戶資料檔)->最後交易日(F16)
       &&C09(出貨紀錄)
       &&取消單號(F02),客戶編號(F03),訂單編號(F04),品號(F05),出貨數量(F06),單價(F07),小計(F08),結帳方式(F09),安全資料(F12),幣別(F13),匯率(F14),業務員編號(F19)
***       &&C14(月結暫存檔)->客戶編號(F01),科目(F02),借/貸(F03),金額(F06)
       &&B01(物料基本資料檔)->總庫存數量(F12),可分配量(F13)
       IF MESSAGEBOX('是否確認資料無誤可以取消?',4+32+256,'請確認') = 6	        
          THISFORM.PAGEFRAME1.PAGE1.PASS_CND.BACKCOLOR=RGB(255,255,0)    
          SELE RECNO() FROM C08 WHERE C08.F01=C08_1.F01  AND F10<>'2' INTO ARRAY BK1              
               JJ1=''                
               IF _TALLY>0   
                  FOR I= 1 TO ALEN(BK1)
                      JJ1=JJ1+ALLTRIM(STR(BK1(I)))+','
                  ENDFOR    
                  KK1=STUFF(JJ1,RAT(',',JJ1,1),1,'')              
                  RLOCK(KK1,'C08')
                  LL1=RLOCK(KK1,'C08')
               ELSE
                  LL1=.T.   
               ENDIF                   
               SELE RECNO() FROM C05 WHERE F01= ANY (SELE F07 FROM C08 WHERE F01=C08_1.F01) INTO ARRAY BK2
               JJ2=''                
               IF _TALLY>0                   
                  FOR I= 1 TO ALEN(BK2)
                      JJ2=JJ2+ALLTRIM(STR(BK2(I)))+','
                   ENDFOR  
                   KK2=STUFF(JJ2,RAT(',',JJ2,1),1,'')
                   RLOCK(KK2,'C05')
                   LL2=RLOCK(KK2,'C05')
               ELSE
                  LL2=.T.   
               ENDIF   
               SELE RECNO() FROM C04 WHERE F03+F04=ANY (SELE F07+F03 FROM C08 WHERE F01=C08_1.F01) INTO ARRAY BK3              
               JJ3=''                
               IF _TALLY>0   
                  FOR I= 1 TO ALEN(BK3)
                      JJ3=JJ3+ALLTRIM(STR(BK3(I)))+','
                  ENDFOR    
                  KK3=STUFF(JJ3,RAT(',',JJ3,1),1,'')              
                  RLOCK(KK3,'C04')
                  LL3=RLOCK(KK3,'C04')
               ELSE
                  LL3=.T.   
               ENDIF                   
               SELE RECNO() FROM C03 WHERE F02=ANY (SELE F07 FROM C08 WHERE F01=C08_1.F01) INTO ARRAY BK4
               JJ4=''
               IF _TALLY>0   
                  FOR I= 1 TO ALEN(BK4)
                      JJ4=JJ4+ALLTRIM(STR(BK4(I)))+','
                  ENDFOR    
                  KK4=STUFF(JJ4,RAT(',',JJ4,1),1,'')              
                  RLOCK(KK4,'C03')
                  LL4=RLOCK(KK4,'C03')
               ELSE
                  LL4=.T.   
               ENDIF     
               SELE RECNO() FROM C01 WHERE F01=C08_1.F06 INTO ARRAY BK5
               JJ5=''
               IF _TALLY>0   
                  FOR I= 1 TO ALEN(BK5)
                      JJ5=JJ5+ALLTRIM(STR(BK5(I)))+','
                  ENDFOR    
                  KK5=STUFF(JJ5,RAT(',',JJ5,1),1,'')              
                  RLOCK(KK5,'C01')
                  LL5=RLOCK(KK5,'C01')
               ELSE
                  LL5=.T.   
               ENDIF                   
               IF LL1 .AND. LL1 .AND. LL2 .AND. LL3 .AND. LL4 .AND. LL5=.T. 
                  IF LEN(ALLTRIM(JJ1))>0 
                     IF !USED('E08')
                        SELECT 0
                        USE E08
                     ELSE
                        SELECT E08
                     ENDIF
                     SET ORDER TO E083      
                     SELE C08
                     TQTY=0
                     FTTL=0
                     FOR I= 1 TO ALEN(BK1)                      
                         GO BK1(I) 
                         TQTY=TQTY+F17				&&小計
                         FTTL=FTTL+ROUND(F04*F15,2)	&&外幣金額小計
                         SELE C05                                            &&出貨計劃
                         SET ORDER TO C054                 
                         SEEK C08.F07+C08.F03
                         IF FOUND()
                            TPQTY=0
                            QTY=C08.F04+C08.F13
                            DO WHILE F01+F02=C08.F07+C08.F03 
                               DO CASE 
                                  CASE QTY=F05 
                                       SELE C05
                                       REPLACE  F04 WITH F04+F05*(-1)
                                       REPLACE  F05 WITH F05+QTY*(-1)                                   
                                       IF !EMPTY(ALLTRIM(F15))
                                          TPQTY=TPQTY+QTY
                                       ENDIF             
                                       IF F04=0
                                          DELETE 
                                       ENDIF                     
                                       EXIT
                                  CASE QTY>F05                                         
                                       SELE C05                              
                                       QTY=QTY+F05*(-1)  
                                       IF !EMPTY(ALLTRIM(F15))
                                          TPQTY=TPQTY+F05
                                       ENDIF
                                       DELETE      
                                       SKIP
                                  CASE QTY<F05
                                       SELECT  C05                               
                                       REPLACE  F04 WITH F04+QTY*(-1)
                                       REPLACE  F05 WITH F05+QTY*(-1)
                                       IF !EMPTY(ALLTRIM(F15))
                                          TPQTY=TPQTY+QTY
                                       ENDIF
                                       THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION='扣除出貨計劃(C)'
                                       EXIT
                               ENDCASE
                            ENDDO                                  
                         ENDIF            
                         IF TPQTY>0
                            SELECT E08
                            SEEK C08.F03
                            IF FOUND()
                               REPLACE F20 WITH F20+TPQTY                            
                            ELSE
                               APPEND BLANK
                               REPLACE F01 WITH CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/'+C08.F02)
                               REPLACE F02 WITH C08.F03
                               REPLACE F20 WITH F20+TPQTY
                            ENDIF          
                         ENDIF          
                         SELE C04           &&訂單表身
                         SEEK C08.F07+C08.F03
                         IF FOUND()
                             REPL F21 WITH F21+(C08.F04+C08.F13)
                             REPL F10 WITH F10+(C08.F04+C08.F13)*(-1)
                             REPL F23 WITH F23+(C08.F04+C08.F13)*(-1)
                             THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION='訂單表身狀態'        
                         ENDIF    
                         &&減去原始訂單總金額                  
*!*	                         SELECT C03
*!*	                         SEEK C08.F07
*!*	                         IF FOUND()
*!*	                            REPLACE F04 WITH F04+(C08.F04*C08.F15)*(-1)
*!*	                         ENDIF
                         SELE C09         &&出取消紀錄
                         APPEND BLANK
                         REPLACE F01 WITH C08.F07
                         REPLACE F02 WITH C08.F03
                         REPLACE F03 WITH CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/'+C08.F02)
                         REPLACE F04 WITH C08.F01
                         REPLACE F05 WITH C08.F04+C08.F13
                         REPLACE F06 WITH C08.F06
                         REPLACE F07 WITH IIF(SEEK (C08.F07,'C03'),C03.F14,'')
                         REPLACE F08 WITH C08.F12
                         REPLACE F09 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
                         THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION='出貨紀錄'                         
                         SELE C08
                         CHK_NAME=C08.F11
                         REPL F10 WITH '2'
                         REPL F90 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
                         THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION='取消單表身'                                                  
                    ENDFOR   
                    SELECT E08
                    USE
                    SELE C08_1
                    REPL F10 WITH '2'
                    REPL F90 WITH DTCX(DATE())+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
                    THISFORM.PAGEFRAME1.PAGE1.PASS_CND.CAPTION='完成取消程序'                                                                                             
                  ELSE
                     =MESSAGEBOX('此單據已由別的工作站過帳完成',0+64,'提示訊息視窗')
                     SELE C08_1
                     REPL F10 WITH '2'
                  ENDIF           
                  THIS.ENABLED=.F.
                  THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
                  THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.             
                  UNLOCK ALL
                  IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
                     THISFORM.GRID1.SETFOCUS
                  ELSE
                      THISFORM.GRID2.SETFOCUS
                      THISFORM.ORPGROUP.NEW_BOTT.ENABLED=.F.
                  ENDIF
                  THISFORM.REFRESH
               ELSE
                  DO FILE_IMPACT
                  UNLOCK ALL
                 RETURN
              ENDIF   
       ENDIF    
       UNLOCK ALL
       RELEASE ALL LIKE BK*       
  ENDPROC
ENDDEFINE        
***********************************************列印程序
PROCEDURE PNT_PRC       
     LK=C08_1.F01     
     SELE C08
     CALC SUM(F17) FOR F01=LK TO TMP1
     HK=IIF(INT_012=1,ALLTRIM(STR(YEAR(A23.F01)-1911))+SUBSTR(DTOC(A23.F01),3,3),LEFT(dtoc(A23.F01),5))
     SELECT C08.F01,;
            C08.F02,;
            C08.F03,;
            C08.F04,;
            C08.F06,;
            C08.F07,; 
            C08.F09,;
            C08.F12,;  
            C08.F13,;
            C08.F14,;
            C08.F15,;
            C08.F16,;
            C08.F17,;
            C08.F21,;
            C01.F04,;
            C01.F07,;
            C01.F08,;
            C01.F10,;
            C01.F12,;
            C01.F13,;
            C01.F24,;
            C03.F14,;
            C04.F17,;
            B01.F02,;
            B01.F04;            
     FROM C08,C01,C03,C04,B01 WHERE C08.F01=LK AND C01.F01=C08.F06 AND C03.F02=C08.F07 AND C04.F03=C08.F07 AND C04.F04=C08.F03;
     AND B01.F01=C08.F03 ORDER BY C08.F03 NOWAIT
     IF _TALLY >0
         IF MESSAGEBOX('選擇是將列印為 A5 格式,選擇否則將列印為 中一刀 格式?',4+32+0,'請選擇列印格式') = 6
	        REPORT FORM ALLTRIM(INT_116)+'C08A' TO PRINT PROMPT PREVIEW
	     ELSE   
             REPORT FORM ALLTRIM(INT_116)+'C08' TO PRINT PROMPT PREVIEW
         ENDIF    
     ENDIF  
ENDPROC
************************************************特殊輸入欄位的設定----料號
DEFINE CLASS TXTF03 AS TEXTBOX
  READONLY=.T.
  MAXLENGTH=43
  FONTSIZE=INT_015*9

  ****
  PROCEDURE INTERACTIVECHANGE
      CHK_IN='0'
      PR_NO='1'
      IF AT('?',ALLTRIM(THIS.VALUE))<>0
          DO CASE
                CASE AT('?',ALLTRIM(THIS.VALUE))>1 .AND. EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE))                   
                          SELECT F02,F01,F03,F04,F05,F09 FROM C05 WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE; 
                          AND LEFT(F02,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1);    
                          AND (C05.F04-C05.F05)>0 ORDER BY F02,F03 INTO CURSOR OQT 
                CASE AT('?',ALLTRIM(THIS.VALUE))>1 .AND. !EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE))                   
                           SELECT F02,F01,F03,F04,F05,F09 FROM C05 WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE; 
                           AND LEFT(F02,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1) AND (C05.F04-C05.F05)>0;    
                           AND F01=THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE ORDER BY F02,F03 INTO CURSOR OQT  
                CASE AT('?',ALLTRIM(THIS.VALUE))=1 .AND. EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE))                   
                           SELECT F02,F01,F03,F04,F05,F09 FROM C05  WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE;
                           AND (C05.F04-C05.F05)>0 ORDER BY F02,F03 INTO CURSOR OQT  
                CASE AT('?',ALLTRIM(THIS.VALUE))=1 .AND. !EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE))                   
                           SELECT F02,F01,F03,F04,F05,F09 FROM C05  WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE;
                           AND (C05.F04-C05.F05)>0 AND F01=THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE ORDER BY F02,F03 INTO CURSOR OQT  
          ENDCASE 
          IF _TALLY>0
             OQT_SEEK=createobject("OQT_SEEK")  
             OQT_SEEK.SHOW    
             IF LEN(ALLTRIM(FLG))>1
                THIS.VALUE=FLG
                THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=CHK_STR
                THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE=QTY                              
                FLG='0'           
                CHK_STR=''
                QTY=0    
             ENDIF             
             
          ELSE


                    =MESSAGEBOX('此客戶無出貨計劃可取消',0+48,'提示訊息視窗')
*!*	                   THIS.VALUE=''
*!*	                   THIS.REFRESH
                    THIS.SETFOCUS
                    RETURN   
                    THISFORM.SHRGROUP.ABANDON_BOTT.CLICK 
          ENDIF          

      ENDIF            
          THISFORM.PAGEFRAME1.PAGE2.LBLF031.CAPTION=IIF(SEEK(THIS.VALUE,'B01'),B01.F02,'')            
          IF !EMPTY(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE)
              THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE=IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THIS.VALUE,'C04'),C04.F06,INT_011)          
              THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE        
              THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE=IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE+THIS.VALUE,'C04'),C04.F07,0)                      
              THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE=IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE,'C00'),C00.F02,1)         
          ENDIF          
  ENDPROC
ENDDEFINE
***************************************************特殊欄位-----------------訂單號碼
DEFINE CLASS TXTF07 AS TEXTBOX
  READONLY=.T.
  MAXLENGTH=10
  FONTSIZE=INT_015*9

   **********        
  PROCEDURE INTERACTIVECHANGE
    PR_NO='2'
    IF AT('?',ALLTRIM(THIS.VALUE))<>0
       DO CASE
              CASE AT('?',ALLTRIM(THIS.VALUE))>1 .AND. EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE))                   
                        SELECT 0,F01,F02,F03,F04,F05,F09 FROM C05 INTO CURSOR OQT; 
                        ORDER BY F01,F03 WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE; 
                        AND LEFT(F01,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1);    
                        AND (C05.F04-C05.F05)>0 READWRITE 
             CASE AT('?',ALLTRIM(THIS.VALUE))>1 .AND. !EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE))                   
                        SELECT 0,F01,F02,F03,F04,F05,F09 FROM C05 INTO CURSOR OQT; 
                        ORDER BY F01,F03 WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE; 
                        AND LEFT(F01,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1);    
                        AND (C05.F04-C05.F05)>0 AND F02=THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE  READWRITE             
              CASE AT('?',ALLTRIM(THIS.VALUE))=1 .AND. EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE))                   
                        SELECT 0,F02,F01,F03,F04,F05,F09 FROM C05 INTO CURSOR OQT ORDER BY F01,F03 WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE;
                        AND (C05.F04-C05.F05)>0 READWRITE 
              CASE AT('?',ALLTRIM(THIS.VALUE))=1 .AND. !EMPTY(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE))                   
                        SELECT 0,F02,F01,F03,F04,F05,F09 FROM C05 INTO CURSOR OQT ORDER BY F01,F03 WHERE F06=THISFORM.PAGEFRAME1.PAGE1.TXTF06.VALUE;
                       AND (C05.F04-C05.F05)>0 AND F02=THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE READWRITE          
        ENDCASE 
        IF _TALLY>0  
           OQT_SEEK=CREATEOBJECT("OQT_SEEK")  
           OQT_SEEK.SHOW    
                THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE=FLG
                THIS.VALUE=CHK_STR
                THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE=QTY                              
                FLG='0'           
                CHK_STR=''
                QTY=0               
           THIS.REFRESH
        ELSE    	
  	       =MESSAGEBOX('此客戶已無出貨計畫可取消!',0+48,'提示訊息視窗')
	       THISFORM.PAGEFRAME1.PAGE2.TXTF07.SETFOCUS 
           RETURN
           THISFORM.SHRGROUP.ABANDON_BOTT.CLICK            
        ENDIF            
    ENDIF 
        THISFORM.PAGEFRAME1.PAGE2.LBLF031.CAPTION=IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'B01'),B01.F02,'')          
        IF !EMPTY(THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE)    
            THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE=IIF(SEEK(THIS.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F06,INT_011)          
            THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE        
            THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE=IIF(SEEK(THIS.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF03.VALUE,'C04'),C04.F07,0)                      
            THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE=IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE,'C00'),C00.F02,1)          
        ENDIF   
  ENDPROC     
ENDDEFINE 
***************************************************特殊輸入欄位設定-----------客戶
DEFINE CLASS TXTF06 AS TEXTBOX
  READONLY=.T.
  MAXLENGTH=5
  FONTSIZE=INT_015*9       
  PROCEDURE INTERACTIVECHANGE
    IF AT('?',ALLTRIM(THIS.VALUE))<>0 
       IF AT('?',ALLTRIM(THIS.VALUE))>1             
          IF EMPTY(A02.F12)
             SELECT F02,F01,F04 FROM C01 INTO CURSOR VDR ORDER BY F02 WHERE LEFT(F02,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1) AND F33=SYS_OPER
          ELSE
             SELECT F02,F01,F04 FROM C01 INTO CURSOR VDR ORDER BY F02 WHERE LEFT(F02,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1)
          ENDIF
       ELSE
          SELECT F02,F01,F04 FROM C01 INTO CURSOR VDR ORDER BY F02 
       ENDIF
       IF _TALLY>0          
          VDR_SEEK=CREATEOBJECT("VDR_SEEK")  
          VDR_SEEK.SHOW    
          THIS.VALUE=FLG
          THIS.REFRESH
          FLG='0'        
       ENDIF   
    ELSE
       IF LEN(ALLTRIM(THIS.VALUE))=4
          SELECT F02,F01,F04 FROM C01 INTO CURSOR VDR ORDER BY F02 WHERE F02=ALLTRIM(THIS.VALUE)
          DO CASE
             CASE _TALLY=1
                  THIS.VALUE=VDR.F01
                  THIS.REFRESH
             CASE _TALLY>1
                  VDR_SEEK=CREATEOBJECT("VDR_SEEK")  
                  VDR_SEEK.SHOW    
                  THIS.VALUE=FLG
                  THIS.REFRESH
                  FLG='0'        
          ENDCASE      
       ENDIF    
    ENDIF      
       THISFORM.PAGEFRAME1.PAGE1.LBLF061.CAPTION=IIF(SEEK(THIS.VALUE,'C01'),C01.F04,'')  
       THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE=IIF(SEEK(THIS.VALUE,'C01'),C01.F33,'')
       THISFORM.PAGEFRAME1.PAGE1.LBLF091.CAPTION=IIF(SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF09.VALUE,'A01'),A01.F03,'')
  ENDPROC
ENDDEFINE
***************************************************特殊輸入欄位設定-----------業務人員
DEFINE CLASS TXTF09 AS TEXTBOX
   READONLY=.T.
   MAXLENGTH=5
   FONTSIZE=INT_015*9      
   PROCEDURE INTERACTIVECHANGE
     IF AT('?',ALLTRIM(THIS.VALUE))<>0
        IF AT('?',ALLTRIM(THIS.VALUE))>1             
           SELECT F01,F03 FROM A01 INTO CURSOR MAN ORDER BY F01 WHERE LEFT(F01,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1)
        ELSE
           SELECT F01,F03 FROM A01 INTO CURSOR MAN ORDER BY F01    
        ENDIF   
        IF _TALLY>0
           MAN_SEEK=CREATEOBJECT("MAN_SEEK")  
           MAN_SEEK.SHOW    
           THIS.VALUE=FLG
           THIS.REFRESH
           FLG='0'        
        ENDIF   
     ENDIF  
      THISFORM.PAGEFRAME1.PAGE1.LBLF091.CAPTION=IIF(SEEK(THIS.VALUE,'A01'),A01.F03,'')  
  ENDPROC
ENDDEFINE

***************************************************幣別設定
DEFINE CLASS CRCY AS COMBOBOX
  HEIGHT=INT_015*25
  AUTOSIZE=.T.
  TOP=INT_015*39
  LEFT=INT_015*379
  BOUNDCOLUMN=1
  COLUMNCOUNT=1
  WIDTH=INT_015*84
  FONTSIZE=INT_015*9
  ROWSOURCETYPE=1
  STYLE=2
  NAME='CRCY'
  PROCEDURE INIT
    SELECT C00
    GO TOP 
    DO WHILE .NOT. EOF()
       L=4-LEN(ALLTRIM(F01))
       THIS.ADDITEM(F01)
       SKIP
    ENDDO
  ENDPROC
  PROCEDURE INTERACTIVECHANGE
    THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=THIS.DISPLAYVALUE
    THISFORM.PAGEFRAME1.PAGE2.TXTF16.VALUE=IIF(SEEK(THIS.DISPLAYVALUE,'C00'),C00.F02,1)
    THISFORM.PAGEFRAME1.PAGE2.TXTF14.REFRESH
    THISFORM.PAGEFRAME1.PAGE2.TXTF16.REFRESH
  ENDPROC
ENDDEFINE         
***************************************出貨計劃
DEFINE CLASS OQT_SEEK AS FORM
*!*	  AUTOCENTER=.T.
  CAPTION=ALLTRIM(C01.F04)+'         C05.出貨計劃'
  TOP=INT_015*110
  LEFT=INT_015*125    
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*325
  WIDTH=INT_015*560
  FONTSIZE=INT_015*9
  MAXBUTTON=.F.
  MINBUTTON=.F.    
  CLOSABLE=.F.
  CONTROLBOX=.F.
  BORDERSTYLE=2
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WINDOWTYPE=1
  NAME='OQT_SEEK'
  ADD OBJECT GRID1 AS GRID WITH;          
      AUTOCENTER=.T.,;
      HIGHLIGHTROWLINEWIDTH=4,;
      WIDTH=INT_015*745,;      
      HEIGHT=INT_015*293,;      
      ROWHEIGHT=INT_015*18,;
      HEADERHEIGHT=INT_015*19,;
      DELETEMARK=.F.,;
      READONLY=.T.,;
      RECORDSOURCETYPE=1,;
      COLUMNCOUNT=5,;       
      RECORDSOURCE='OQT',;     
      NAME='GRID1',;
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2',;      
      COLUMN3.NAME='COLUMN3',;      
      COLUMN4.NAME='COLUMN4',;            
      COLUMN5.NAME='COLUMN5'
  ADD OBJECT CMND1 AS COMMANDBUTTON WITH;
      AUTOSIZE=.T.,;
      LEFT=INT_015*230,;    
      HEIGHT=INT_015*25,;   
      TOP=INT_015*297,;        
      WIDTH=INT_015*80,;    
      FONTSIZE=INT_015*9,;
      CAPTION='\<S.確定',;
      TOOLTIPTEXT='選擇游標所指的紀錄!快速鍵->ALT+S'
      NAME='CMND1'
  ADD OBJECT CMND2 AS COMMANDBUTTON WITH;
      AUTOSIZE=.T.,;
      LEFT=INT_015*320,;
      TOP=INT_015*297,;
      HEIGHT=INT_015*25,;
      WIDTH=INT_015*80,;    
      FONTSIZE=INT_015*9,;      
      CAPTION='\<X.取消',;
      TOOLTIPTEXT='取消此搜尋畫面!快速鍵->ALT+X'
      NAME='CMND2'
   PROCEDURE INIT 
         AREA1='OQT'
         SELE &AREA1
         GO TOP
         THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'COLUMN')
         THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'HEADER')   
         THISFORM.SETALL('MOVABLE',.F.,'COLUMN') 
         THISFORM.SETALL('MOUSEPOINTER',99,'COMMANDBUTTON')
         THISFORM.SETALL('MOUSEICON','BMPS\harrow.cur','COMMANDBUTTON')                           
         THISFORM.SETALL('READONLY',.T.,'TEXTBOX')
         THISFORM.GRID1.COLUMN1.HEADER1.CAPTION=''
         THISFORM.GRID1.COLUMN1.WIDTH=INT_015*20
         IF PR_NO='1'  
             THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='料        號'
             THISFORM.GRID1.COLUMN1.WIDTH=INT_015*180
             THISFORM.GRID1.COLUMN1.CONTROLSOURCE='OQT.F02'               
             THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='訂單號碼'
             THISFORM.GRID1.COLUMN2.CONTROLSOURCE='OQT.F01'
             THISFORM.GRID1.COLUMN2.WIDTH=INT_015*80      
         ELSE
             THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='訂單號碼'
             THISFORM.GRID1.COLUMN1.CONTROLSOURCE='OQT.F01'
             THISFORM.GRID1.COLUMN1.WIDTH=INT_015*80
             THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='料        號'
             THISFORM.GRID1.COLUMN2.WIDTH=INT_015*180
             THISFORM.GRID1.COLUMN2.CONTROLSOURCE='OQT.F02'        
         ENDIF
         THISFORM.GRID1.COLUMN3.HEADER1.CAPTION='出貨日期'
         THISFORM.GRID1.COLUMN3.CONTROLSOURCE='OQT.F03'
         THISFORM.GRID1.COLUMN3.WIDTH=INT_015*65
         THISFORM.GRID1.COLUMN4.HEADER1.CAPTION='出貨數量'         
         THISFORM.GRID1.COLUMN4.CONTROLSOURCE='OQT.F04-OQT.F05'
         THISFORM.GRID1.COLUMN4.WIDTH=INT_015*80       
         THISFORM.GRID1.COLUMN5.HEADER1.CAPTION='客戶單號'         
         THISFORM.GRID1.COLUMN5.CONTROLSOURCE='OQT.F09'
         THISFORM.GRID1.COLUMN5.WIDTH=INT_015*120                  
         THISFORM.GRID1.SETFOCUS
      ENDPROC
      ***

      ***
      PROC GRID1.AFTERROWCOLCHANGE
           LPARAMETERS XCOLINDEX
	           FCH='GRID1'
      ENDPROC 
 PROCEDURE CMND1.CLICK
           FLG=OQT.F02
           CHK_STR=OQT.F01           
           QTY=OQT.F04-OQT.F05 
           THISFORM.CMND2.CLICK   
 ENDPROC
 PROCEDURE CMND2.CLICK 
      AREA1='C08_1'
      SELECT OQT
      USE
      THISFORM.RELEASE
 ENDPROC  
 **

ENDDEFINE 
*********     

*********     

*******************************************   計算該單出貨總金額
FUNC TTL1
     PARA BKK_NO
     qt_od=0
     sele C08
     SEEK BKK_NO
     IF FOUND()
         DO WHILE F01=BKK_NO            
                          
                  qt_od=qt_od+f17
                                                    
                SKIP
          ENDDO
     ELSE
       qt_od=0
     ENDIF
     SELE C08_1
     RETURN ROUND(qt_od,INT_069)
