***程式名稱:C12應收帳款對帳單
CLOSE ALL
CLEAR 
FLG='0'
FCH=''
CHK=''
CHK_STR=''
FILTER_KEY=''
FTR_STR='2'
R=0
QTY=0
TQTY=0
PO_NO=''
AREA1='C13_1'
AREA2='C13'
IF !USED('A23')
    SELE 0
    USE A23
ELSE 
   SELE A23
ENDIF
SET ORDER TO 1         
IF !USED('C00')                  &&幣別檔
   SELE 0
   USE C00
ELSE
   SELE C00
ENDIF
SET ORDER TO 1      
IF ! USED('A01')
   SELE 0
   USE A01 INDE A01
ELSE
   SELE A01
ENDIF      
SET ORDER TO A01
IF !USED('A02')
   SELE 0
   USE A02 INDE A02
ELSE
   SELE A02
ENDIF
SET ORDER TO A021      
SEEK SYS_OPER+'C12'    
IF !USED('B0A')
   SELE 0
   USE B0A 
ELSE
   SELE B0A
ENDIF
SET ORDER TO B0A2        
SET FILTER TO LEFT(DTOS(F03),6)<=LEFT(DTOS(DATE()),6)
IF !USED('B01')
   SELE 0
   USE B01 INDE B01
ELSE
   SELE B01
ENDIF
SET ORDER TO 1           
IF !USED('C01')
   SELE 0
   USE C01 INDE C01
ELSE
   SELE C01
ENDIF
SET ORDER TO C011
B04='B04'+LEFT(DTOS(DATE()),6)
B041='B041'+LEFT(DTOS(DATE()),6)
IF !USED('&B04')
   SELE 0
   USE (B04) ALIA B04
ELSE
   SELE B04
ENDIF
SET ORDER TO 1      
B05='B05'+LEFT(DTOS(DATE()),6)
B051='B051'+LEFT(DTOS(DATE()),6)
IF !USED('&B05')
   SELE 0
   USE (B05) ALIA B05
ELSE
   SELE B05
ENDIF
SET ORDER TO 1      
C10='C10'+LEFT(DTOS(DATE()),6)
C105='C105'+LEFT(DTOS(DATE()),6)
IF !USED('&C10')
   SELE 0
   USE (C10) ALIA C10
ELSE
   SELE C10
ENDIF
SET ORDER TO 5      
C13='C13'+LEFT(DTOS(DATE()),6)
C131='C131'+LEFT(DTOS(DATE()),6)
IF !USED('&C13')
   SELE 0
   USE (C13) ALIA C13
ELSE
   SELE C13
ENDIF
SET ORDER TO C131    
SET RELA TO F03 INTO B01
SET RELA TO F19 INTO A01 ADDI
CREATE CURSOR C13_1;
(F03 C(5),F10 C(8),F06 N(13,2),F07 N(13,2),F08 N(13,2),F09 N(13,2),FTR C(10),F11 N(13,2))
INDE ON F03 TAG C13_11
INDE ON F10+F03 TAG C13_12
SELE F03,F10 FROM C13 GROUP BY F03 ORDER BY C13.F03 INTO CURSOR C13_2
SELE C13_2
GO TOP
DO WHILE !EOF()
   SELE C13_1
   APPEND BLANK
   REPLACE  F03 WITH C13_2.F03
   REPLACE  F10 WITH IIF(SEEK(C13_2.F03,'C01'),C01.F10,'')   
   REPLACE  F06 WITH TTL1(C13_1.F03)
   REPLACE  F07 WITH TTL2(C13_1.F03)
   REPLACE  F08 WITH TTL3_1(C13_1.F03)
   REPLACE  F09 WITH TTL4(C13_1.F03)  
   REPLACE FTR WITH C13_2.F10   
   REPLACE F11 WITH TTL3_2(C13_1.F03)
   SELE C13_2
   SKIP   
ENDDO
SELE C13_2
USE   
SELE C13_1
SET ORDER TO  C13_11 
SET RELA TO F03 INTO C01
C12FORM=CREATEOBJECT("TKC12")
C12FORM.SHOW  
DEFINE CLASS TKC12 AS FORM
  CAPTION='C12.應收帳款對帳單'
*!*	  AUTOCENTER=.T.
  CONTROLBOX=.F.
  BORDERSTYLE=1  
  MAXBUTTON=.F.
  MINBUTTON=.F.
  MOVABLE=.F.
  CLOSABLE=.F.
  CONTROLCOUNT=57
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*550
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WIDTH=INT_015*789
  WINDOWTYPE=1
  NAME='TKC12'
  ADD OBJECT SHAPE1 AS SHAPE1 WITH;
      AUTOCENTER=.T.
  ADD OBJECT LBL_REC AS LBL_REC WITH;
      AUTOCENTER =.T.
  ADD OBJECT REC_COUNT AS REC_COUNT  WITH;
      CAPTION=STR(RECCOUNT())        
  ADD OBJECT SHAPE2 AS SHAPE2 WITH;
      AUTOCENTER=.T.
  ADD OBJECT SHAPE3 AS SHAPE3 WITH;
      AUTOCENTER=.T.
  ADD OBJECT PAGEFRAME1 AS PAGEFRAME WITH;
      LEFT=INT_015*236,;
      WIDTH=INT_015*540,;
      HEIGHT=INT_015*200,;
      FONTSIZE=INT_015*9,;
      PAGECOUNT=2,;
      TABSTRETCH=1,;
      ACTIVEPAGE=1,;
      VISIBLE=.T.,;
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;               
      PAGE1.NAME='PAGE1',;
      PAGE1.VISIBLE=.T.,;
      PAGE1.CAPTION='表頭資料',;
      PAGE2.NAME='PAGE2',;
      PAGE2.VISIBLE=.T.,;
      PAGE2.CAPTION='表身詳細資料內容'   
  ADD OBJECT KEY_LIST AS KEY_LIST WITH;
      AUTOCENTER=.T.,;
      WIDTH=INT_015*130
  ADD OBJECT MTH_LIST AS MTH_LIST WITH;
      AUTOCENTER=.T.
  ADD OBJECT GRID1 AS GRID1 WITH;
      COLUMNCOUNT=2,;            
      RECORDSOURCE='C13_1',;      
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2'      
  ADD OBJECT GRID2 AS GRID2 WITH;
      COLUMNCOUNT=6,;            
      RECORDSOURCE='C13',; 
      LINKMASTER='C13_1',;
      RELATIONALEXPR='F03',;
      CHILDORDER=C131,;  
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2',;
      COLUMN3.NAME='COLUMN3',;
      COLUMN4.NAME='COLUMN4',;
      COLUMN5.NAME='COLUMN5',;
      COLUMN6.NAME='COLUMN6'
  ADD OBJECT CMDGROUP AS CMDGROUP WITH;
      AUTOSIZE=.T.                             
  ADD OBJECT ORPGROUP AS ORPGROUP WITH;    
      AUTOSIZE=.T.               
  ADD OBJECT SHRGROUP AS SHRGROUP WITH;
      TOP=INT_015*173,;
      LEFT=INT_015*558          
  ADD OBJECT ANS_BOTT AS COMMANDBUTTON WITH;
      TOP=INT_015*490,;
      LEFT=INT_015*15,;
      HEIGHT=INT_015*25,;
      FONTSIZE=INT_015*9,;
      WIDTH=INT_015*70,;     
      CAPTION='\<A.帳款總表',;
      NAME='ANS_BOTT' 
  ADD OBJECT ACC_BOTT AS COMMANDBUTTON WITH;
      TOP=INT_015*490,;
      LEFT=INT_015*86,;
      HEIGHT=INT_015*25,;
      FONTSIZE=INT_015*9,;
     WIDTH=INT_015*70,;
      CAPTION='\<T.結轉傳票',;
      NAME='ACC_BOTT'                             
  ADD OBJECT ACD_BOTT AS COMMANDBUTTON WITH;
      TOP=INT_015*490,;
      LEFT=INT_015*86,;
      HEIGHT=INT_015*25,;
      FONTSIZE=INT_015*9,;
      WIDTH=INT_015*70,;
      CAPTION='\<C.刪除傳票',;
      NAME='ACD_BOTT'                             
  PROCEDURE PAGEFRAME1.PAGE1.INIT     
     THIS.ADDOBJECT('LBLF03','LABEL')
     WITH THIS.LBLF03
          .VISIBLE=.T.
          .LEFT=INT_015*14
          .TOP=INT_015*13
          .WIDTH=INT_015*50
          .CAPTION='客戶編號'          
     ENDWITH
     THIS.ADDOBJECT('LBLF04','LABEL')
     WITH THIS.LBLF04
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*38
         .WIDTH=INT_015*50
         .CAPTION='客戶名稱'
     ENDWITH
     THIS.ADDOBJECT('LBLF041','LABEL')
     WITH THIS.LBLF041
         .VISIBLE=.T.
         .LEFT=INT_015*65
         .TOP=INT_015*38
         .AUTOSIZE=.T.
     ENDWITH     
     THIS.ADDOBJECT('LBLTTL1','LABEL')
     WITH THIS.LBLTTL1
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*63
         .WIDTH=INT_015*50
         .CAPTION='出貨金額'
         .ALIGNMENT=2         
     ENDWITH    
     THIS.ADDOBJECT('LBLTTL11','LABEL')
     WITH THIS.LBLTTL11
         .VISIBLE=.T.
         .LEFT=INT_015*65
         .TOP=INT_015*63
         .WIDTH=INT_015*100
         .ALIGNMENT=2         
     ENDWITH               
     THIS.ADDOBJECT('LBLTTL2','LABEL')
     WITH THIS.LBLTTL2
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*88
         .WIDTH=INT_015*50
         .CAPTION='退貨金額'
     ENDWITH    
     THIS.ADDOBJECT('LBLTTL21','LABEL')
     WITH THIS.LBLTTL21
         .VISIBLE=.T.
         .LEFT=INT_015*65
         .TOP=INT_015*88
         .WIDTH=INT_015*100
         .ALIGNMENT=2         
     ENDWITH                    
     THIS.ADDOBJECT('LBLTTL4','LABEL')
     WITH THIS.LBLTTL4
         .VISIBLE=.T.
         .LEFT=INT_015*214
         .TOP=INT_015*82
         .WIDTH=INT_015*50
         .CAPTION='折讓金額'
     ENDWITH    
     THIS.ADDOBJECT('LBLTTL41','LABEL')
     WITH THIS.LBLTTL41
         .VISIBLE=.T.
         .LEFT=INT_015*265
         .TOP=INT_015*82
         .WIDTH=INT_015*100
         .ALIGNMENT=2         
     ENDWITH                                   
     THIS.ADDOBJECT('LBLTTL3','LABEL')
     WITH THIS.LBLTTL3
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*113
         .WIDTH=INT_015*50
         .CAPTION='稅        額'
     ENDWITH    
     THIS.ADDOBJECT('LBLTTL31','LABEL')
     WITH THIS.LBLTTL31
         .VISIBLE=.T.
         .LEFT=INT_015*65
         .TOP=INT_015*113
         .WIDTH=INT_015*100
         .ALIGNMENT=2         
     ENDWITH                         
     THIS.ADDOBJECT('LBLTTL5','LABEL')
     WITH THIS.LBLTTL5
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*138
         .WIDTH=INT_015*50
         .CAPTION='總        額'
     ENDWITH    
     THIS.ADDOBJECT('LBLTTL51','LABEL')
     WITH THIS.LBLTTL51
         .VISIBLE=.T.
         .LEFT=INT_015*65
         .TOP=INT_015*138
         .WIDTH=INT_015*100
         .ALIGNMENT=2
     ENDWITH                              
     THIS.ADDOBJECT('LBLTRN','LABEL')
     WITH THIS.LBLTRN
         .VISIBLE=.T.
         .LEFT=INT_015*414
         .TOP=INT_015*163
         .WIDTH=INT_015*50
         .CAPTION='傳票號碼'
     ENDWITH    
     THIS.ADDOBJECT('LBLTRN1','LABEL')
     WITH THIS.LBLTRN1
         .VISIBLE=.T.
         .LEFT=INT_015*465
         .TOP=INT_015*163
         .AUTOSIZE=.T.
     ENDWITH                               
     THIS.ADDOBJECT('TXTF03','TXTF03')          
     WITH THIS.TXTF03
          .VISIBLE=.T.
          .LEFT=INT_015*64
          .TOP=INT_015*9
          .WIDTH=INT_015*50
          .HEIGHT=INT_015*25
          .MAXLENGTH=5
     ENDWITH        
  ENDPROC   
  PROCEDURE PAGEFRAME1.PAGE2.INIT
	THIS.ADDOBJECT('LBLF01','LABEL')
	WITH THIS.LBLF01  
	     .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*7
	     .WIDTH=INT_015*50
         .CAPTION='出貨日期'
    ENDWITH  
    THIS.ADDOBJECT('LBLF04','LABEL')
    WITH THIS.LBLF04
         .VISIBLE=.T.
         .LEFT=INT_015*14
	     .TOP=INT_015*32
	     .WIDTH=INT_015*50
	     .CAPTION='訂單編號'
	ENDWITH     
    THIS.ADDOBJECT('LBLF05','LABEL')
    WITH THIS.LBLF05
         .VISIBLE=.T.
	     .LEFT=INT_015*14
	     .TOP=INT_015*57
	     .WIDTH=INT_015*50
	     .CAPTION='料       號'
	ENDWITH     
    THIS.ADDOBJECT('LBLF06','LABEL')
    WITH THIS.LBLF06
         .VISIBLE=.T.
         .LEFT=INT_015*14
         .TOP=INT_015*82
         .WIDTH=INT_015*50
         .CAPTION='出貨數量'         
    ENDWITH     
    THIS.ADDOBJECT('LBLF02','LABEL')
    WITH THIS.LBLF02
         .VISIBLE=.T.    
         .LEFT=INT_015*14
         .TOP=INT_015*107
         .WIDTH=INT_015*50
         .CAPTION='出貨單號'       
    ENDWITH    
    THIS.ADDOBJECT('LBLTU','LABEL')
    WITH THIS.LBLTU
         .VISIBLE=.T.           
         .LEFT=INT_015*146
         .TOP=INT_015*107
         .WIDTH=INT_015*45
         .CAPTION=''
    ENDWITH              
    THIS.ADDOBJECT('LBLF15','LABEL')
    WITH THIS.LBLF15
         .VISIBLE=.T.    
         .LEFT=INT_015*14
         .TOP=INT_015*132
         .WIDTH=INT_015*50
         .CAPTION='備註說明'       
    ENDWITH        
    THIS.ADDOBJECT('LBLF17','LABEL')
    WITH THIS.LBLF17
         .VISIBLE=.T.    
         .LEFT=INT_015*14
         .TOP=INT_015*157
         .WIDTH=INT_015*50
         .CAPTION='發票號碼'       
    ENDWITH            
    THIS.ADDOBJECT('LBLF19','LABEL')
    WITH THIS.LBLF19
         .VISIBLE=.T.    
         .LEFT=INT_015*328
         .TOP=INT_015*7
         .WIDTH=INT_015*50
         .CAPTION='業務人員'       
    ENDWITH        
    THIS.ADDOBJECT('LBLF191','LABEL')
    WITH THIS.LBLF191
         .VISIBLE=.T.    
         .LEFT=INT_015*430
         .TOP=INT_015*7
         .AUTOSIZE=.T.
    ENDWITH                
    THIS.ADDOBJECT('LBLF13','LABEL')    
    WITH THIS.LBLF13
         .VISIBLE=.T.           
         .LEFT=INT_015*328
         .TOP=INT_015*32
         .WIDTH=INT_015*50
         .CAPTION='幣        別'
    ENDWITH     
    THIS.ADDOBJECT('LBLF14','LABEL')    
    WITH THIS.LBLF14
         .VISIBLE=.T.           
         .LEFT=INT_015*328
         .TOP=INT_015*57
         .WIDTH=INT_015*50
         .CAPTION='匯        率'
    ENDWITH         
    THIS.ADDOBJECT('LBLF07','LABEL')      
    WITH THIS.LBLF07
         .VISIBLE=.T.       
         .LEFT=INT_015*328
         .TOP=INT_015*82
         .WIDTH=INT_015*50
         .CAPTION='單        價'
    ENDWITH     
    THIS.ADDOBJECT('LBLF08','LABEL')
    WITH THIS.LBLF08
         .VISIBLE=.T.           
         .LEFT=INT_015*316
         .TOP=INT_015*107
         .WIDTH=INT_015*149
         .CAPTION=IIF(SEEK(INT_011,'C00'),ALLTRIM(C00.F04)+'小計',INT_011+'小計')         
    ENDWITH  
    THIS.ADDOBJECT('LBLF081','LABEL')    
    WITH THIS.LBLF081
         .VISIBLE=.T.           
         .LEFT=INT_015*379
         .TOP=INT_015*107
         .WIDTH=INT_015*100
         .ALIGNMENT=2
    ENDWITH         
    THIS.ADDOBJECT('LBLTS','LABEL')
    WITH THIS.LBLTS
         .VISIBLE=.T.           
         .LEFT=INT_015*480
         .TOP=INT_015*82
         .WIDTH=INT_015*45
         .CAPTION=''
    ENDWITH          
    THIS.ADDOBJECT('LBLF12','LABEL')
    WITH THIS.LBLF12
        .VISIBLE=.T.           
        .LEFT=INT_015*328
        .TOP=INT_015*156
        .WIDTH=INT_015*50
        .CAPTION='安全資料'         
    ENDWITH    
    THIS.ADDOBJECT('LBLF121','LABEL')
    WITH THIS.LBLF121
        .VISIBLE=.T.           
        .LEFT=INT_015*380
        .TOP=INT_015*156
        .AUTOSIZE=.T.
    ENDWITH    

	THIS.ADDOBJECT('TXTF01','TEXTBOX')
	WITH THIS.TXTF01      
	     .VISIBLE=.T.
	     .LEFT=INT_015*65
	     .TOP=INT_015*3
	     .WIDTH=INT_015*70
	     .HEIGHT=INT_015*25
	     .NAME='TXTF01'  
	ENDWITH     
	THIS.ADDOBJECT('TXTF04','TEXTBOX')
	WITH THIS.TXTF04      
	     .VISIBLE=.T.
	     .LEFT=INT_015*65
	     .TOP=INT_015*28
	     .WIDTH=INT_015*80
	     .HEIGHT=INT_015*25
	     .MAXLENGTH=10
	     .NAME='TXTF04'  
	ENDWITH     
	THIS.ADDOBJECT('TXTF05','TXTF05')
	WITH THIS.TXTF05
	     .VISIBLE=.T.
	     .LEFT=INT_015*65
	     .TOP=INT_015*53
	     .WIDTH=INT_015*261
	     .HEIGHT=INT_015*25
	     .MAXLENGTH=43
	     .NAME='TXTF05'	    
	ENDWITH     
    THIS.ADDOBJECT('TXTF06','TEXTBOX')
    WITH THIS.TXTF06
         .VISIBLE=.T.           
         .LEFT=INT_015*65
         .TOP=INT_015*78
         .WIDTH=INT_015*100
         .HEIGHT=INT_015*25
         .INPUTMASK='999999999999'
         .NAME='TXTF06'
    ENDWITH     
    THIS.ADDOBJECT('TXTF02','TEXTBOX')
    WITH THIS.TXTF02
         .VISIBLE=.T.           
         .LEFT=INT_015*65
         .TOP=INT_015*103
         .WIDTH=INT_015*80
         .HEIGHT=INT_015*25
         .MAXLENGTH=10
         .NAME='TXTF02'
    ENDWITH         
    THIS.ADDOBJECT('TXTF15','TEXTBOX')
    WITH THIS.TXTF15
         .VISIBLE=.T.           
         .LEFT=INT_015*65
         .TOP=INT_015*128
         .WIDTH=INT_015*470
         .HEIGHT=INT_015*25
         .MAXLENGTH=100
         .NAME='TXTF15'
    ENDWITH             
    THIS.ADDOBJECT('TXTF17','TEXTBOX')
    WITH THIS.TXTF17
         .VISIBLE=.T.           
         .LEFT=INT_015*65
         .TOP=INT_015*153
         .WIDTH=INT_015*80
         .HEIGHT=INT_015*25
         .MAXLENGTH=10
         .NAME='TXTF17'
    ENDWITH                 
    THIS.ADDOBJECT('TXTF19','TXTF19')
    WITH THIS.TXTF19
         .VISIBLE=.T.           
         .LEFT=INT_015*379
         .TOP=INT_015*3
         .WIDTH=INT_015*50
         .HEIGHT=INT_015*25
         .MAXLENGTH=5
         .NAME='TXTF19'
    ENDWITH             
    THIS.ADDOBJECT('TXTF13','TEXTBOX')
    WITH THIS.TXTF13
         .VISIBLE=.T.           
         .LEFT=INT_015*379
         .TOP=INT_015*28
         .WIDTH=INT_015*49         
         .HEIGHT=INT_015*25
         .MAXLENGTH=4
         .NAME='TXTF13'                            
    ENDWITH         
    THIS.ADDOBJECT('CRCY','CRCY')
    THIS.ADDOBJECT('TXTF14','TEXTBOX')
    WITH THIS.TXTF14
         .VISIBLE=.T.           
         .LEFT=INT_015*379
         .TOP=INT_015*53
         .WIDTH=INT_015*100
         .HEIGHT=INT_015*25
         .INPUTMASK='9999.999999'
         .NAME='TXTF14'                            
    ENDWITH     
    
    THIS.ADDOBJECT('TXTF07','TEXTBOX')
    WITH THIS.TXTF07
         .VISIBLE=.T.           
         .LEFT=INT_015*379 
         .TOP=INT_015*78
         .WIDTH=INT_015*100
         .HEIGHT=INT_015*25
         .INPUTMASK='9999999.999999'
         .NAME='TXTF07'                            
    ENDWITH     
  ENDPROC       
  PROCEDURE PAGEFRAME1.PAGE1.ACTIVATE
     R=0
     SELECT  C13_1
     IF THISFORM.SHRGROUP.VISIBLE=.F.
        THISFORM.GRID1.ENABLED=.T.   
        THISFORM.GRID1.SETFOCUS 
        THISFORM.KEY_LIST.ENABLED=.T.
        THISFORM.MTH_LIST.ENABLED=.T.
     ELSE
       THISFORM.KEY_LIST.ENABLED=.F.   
       THISFORM.MTH_LIST.ENABLED=.F.   
     ENDIF                 
    IF THISFORM.GRID1.ACTIVEROW=0 .AND. THISFORM.SHRGROUP.ENABLED=.F.
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.F.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
        THISFORM.ANS_BOTT.ENABLED=.F.
        THISFORM.ACC_BOTT.ENABLED=.F.                
        THISFORM.ACD_BOTT.ENABLED=.F.                        
        THISFORM.PAGEFRAME1.PAGE1.SETALL('VALUE','','TEXTBOX')        
        THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE=''        
        THISFORM.PAGEFRAME1.PAGE1.LBLF041.CAPTION=''     
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL11.CAPTION=TRANSFORM(0,'@J 999,999,999,999')
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL21.CAPTION=TRANSFORM(0,'@J 999,999,999,999')
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL31.CAPTION=TRANSFORM(0,'@J 999,999,999,999')
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL41.CAPTION=TRANSFORM(0,'@J 999,999,999,999')        
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL51.CAPTION=TRANSFORM(0,'@J 999,999,999,999')     
        THISFORM.PAGEFRAME1.PAGE1.LBLTRN1.CAPTION=''   
        THISFORM.PAGEFRAME1.PAGE2.ENABLED=.F.      
     ELSE
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.T.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
        THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)    &&判斷有無列印的權限  
        THISFORM.ANS_BOTT.ENABLED=.T.        
        THISFORM.ACC_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                          
        THISFORM.ACC_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                  
        THISFORM.ACD_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.) AND IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                                  
        THISFORM.ACD_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.) AND IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                          
        THISFORM.PAGEFRAME1.PAGE2.ENABLED=.T.
     ENDIF   
     THISFORM.ORPGROUP.NEW_BOTT.ENABLED=IIF(A02.F04='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.)   &&判斷有無新增的權限     
     THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
  ENDPROC
  PROCEDURE PAGEFRAME1.PAGE2.ACTIVATE
      THISFORM.ACC_BOTT.ENABLED=.F.                
      THISFORM.ACD_BOTT.ENABLED=.F.                      
      SELE C13  
     IF THISFORM.SHRGROUP.ENABLED=.F.     
        THISFORM.GRID2.READONLY=.T.     
        THISFORM.GRID2.SETFOCUS    
     ENDIF
     IF THISFORM.GRID2.ACTIVEROW=0 .AND. THISFORM.SHRGROUP.ENABLED=.F.
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.F.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.F.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
        THISFORM.PAGEFRAME1.PAGE2.SETALL('VALUE','','TEXTBOX')
        THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE=''
        THISFORM.PAGEFRAME1.PAGE2.TXTF19.VALUE=''
        THISFORM.PAGEFRAME1.PAGE2.LBL191.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE2.LBLF081.CAPTION='0'
        THISFORM.PAFGFRAME1.PAGE2.LBLF121.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE2.LBLTS.CAPTION=''        
        THISFORM.PAGEFRAME1.PAGE2.LBLTU.CAPTION=''                
     ELSE
        THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.T.      
        THISFORM.CMDGROUP.UP_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.END_BOTT.ENABLED=.T.
        THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
        THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) &&判斷有無修改的權限
        THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.)  &&判斷有無刪除的權限
        THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)  &&&&判斷有無列印的權限  
     ENDIF   
     R=RECNO('&AREA1')
     THISFORM.GRID1.SETALL("DYNAMICBACKCOLOR","IIF(RECNO('&AREA1')=R,RGB(255,255,0),'')","COLUMN")
     THISFORM.GRID1.ENABLED=.F.     
     THISFORM.ORPGROUP.NEW_BOTT.ENABLED=IIF(A02.F04='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.)   &&判斷有無新增的權限
     THISFORM.KEY_LIST.ENABLED=.F.     
     THISFORM.MTH_LIST.ENABLED=.F.     
  ENDPROC     
  PROC INIT       
       CHK_STR=THISFORM.MTH_LIST.DISPLAYVALUE
       THISFORM.SETALL('HEIGHT',INT_015*25,'TEXTBOX')
       THISFORM.SETALL('HEIGHT',INT_015*17,'LABEL')
       THISFORM.SETALL('FONTSIZE',INT_015*9,'TEXTBOX')
       THISFORM.SETALL('FONTSIZE',INT_015*9,'LABEL')       
       THISFORM.SETALL('READONLY',.T.,'TEXTBOX')
       THISFORM.SHRGROUP.VISIBLE=.F.
       THISFORM.SHRGROUP.ENABLED=.F.
       IF ALLTRIM(INT_ACC)='FALSE'
          THISFORM.PAGEFRAME1.PAGE1.LBLTRN.VISIBLE=.F.
          THISFORM.PAGEFRAME1.PAGE1.LBLTRN1.VISIBLE=.F.          
       ENDIF
       THISFORM.GRID1.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)
       THISFORM.GRID2.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'COLUMN')
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'HEADER')         
       THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='客戶編號'
       THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='客戶簡稱'
       THISFORM.GRID1.COLUMN1.CONTROLSOURCE='C13_1.F03'
       THISFORM.GRID1.COLUMN2.CONTROLSOURCE='C01.F04'
       THISFORM.GRID1.COLUMN1.WIDTH=INT_015*60
       THISFORM.GRID1.COLUMN2.WIDTH=INT_015*149
       THISFORM.GRID2.SETALL('FONTSIZE',INT_015*9,'COLUMN')
       THISFORM.GRID2.SETALL('FONTSIZE',INT_015*9,'HEADER')       
       THISFORM.GRID2.COLUMN1.HEADER1.CAPTION='出貨日期'       
       THISFORM.GRID2.COLUMN2.HEADER1.CAPTION='料          號'
	   THISFORM.GRID2.COLUMN3.HEADER1.CAPTION='出貨數量'	  
	   THISFORM.GRID2.COLUMN4.HEADER1.CAPTION='幣別'
	   THISFORM.GRID2.COLUMN5.HEADER1.CAPTION='單    價'
       THISFORM.GRID2.COLUMN6.HEADER1.CAPTION=INT_011+'小計'	   
	   THISFORM.GRID2.LINKMASTER='C13_1'
       THISFORM.GRID2.RELATIONALEXPR='F03'
	   THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C13.F01'
	   THISFORM.GRID2.COLUMN2.CONTROLSOURCE='C13.F05'
	   THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C13.F06'
	   THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C13.F13'
  	   THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C13.F07'
   	   THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C13.F08'
	   THISFORM.GRID2.COLUMN1.WIDTH=INT_015*70
       THISFORM.GRID2.COLUMN2.WIDTH=INT_015*149
       THISFORM.GRID2.COLUMN3.WIDTH=INT_015*80
       THISFORM.GRID2.COLUMN4.WIDTH=INT_015*30
       THISFORM.GRID2.COLUMN5.WIDTH=INT_015*80
       THISFORM.GRID2.COLUMN6.WIDTH=INT_015*90
       THISFORM.GRID1.READONLY=.T.      
       THISFORM.GRID2.READONLY=.T.            
       THISFORM.GRID1.SETFOCUS
       IF THISFORM.GRID1.ACTIVEROW=0
          THISFORM.CMDGROUP.ENABLED=.F.
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
          THISFORM.ANS_BOTT.ENABLED=.F.
          THISFORM.ACC_BOTT.ENABLED=.F.          
          THISFORM.ACD_BOTT.ENABLED=.F.                    
       ELSE
          THISFORM.CMDGROUP.ENABLED=.T.      
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限 
          THISFORM.ACC_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                                      
          THISFORM.ACC_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                            
          THISFORM.ACD_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.) AND IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                                      
          THISFORM.ACD_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.) AND IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                                      
          THISFORM.ANS_BOTT.ENABLED=.T.      
       ENDIF  
       THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.       
       THISFORM.KEY_LIST.DISPLAYVALUE='依客戶編號排列'      
       JK='客戶編號'
       SELE C13_1
       THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE=C13_1.F03
  ENDPROC               
  PROC KEY_LIST.INIT 
       WITH THIS 
           .ADDITEM('依客戶編號排列')      
       ENDWITH      
  ENDPROC 
  PROC MTH_LIST.INTERACTIVECHANGE
       CHK_STR=THISFORM.MTH_LIST.DISPLAYVALUE
       THISFORM.GRID1.RECORDSOURCE=''
       THISFORM.GRID2.RECORDSOURCE=''
       THISFORM.GRID2.LINKMASTER=''
       THISFORM.GRID2.RELATIONALEXPR=''
       THISFORM.GRID2.CHILDORDER=''            
       SELECT B0A
       FILTER_KEY=LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6) 
       SET FILTER TO LEFT(DTOS(F03),6)<=FILTER_KEY
       SELE B04
       USE
       SELE B05
       USE     
       SELE C10
       USE  
       SELE C13
       SET RELA OFF INTO A01
       SET RELA OFF INTO B01
       SET RELA OFF INTO C13_1
       USE
       SELE C13_1
       SET RELA OFF INTO C01
       USE
       B04='B04'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       B041='B041'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)       
       IF !USED('&B04')
          SELE 0
          USE (B04) ALIA B04
       ELSE
          SELE B04
       ENDIF
       SET ORDER TO B041
       B05='B05'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       B051='B051'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)       
       IF !USED('&B05')
          SELE 0
          USE (B05) ALIA B05
       ELSE
          SELE B05
       ENDIF
       SET ORDER TO B051                                    
       C10='C10'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       C105='C105'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)      
       IF !USED('&C10')
          SELE 0
          USE (C10) ALIA C10
       ELSE
          SELE C10
       ENDIF
       SET ORDER TO C105                      
       C13='C13'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       C131='C131'+LEFT(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),6)
       IF !USED('&C13')
          SELE 0
          USE (C13) ALIA C13
       ELSE
          SELE C13
       ENDIF
       SET ORDER TO C131      
       SET RELA TO F03 INTO B01
       SET RELA TO F19 INTO A01 ADDI
       CREATE CURSOR C13_1;
       (F03 C(5),F10 C(8),F06 N(13,2),F07 N(13,2),F08 N(13,2),F09 N(13,2),FTR C(10),F11 N(13,2))
       INDE ON F03 TAG C13_11
       INDE ON F10+F03 TAG C13_12
       SELE F03,F10 FROM C13 GROUP BY F03 ORDER BY C13.F03 INTO CURSOR C13_2
       SELE C13_2
       GO TOP 
       DO WHILE !EOF()
          SELE C13_1
          APPEND BLANK
          REPLACE  F03 WITH C13_2.F03
          REPLACE  F10 WITH IIF(SEEK(C13_2.F03,'C01'),C01.F10,'')   
          REPLACE  F06 WITH TTL1(C13_1.F03)
          REPLACE  F07 WITH TTL2(C13_1.F03)
          REPLACE  F08 WITH TTL3_1(C13_1.F03)
          REPLACE  F09 WITH TTL4(C13_1.F03)            
          REPLACE FTR WITH C13_2.F10
          REPLACE F11 WITH TTL3_2(C13_1.F03)
          SELE C13_2
          SKIP   
       ENDDO
       SELE C13_2
       USE   
       SELE C13_1
       SET ORDER TO C13_11
       SET RELA TO F03 INTO C01
       THISFORM.GRID1.RECORDSOURCE='C13_1'
       THISFORM.GRID2.RECORDSOURCE='C13'
	   THISFORM.GRID2.LINKMASTER='C13_1'
       THISFORM.GRID2.RELATIONALEXPR='F03'      
       THISFORM.GRID2.CHILDORDER=C131  
       THISFORM.GRID1.COLUMN1.CONTROLSOURCE='C13_1.F03'
       THISFORM.GRID1.COLUMN2.CONTROLSOURCE='C01.F04'       
	   THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C13.F01'
	   THISFORM.GRID2.COLUMN2.CONTROLSOURCE='C13.F05'
	   THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C13.F06'
	   THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C13.F13'
  	   THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C13.F07'
   	   THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C13.F08'            
       THISFORM.KEY_LIST.INTERACTIVECHANGE
	   THISFORM.PAGEFRAME1.ACTIVEPAGE=1
	   THISFORM.REFRESH
	   THISFORM.GRID1.SETFOCUS        
       IF THISFORM.GRID1.ACTIVEROW=0
          THISFORM.CMDGROUP.ENABLED=.F.
          THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
          THISFORM.ACC_BOTT.ENABLED=.F.
          THISFORM.ACD_BOTT.ENABLED=.F.          
       ELSE
          THISFORM.CMDGROUP.ENABLED=.T.      
          THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.
          THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限  
          THISFORM.ACC_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                          
          THISFORM.ACC_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.) AND !IIF(SEEK(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                  
          THISFORM.ACD_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.) AND IIF(SEEK(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                                  
          THISFORM.ACD_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.) AND IIF(SEEK(DTOS(CTOD(THIS.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                                      
       ENDIF          
  ENDPROC
  PROC GRID1.AFTERROWCOLCHANGE
       LPARAMETERS NCOLINDEX       
       THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE=C13_1.F03
       THISFORM.PAGEFRAME1.PAGE1.LBLF041.CAPTION=C01.F04
       THISFORM.PAGEFRAME1.PAGE1.LBLTTL11.CAPTION=TRANSFORM(C13_1.F06,'@J 999,999,999,999.99')
       THISFORM.PAGEFRAME1.PAGE1.LBLTTL21.CAPTION=TRANSFORM(C13_1.F07*(-1),'@J 999,999,999,999.99')       
       THISFORM.PAGEFRAME1.PAGE1.LBLTTL31.CAPTION=TRANSFORM(C13_1.F08+C13_1.F11,'@J 999,999,999,999.99')      
       THISFORM.PAGEFRAME1.PAGE1.LBLTTL41.CAPTION=TRANSFORM(C13_1.F09*(-1),'@J 999,999,999,999.99')                     
       THISFORM.PAGEFRAME1.PAGE1.LBLTTL51.CAPTION=TRANSFORM(C13_1.F06+C13_1.F07+C13_1.F08+C13_1.F09+C13_1.F11,'@J 999,999,999,999.99')  
       THISFORM.PAGEFRAME1.PAGE1.LBLTRN1.CAPTION=C13_1.FTR            
       FCH=THISFORM.ACTIVECONTROL.NAME
       JK=THIS.COLUMN1.HEADER1.CAPTION  
       IF THIS.ACTIVEROW=0
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
       ELSE
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.
       ENDIF   
       CHK=''     
*       THISFORM.REFRESH
  ENDPROC     
  PROC GRID2.AFTERROWCOLCHANGE
       LPARAMETERS NCOLINDEX
       THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE=C13.F01       
       THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE=C13.F02
       THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE=C13.F04
       THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE=C13.F05
       THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE=C13.F06
       THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=C13.F07       
       THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE=C13.F13
       THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=C13.F14     
       THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE=C13.F15            
       THISFORM.PAGEFRAME1.PAGE2.TXTF17.VALUE=C13.F17                   
       THISFORM.PAGEFRAME1.PAGE2.TXTF19.VALUE=C13.F19       
       THISFORM.PAGEFRAME1.PAGE2.LBLF191.CAPTION=A01.F03  
       THISFORM.PAGEFRAME1.PAGE2.LBLF081.CAPTION=TRANSFORM(C13.F08,'@J 999999999.99')
       THISFORM.PAGEFRAME1.PAGE2.LBLF121.CAPTION=C13.F12       
       THISFORM.PAGEFRAME1.PAGE2.LBLTU.CAPTION=IIF(C13.F18='03','折讓','')       
       THISFORM.PAGEFRAME1.PAGE2.LBLTS.CAPTION=IIF(C13.F16='02','稅內含','')              
       FCH=THISFORM.ACTIVECONTROL.NAME
       JK=THIS.COLUMN1.HEADER1.CAPTION
       CHK=THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE
       IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
       ENDIF   
*       THISFORM.REFRESH
  ENDPROC 
  PROCEDURE ORPGROUP.NEW_BOTT.CLICK   
    THISFORM.KEY_LIST.ENABLED=.F. 
    THISFORM.MTH_LIST.ENABLED=.F. 
    THISFORM.ANS_BOTT.ENABLED=.F.
    THISFORM.ACC_BOTT.ENABLED=.F.    
    THISFORM.ACD_BOTT.ENABLED=.F.        
    IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1       
       THISFORM.GRID2.RECORDSOURCE=''
       THISFORM.GRID2.CHILDORDER=''
       THISFORM.PAGEFRAME1.PAGE1.SETALL('READONLY',.F.,'TEXTBOX')     &&處理表頭新增
       THISFORM.GRID1.ENABLED=.F.   
       THISFORM.GRID2.ENABLED=.F.   
        THISFORM.PAGEFRAME1.PAGE2.ENABLED=.F.
        THISFORM.PAGEFRAME1.PAGE1.TXTF03.READONLY=.F.
        THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE=''
        THISFORM.PAGEFRAME1.PAGE1.TXTF03.SETFOCUS
        THISFORM.PAGEFRAME1.PAGE1.LBLF041.CAPTION=''
        THISFORM.PAGEFRAME1.PAGE1.LBLTRN1.CAPTION=''        
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL11.CAPTION=TRANSFORM(0,'@J 999,999,999,999')        
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL21.CAPTION=TRANSFORM(0,'@J 999,999,999,999')        
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL31.CAPTION=TRANSFORM(0,'@J 999,999,999,999')        
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL41.CAPTION=TRANSFORM(0,'@J 999,999,999,999')        
        THISFORM.PAGEFRAME1.PAGE1.LBLTTL51.CAPTION=TRANSFORM(0,'@J 999,999,999,999')     
     ELSE
        THISFORM.PAGEFRAME1.PAGE1.ENABLED=.F.              &&處理表身新增
        THISFORM.GRID2.ENABLED=.F.   
        THISFORM.PAGEFRAME1.PAGE2.SETALL('READONLY',.F.,'TEXTBOX')     
        THISFORM.PAGEFRAME1.PAGE2.CRCY.VISIBLE=.T.
        THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE=INT_011
        THISFORM.PAGEFRAME1.PAGE2.CRCY.ENABLED=.T.
        THISFORM.PAGEFRAME1.PAGE2.TXTF01.SETFOCUS        
        THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE=DATE()
        THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE=''        
        THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE=''                
        THISFORM.PAGEFRAME1.PAGE2.TXTF05.READONLY=.F.
        THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE=''
        THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=0        
        THISFORM.PAGEFRAME1.PAGE2.TXTF19.READONLY=.F.
        THISFORM.PAGEFRAME1.PAGE2.TXTF19.VALUE=C01.F18
        THISFORM.PAGEFRAME1.PAGE2.LBLF191.CAPTION=IIF(SEEK(C01.F18,'A01'),A01.F03,'')
        THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE=0
        THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE=0
        THISFORM.PAGEFRAME1.PAGE2.LBLF081.CAPTION=TRANSFORM(0,'999999999.99')
        THISFORM.PAGEFRAME1.PAGE2.LBLF121.CAPTION=''               
        THISFORM.PAGEFRAME1.PAGE2.LBLTS.CAPTION=''        
        THISFORM.PAGEFRAME1.PAGE2.LBLTU.CAPTION=''                        
        THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE=THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE      
        THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=1      
        THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE=''                       
     ENDIF   

  ENDPROC  
  PROCEDURE ORPGROUP.EDIT_BOTT.CLICK
     THISFORM.KEY_LIST.ENABLED=.F. 
     THISFORM.MTH_LIST.ENABLED=.F. 
     THISFORM.ANS_BOTT.ENABLED=.F.     
    THISFORM.ACC_BOTT.ENABLED=.F.     
    THISFORM.ACD_BOTT.ENABLED=.F.         
     THISFORM.GRID1.ENABLED=.F.   
     THISFORM.GRID2.ENABLED=.F.    
     SELE C13        &&處理表身修改
     LOCK()
        IF RLOCK() 
           THISFORM.PAGEFRAME1.PAGE2.SETALL('READONLY',.F.,'TEXTBOX') 
           THISFORM.PAGEFRAME1.PAGE2.CRCY.VISIBLE=.T.
           THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE=THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE
           THISFORM.PAGEFRAME1.PAGE2.CRCY.ENABLED=.T.
           THISFORM.PAGEFRAME1.PAGE2.TXTF05.READONLY=.F.
           THISFORM.PAGEFRAME1.PAGE2.TXTF19.READONLY=.F.
           THISFORM.PAGEFRAME1.PAGE2.TXTF05.SETFOCUS
        ELSE  
           DO FILE_IMPACT 
           UNLOCK ALL
           THISFORM.SHRGROUP.ABANDON_BOTT.CLICK           
       ENDIF             
  ENDPROC    
  PROC ORPGROUP.DEL_BOTT.CLICK                    &&刪除資料程序
       IF MESSAGEBOX('是否確定要刪除此筆資料',4+32+256,'請確認') = 6	        
          IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1          &&刪除整張訂單
             SELE C13_1             
                PO_NO=C13_1.F03
                SELE RECNO() FROM C13 WHERE C13.F03=PO_NO  INTO ARRAY BK1              
                JJ1=''                
                IF _TALLY>0   
                   FOR I= 1 TO ALEN(BK1)
                       JJ1=JJ1+ALLTRIM(STR(BK1(I)))+','
                   ENDFOR    
                   KK1=STUFF(JJ1,RAT(',',JJ1,1),1,'')              
                   RLOCK(KK1,'C13')
                   LL1=RLOCK(KK1,'C13')
                ELSE
                   LL1=.T.   
                ENDIF                   
                IF LL1 .AND. RLOCK('C13_1')                        
                   SELE C13    
                   DELE FROM C13 WHERE F03=PO_NO                                   
                   SELE C13_1
                   DELE
                   UNLOCK ALL
                ELSE
                   DO FILE_IMPACT                  
                ENDIF
             
             THISFORM.GRID1.SETFOCUS
             IF THISFORM.GRID1.ACTIVEROW=0
                THISFORM.CMDGROUP.ENABLED=.F.
                THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=.F.
                THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.               
                THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.
             ELSE      
                THISFORM.CMDGROUP.ENABLED=.T.
                THISFORM.ORPGROUP.DEL_BOTT.ENABLED=IIF(A02.F06='*',.T.,.F.)    &&判斷有無刪除的權限
                THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限
             ENDIF     
          ELSE                                                                &&刪除單筆資料        
              SELE C13             
              RLOCK()                                         
              IF RLOCK()
                 SELE C10
                 DELE FROM C10 WHERE F05+F04+F03=C13.F04+C13.F02+C13.F05
                 SELECT C13
                DO CASE
                      CASE LEFT(C13.F02,2)='BC' AND LEFT(C13.F04,4)<>'稅額'                      &&出貨
                                 IF LEFT(C13.F16,2)<>'02'
                                    REPLACE C13_1.f06 WITH C13_1.F06+C13.F08*(-1) 
                                 ELSE
                                    REPLACE C13_1.F06 WITH C13_1.F06+ROUND(C13.f08/(1+INT_002/100),INT_069)*(-1)                 &&二聯式應稅    
                                    REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))*(-1)
                                ENDIF    
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18<>'03'                 &&退貨
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F07 WITH C13_1.F07+C13.F08*(-1) 
                                  ELSE
                                      REPLACE C13_1.F07 WITH C13_1.F07+ROUND(C13.f08/(1+INT_002/100),INT_069)*(-1)                &&二聯式應稅  
                                      REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))*(-1)                                      
                                  ENDIF    
                      CASE   LEFT(C13.F04,4)='稅額'                                     &&稅額
                                      REPLACE C13_1.F08 WITH C13_1.F08+C13.F08*(-1) 
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18='03'       &&出貨折讓
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F09 WITH C13_1.F09+C13.F08*(-1)                           
                                  ELSE
                                     REPLACE C13_1.F09 WITH C13_1.F09+ROUND(C13.f08/(1+INT_002/100),INT_069)*(-1)                        &&二聯式應稅
                                     REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))*(-1)                                     
                                  ENDIF    
                 ENDCASE                  
                 SELE C13
                 DELE
                 SKIP -1
                 IF BOF()
                    GO TOP
                 ENDIF   
              ELSE
                 DO FILE_IMPACT                  
              ENDIF                   
              THISFORM.GRID2.SETFOCUS
              IF THISFORM.GRID2.ACTIVEROW=0         &&如果單身被刪空               
                 SELE C13_1                        
                 DELE                               &&連表頭也要刪除
                 SKIP -1
                 IF BOF()
                    GO TOP
                 ENDIF   
                 THISFORM.PAGEFRAME1.ACTIVEPAGE=1 
                 THISFORM.REFRESH          
              ENDIF
          ENDIF
       ENDIF
       RELEASE ALL LIKE BK*   
  ENDPROC  
  PROCEDURE SHRGROUP.SHURE1_BOTT.CLICK               &&新增確認
    IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
       THISFORM.GRID2.RECORDSOURCE='C13'
       THISFORM.GRID2.CHILDORDER=C131
	   THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C13.F01'
	   THISFORM.GRID2.COLUMN2.CONTROLSOURCE='C13.F05'
	   THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C13.F06'
	   THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C13.F13'
  	   THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C13.F07'
   	   THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C13.F08'       
       SELE C13_1 
       COD=SYS(21)
       SET ORDER TO 1
       IF SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE,'C13_1')=.T.
          =MESSAGEBOX('此客戶於本月已有應收帳款資料!,請直接去表身詳細資料內容新增',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE1.TXTF03.SETFOCUS
          RETURN  
       ENDIF
       IF SEEK(THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE,'C01')=.F. .OR. EMPTY(THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE)
          =MESSAGEBOX('客戶基本主檔中無此編號請先建立!',0+64,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE1.TXTF03.SETFOCUS
          SET ORDER TO &COD
          RETURN            
       ENDIF
       SELE C13_1          
       APPEND BLANK
       LOCK()
       IF RLOCK()
          REPLACE F03 WITH THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE   
       ENDIF
*       UNLOCK
       SEEK THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE      
       THISFORM.PAGEFRAME1.PAGE1.ENABLED=.F.
       THISFORM.PAGEFRAME1.PAGE2.ENABLED=.T.  
       THISFORM.PAGEFRAME1.ACTIVEPAGE=2
       THISFORM.ORPGROUP.NEW_BOTT.CLICK
       THISFORM.REFRESH
    ELSE         &&表身新增確認    
       IF LEFT(DTOS(THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE),6)>LEFT(DTOS(CTOD(ALLTRIM(THISFORM.MTH_LIST.DISPLAYVALUE)+'/01')),6)
          =MESSAGEBOX('出貨日期不得大於本月',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF01.SETFOCUS
          RETURN
       ENDIF    
       IF EMPTY(THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE)
          =MESSAGEBOX("請輸入正確的料號或是'發票:'兩字及其發票號碼或是出貨時所發生的其他費用名稱",0+48,"提示訊息視窗")
          THISFORM.PAGEFRAME1.PAGE2.TXTF05.SETFOCUS
          RETURN
       ENDIF                    
       IF THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE=0
          =MESSAGEBOX('出貨數量不得為 0',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF06.SETFOCUS
          RETURN
       ENDIF                 
       IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)<>'BC' 
          IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)<>'BD'
                =MESSAGEBOX("出貨單號欄位請輸入正確的出(退)貨單號",0+48,"提示訊息視窗")         
                THISFORM.PAGEFRAME1.PAGE2.TXTF02.SETFOCUS
                RETURN
          ENDIF      
       ENDIF
       IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)='BC'  .OR. LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)='BD' 
           IF LEN(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE))<>10
               =MESSAGEBOX('出貨單號不足10碼,請重新輸入!',0+48,'提示訊息視窗')
               THISFORM.PAGEFRAME1.PAGE2.TXTF02.SETFOCUS
               RETURN
           ENDIF    
       ENDIF           
       IF THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE<=0
          =MESSAGEBOX('單價一定要大於 0',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF07.SETFOCUS
          RETURN
       ENDIF                 
       IF THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE<=0
          =MESSAGEBOX('匯率一定要大於 0',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF14.SETFOCUS
          RETURN
       ENDIF      
       IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE,2)='CA'
          SELE C10
          APPEND BLANK
          REPL F01 WITH RIGHT(DTOS(THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE),2)
          REPL F02 WITH C13_1.F03
          REPL F03 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE
          REPL F04 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE
          REPL F05 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE
          REPL F06 WITH INT_011
          REPL F07 WITH IIF(THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=1,THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE,THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE)          
          REPL F08 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE
          REPLACE F09 WITH C01.F05
          REPLACE F10 WITH C01.F18
          REPLACE F11 WITH IIF(SEEK(C01.F18,'A01'),A01.F03,'')
          REPLACE F12 WITH C01.F33
          REPLACE F13 WITH IIF(SEEK(C01.F33,'A01'),A01.F03,'')          
          REPLACE F14 WITH C01.F23
          REPLACE F15 WITH IIF(SEEK(C01.F23,'A01'),A01.F03,'')                           
       ENDIF                  
       SELE C13
       APPEND BLANK       
       RLOCK()
          REPLACE F01 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE
          REPLACE F02 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE
          REPLACE F03 WITH C13_1.F03
          REPLACE F04 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE
          REPLACE F05 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE
          REPLACE F06 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE
          REPLACE F07 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE
          REPLACE F14 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE                                        
          REPLACE F08 WITH IIF(F14=1,ROUND(F06*F07,INT_069),ROUND(F06*F07*F14,INT_069))
          REPLACE F09 WITH '1'
          REPLACE F12 WITH IIF(INT_012=1,PADL(ALLTRIM(STR(YEAR(DATE())-1911)),3,' ')+RIGHT(DTOC(DATE()),6),dtoc(DATE())+' ')+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
          REPLACE F13 WITH THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE
          REPLACE F15 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE                      
          REPLACE F17 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF17.VALUE                                        
          REPLACE F19 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF19.VALUE   
          REPLACE F79 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE 
          IF LEFT(F04,4)<>'稅額'
              IF messagebox('稅是否內含',4+32+256,'請確認') = 6	        
                  REPLACE F16 WITH '02'
              ENDIF
              IF F08<0
                  IF LEFT(F02,2)<>'BD'
                      REPLACE F02 WITH 'BD'
                  ENDIF
                  IF messagebox('是否為折讓',4+32+256,'請確認') = 6	        
                      REPLACE F18 WITH '03'
                  ENDIF              
              ENDIF
          ENDIF                                               
 
                DO CASE
                      CASE LEFT(C13.F02,2)='BC' AND LEFT(C13.F04,4)<>'稅額'                      &&出貨
                                 IF LEFT(C13.F16,2)<>'02'
                                    REPLACE C13_1.f06 WITH C13_1.F06+C13.F08 
                                 ELSE
                                    REPLACE C13_1.F06 WITH C13_1.F06+ROUND(C13.f08/(1+INT_002/100),INT_069)                 &&二聯式應稅    
                                    REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))
                                ENDIF    
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18<>'03'                 &&退貨
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F07 WITH C13_1.F07+C13.F08 
                                  ELSE
                                      REPLACE C13_1.F07 WITH C13_1.F07+ROUND(C13.f08/(1+INT_002/100),INT_069)                &&二聯式應稅  
                                      REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))                                      
                                  ENDIF    
                      CASE   LEFT(C13.F04,4)='稅額'                                     &&稅額
                                      REPLACE C13_1.F08 WITH C13_1.F08+C13.F08 
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18='03'       &&出貨折讓
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F09 WITH C13_1.F09+C13.F08                           
                                  ELSE
                                     REPLACE C13_1.F09 WITH C13_1.F09+ROUND(C13.f08/(1+INT_002/100),INT_069)                        &&二聯式應稅
                                     REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))                                     
                                  ENDIF    
                 ENDCASE                  
      UNLOCK ALL         
      SELE C13
      SEEK THISFORM.PAGEFRAME1.PAGE1.TXTF03.VALUE+DTOS(THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE)
      THISFORM.GRID2.ENABLED=.T.
      THISFORM.GRID2.SETFOCUS  
      THISFORM.ORPGROUP.NEW_BOTT.CLICK      
    ENDIF  
  ENDPROC
  PROCEDURE SHRGROUP.SHURE2_BOTT.CLICK                          &&修改確認
       IF LEFT(DTOS(THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE),6)>LEFT(DTOS(CTOD(ALLTRIM(THISFORM.MTH_LIST.DISPLAYVALUE)+'/01')),6)
          =MESSAGEBOX('出貨日期不得大於本月',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF01.SETFOCUS
          RETURN
       ENDIF    
       IF EMPTY(THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE)
          =MESSAGEBOX("請輸入正確的料號或是'發票:'兩字及其發票號碼或是出貨時所發生的其他費用名稱",0+48,"提示訊息視窗")
          THISFORM.PAGEFRAME1.PAGE2.TXTF05.SETFOCUS
          RETURN
       ENDIF                    
       IF THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE=0
          =MESSAGEBOX('出貨數量不得為 0',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF06.SETFOCUS
          RETURN
       ENDIF                 
       IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)<>'BC' 
          IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)<>'BD'
             IF SUBSTR(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,3,6)<>'類發票'
                =MESSAGEBOX("出貨單號欄位請輸入正確的出(退)貨單號或是'31(32)類發票'",0+48,"提示訊息視窗")         
                THISFORM.PAGEFRAME1.PAGE2.TXTF02.SETFOCUS
                RETURN
             ENDIF
          ENDIF      
       ENDIF   
       IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)='BC'  .OR. LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)='BD' 
           IF LEN(ALLTRIM(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE))<>10
               =MESSAGEBOX('出貨單號不足10碼,請重新輸入!',0+48,'提示訊息視窗')
               THISFORM.PAGEFRAME1.PAGE2.TXTF02.SETFOCUS
               RETURN
           ENDIF    
       ENDIF          
       IF THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE<=0
          =MESSAGEBOX('單價一定要大於 0',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF07.SETFOCUS
          RETURN
       ENDIF                 
       IF THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE<=0
          =MESSAGEBOX('匯率一定要大於 0',0+48,'提示訊息視窗')
          THISFORM.PAGEFRAME1.PAGE2.TXTF14.SETFOCUS
          RETURN
       ENDIF                     
       IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE,2)='CA'
          SELE C10
          SEEK THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE+THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE
          IF FOUND()
             REPL F01 WITH RIGHT(DTOS(THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE),2)
             REPL F07 WITH IIF(THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=1,THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE,THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE*THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE)          
             REPL F08 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE
          ENDIF   
          IF C13.F13<>THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE .OR. C13.F14<>THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE .OR. C13.F07<>THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE 
             IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)='BC'
                SELE B04
                SEEK THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE+IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE,'B0A'),B0A.F01,THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE)+THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE
                IF FOUND()
                   REPL F14 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE
                   REPL F15 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE
                   REPL F16 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE
                   REPL F17 WITH ROUND(IIF(F16=1,F04*F15,F04*F15*F16),INT_069)
                   REPL F11 WITH IIF(INT_012=1,PADL(ALLTRIM(STR(YEAR(DATE())-1911)),3,' ')+RIGHT(DTOC(DATE()),6),dtoc(DATE())+' ')+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
                ENDIF                
             ENDIF
             IF LEFT(THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE,2)='BD'
                SELE B05
                SEEK THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE+IIF(SEEK(THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE,'B0A'),B0A.F01,THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE)+THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE
                IF FOUND()
                   REPL F16 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE
                   REPL F17 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE
                   REPL F18 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE
                   REPL F13 WITH IIF(INT_012=1,PADL(ALLTRIM(STR(YEAR(DATE())-1911)),3,' ')+RIGHT(DTOC(DATE()),6),dtoc(DATE())+' ')+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
                ENDIF                
             ENDIF             
          ENDIF
       ENDIF                            
          SELECT C13
                DO CASE
                      CASE LEFT(C13.F02,2)='BC' AND LEFT(C13.F04,4)<>'稅額'                      &&出貨
                                 IF LEFT(C13.F16,2)<>'02'
                                    REPLACE C13_1.f06 WITH C13_1.F06+C13.F08*(-1) 
                                 ELSE
                                    REPLACE C13_1.F06 WITH C13_1.F06+ROUND(C13.f08/(1+INT_002/100),INT_069)*(-1)                 &&二聯式應稅    
                                    REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))*(-1)
                                ENDIF    
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18<>'03'                 &&退貨
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F07 WITH C13_1.F07+C13.F08*(-1) 
                                  ELSE
                                      REPLACE C13_1.F07 WITH C13_1.F07+ROUND(C13.f08/(1+INT_002/100),INT_069)*(-1)                &&二聯式應稅  
                                      REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))*(-1)                                      
                                  ENDIF    
                      CASE   LEFT(C13.F04,4)='稅額'                                     &&稅額
                                      REPLACE C13_1.F08 WITH C13_1.F08+C13.F08*(-1) 
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18='03'       &&出貨折讓
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F09 WITH C13_1.F09+C13.F08*(-1)                           
                                  ELSE
                                     REPLACE C13_1.F09 WITH C13_1.F09+ROUND(C13.f08/(1+INT_002/100),INT_069)*(-1)                        &&二聯式應稅
                                     REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))*(-1)                                     
                                  ENDIF    
                 ENDCASE                  
          SELE C13  
          REPLACE F01 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF01.VALUE
          REPLACE F02 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF02.VALUE
          REPLACE F04 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF04.VALUE
          REPLACE F05 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE
          REPLACE F06 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF06.VALUE
          REPLACE F07 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF07.VALUE
          REPLACE F14 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE           
          REPLACE F08 WITH IIF(F14=1,ROUND(F06*F07,INT_069),ROUND(F06*F07*F14,INT_069))
          REPLACE F12 WITH IIF(INT_012=1,PADL(ALLTRIM(STR(YEAR(DATE())-1911)),3,' ')+RIGHT(DTOC(DATE()),6),dtoc(DATE())+' ')+IIF(SEEK(sys_oper,'A01'),A01.F03,'')
          REPLACE F13 WITH THISFORM.PAGEFRAME1.PAGE2.CRCY.DISPLAYVALUE
          REPLACE F15 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF15.VALUE      
          REPLACE F17 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF17.VALUE                                                                                    
          REPLACE F19 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF19.VALUE 
          REPLACE F79 WITH THISFORM.PAGEFRAME1.PAGE2.TXTF05.VALUE   
          UNLOCK ALL
                DO CASE
                      CASE LEFT(C13.F02,2)='BC' AND LEFT(C13.F04,4)<>'稅額'                      &&出貨
                                 IF LEFT(C13.F16,2)<>'02'
                                    REPLACE C13_1.f06 WITH C13_1.F06+C13.F08 
                                 ELSE
                                    REPLACE C13_1.F06 WITH C13_1.F06+ROUND(C13.f08/(1+INT_002/100),INT_069)                 &&二聯式應稅    
                                    REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))
                                ENDIF    
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18<>'03'                 &&退貨
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F07 WITH C13_1.F07+C13.F08 
                                  ELSE
                                      REPLACE C13_1.F07 WITH C13_1.F07+ROUND(C13.f08/(1+INT_002/100),INT_069)                &&二聯式應稅  
                                      REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))                                      
                                  ENDIF    
                      CASE   LEFT(C13.F04,4)='稅額'                                     &&稅額
                                      REPLACE C13_1.F08 WITH C13_1.F08+C13.F08 
                      CASE  LEFT(C13.F02,2)='BD' AND LEFT(C13.F04,4)<>'稅額' AND C13.F18='03'       &&出貨折讓
                                  IF LEFT(C13.F16,2)<>'02'
                                      REPLACE C13_1.F09 WITH C13_1.F09+C13.F08                           
                                  ELSE
                                     REPLACE C13_1.F09 WITH C13_1.F09+ROUND(C13.f08/(1+INT_002/100),INT_069)                        &&二聯式應稅
                                     REPLACE C13_1.F08 WITH C13_1.F08+(C13.F08-ROUND(C13.f08/(1+INT_002/100),INT_069))                                     
                                  ENDIF    
                 ENDCASE                  
 *      ELSE
*         DO FILE_IMPACT
*          RETURN   
*       ENDIF   
     SELE C13
     THISFORM.SHRGROUP.ABANDON_BOTT.CLICK    
  ENDPROC   
  PROCEDURE SHRGROUP.ABANDON_BOTT.CLICK
      THISFORM.SHRGROUP.ENABLED=.F.
      THISFORM.SHRGROUP.VISIBLE=.F.      
      THISFORM.ORPGROUP.ENABLED=.T.
      THISFORM.ANS_BOTT.ENABLED=.T.      
      THISFORM.ACC_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.)  AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                              
      THISFORM.ACC_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.)  AND !IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                        
      THISFORM.ACD_BOTT.VISIBLE=IIF(A02.F08='*',.T.,.F.)  AND IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                                    
      THISFORM.ACD_BOTT.ENABLED=IIF(A02.F08='*',.T.,.F.)  AND IIF(SEEK(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),'A23','A231'),A23.F14,.F.) AND ALLTRIM(INT_ACC)<>'FALSE' &&判斷有無轉會計傳票的權限                              
      THISFORM.ORPGROUP.SETALL('FORECOLOR',RGB(0,0,0),'COMMANDBUTTON')
      THISFORM.CMDGROUP.ENABLED=.T.
      THISFORM.CMDGROUP.SETALL('ENABLED',.T.,'COMMANDBUTTON')
      THISFORM.CMDGROUP.SETALL('FORECOLOR',RGB(0,0,0),'COMMANDBUTTON')
      THISFORM.SETALL('READONLY',.T.,'TEXTBOX')  
      THISFORM.PAGEFRAME1.PAGE1.SETALL('READONLY',.T.,'TEXTBOX')  
      THISFORM.PAGEFRAME1.PAGE2.SETALL('READONLY',.T.,'TEXTBOX')  
      THISFORM.PAGEFRAME1.PAGE1.TXTF03.READONLY=.T.  
      THISFORM.PAGEFRAME1.PAGE2.TXTF05.READONLY=.T. 
      THISFORM.PAGEFRAME1.PAGE2.TXTF19.READONLY=.T.   
      THISFORM.PAGEFRAME1.PAGE2.CRCY.VISIBLE=.F.
      THISFORM.PAGEFRAME1.PAGE1.ENABLED=.T.
      THISFORM.PAGEFRAME1.PAGE2.ENABLED=.T.
      IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1   
           THISFORM.GRID1.ENABLED=.T.
          THISFORM.GRID2.ENABLED=.T.
         THISFORM.GRID1.SETFOCUS
         THISFORM.KEY_LIST.ENABLED=.T.
         THISFORM.MTH_LIST.ENABLED=.T.      
      ELSE
           THISFORM.GRID1.ENABLED=.F.
          THISFORM.GRID2.ENABLED=.T.      
         THISFORM.GRID2.SETFOCUS
         IF THISFORM.GRID2.ACTIVEROW=0
            SELE C13_1
            DELE
            THISFORM.PAGEFRAME1.ACTIVEPAGE=1
            THISFORM.REFRESH  
         ENDIF   
      ENDIF       
      UNLOCK ALL
  ENDPROC
  PROCEDURE SHRGROUP.FINISH_BOTT.CLICK
      IF THISFORM.PAGEFRAME1.ACTIVEPAGE=1
         IF THISFORM.GRID2.RECORDSOURCE<>'C13'
            THISFORM.GRID2.RECORDSOURCE='C13'
            THISFORM.GRID2.CHILDORDER=C131
       	    THISFORM.GRID2.COLUMN1.CONTROLSOURCE='C13.F01'
	        THISFORM.GRID2.COLUMN2.CONTROLSOURCE='C13.F05'
	        THISFORM.GRID2.COLUMN3.CONTROLSOURCE='C13.F06'
	        THISFORM.GRID2.COLUMN4.CONTROLSOURCE='C13.F13'
  	        THISFORM.GRID2.COLUMN5.CONTROLSOURCE='C13.F07'
   	        THISFORM.GRID2.COLUMN6.CONTROLSOURCE='C13.F08'         
	     ENDIF   
      ENDIF  
      THISFORM.SHRGROUP.ABANDON_BOTT.CLICK
  ENDPROC   
  PROCEDURE ANS_BOTT.CLICK
      IF MESSAGEBOX('是否只印銷貨',4+32+256,'請確認') = 6	        
        UKEF='1'
      ELSE
        UKEF='0'  
      ENDIF
       SELE C13_1
       R=RECNO()
       ANS_CHK=CREATEOBJECT("ANS_CHK")  
       ANS_CHK.SHOW    
       UKEF='0'
  ENDPROC  
  PROCEDURE ACC_BOTT.CLICK   &&轉會計傳票
      IF messagebox('確認資料無誤可轉會計傳票?',4+32+256,'請確認') = 6	                 
          OMT1=VAL(RIGHT(THISFORM.MTH_LIST.DISPLAYVALUE,2))+1   &&計算本月最後一天為幾號
          IF OMT1>12
              OMT1=OMT1%12
              OMT2=VAL(LEFT(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),4))+1
           ELSE
              OMT2=VAL(LEFT(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),4))  
          ENDIF
          OMT3=RIGHT(DTOS(CTOD(ALLTRIM(STR(OMT2))+'/'+PADL(ALLTRIM(STR(OMT1)),2,'0')+'/01')-1),2)
          OMT4=CHR(VAL(RIGHT(THISFORM.MTH_LIST.DISPLAYVALUE,2))+IIF(VAL(RIGHT(THISFORM.MTH_LIST.DISPLAYVALUE,2))>9,55,48))
          ACC='ACC'+ALLTRIM(SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,2)+OMT4)
          PTH1=ALLTRIM(INT_ACC)+'\ACS\DA'
          IF FILE(PTH1+'\'+ACC+'.DBF')=.F.
             MESSAGEBOX('新傳票月份檔還未產生!請先至會計總帳系統產生月份檔',0+48,'提示訊息視窗')             
             RETURN
          ENDIF              
          IF !USED('A09')
              SELECT 0
              USE A09
          ELSE
              SELECT A09
          ENDIF
          SET ORDER TO 1                         
          PTH2=ALLTRIM(INT_ACC)+'\CUS\DA'
          SELECT 0 
          USE &PTH2\CUS ALIAS CUS INDEX &PTH2\CUS
          SET ORDER TO 1
          SELECT 0
          USE &PTH1\&ACC  ALIA ACC INDEX &PTH1\&ACC
          SET ORDER TO 4
          SELECT C13_1
          GO TOP
          DO WHILE !EOF()
                 SELECT ACC
                 SELECT RECNO() FROM ACC WHERE CUS_NO=C13_1.F03 AND SUBSTR(TRAN_NO,4,1)='d' nowait          
                 IF _tally=0 
                      AI1=C13_1.F06    &&銷貨金額
                      AI2=C13_1.F07    &&銷貨退回金額
                      AI3=C13_1.F08+C13_1.F11   &&稅額
                      AI4=C13_1.F09   &&折讓金額
                      H='K00D '+SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
                      SELE A09
                      SEEK H            
                      IF !FOUND()                                                  &&如果為本月第一張訂單則重頭開始編號
	                     APPEND BLANK                                                
		                 REPLACE  F01 WITH 'K00D '
	                     REPLACE  F02 WITH  SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,4)
	                     REPLACE  F05 WITH  LEFT(F02,2)+OMT4
	                     REPLACE  F06 WITH '銷項會計傳票'
                         REPLACE  F08 WITH ALLTRIM(F05)+'d'+'0000'
                      ENDIF
	                  RLOCK()
	                  HX=VAL(RIGHT(ALLTRIM(F08),4))+1
	                  PO_NO=LEFT(F08,4)+PADL(ALLTRIM(STR(HX)),4,'0')
	                  REPLACE  F08 WITH PO_NO                                             &&記錄本訂單號碼,本月份後續的訂單號碼將以此往下編
	                  UNLOCK                 	         
	                  T=0
                      SELECT ACC
                      FOR I=1 TO 5
                              DO CASE
                                     CASE I=1
                                               T=T+1
                                                APPEND BLANK                                                                                            
                                                REPLACE tran_no WITH PO_NO
                                                REPLACE tran_date WITH left(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)+OMT3
                                                REPLACE cus_no WITH C13_1.F03                                   
                                                REPLACE cus_name1 WITH C01.F05
                                                REPLACE Yymm WITH LEFT(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)
                                                REPLACE crea_d WITH DATE()  
                                                REPLACE Res_cont WITH 'C12對帳單轉入'+SPACE(2)+THISFORM.MTH_LIST.DISPLAYVALUE
                                                REPLACE  seq WITH  PADL(ALLTRIM(STR(T)),2,'0')
                                                IF AI1+AI3+AI2+AI4>0 
                                                     REPLACE acc_no WITH INT_094
                                                     REPLACE acc_name WITH '應收帳款'                                              
                                                     REPLACE amt_d WITH AI1+AI2+AI3+AI4                             
                                                ELSE
                                                     REPLACE acc_no WITH INT_094
                                                     REPLACE acc_name WITH '應收帳款'                                              
                                                     REPLACE amt_c WITH (AI1+AI2+AI3+AI4)*(-1)
                                                ENDIF                                   
                                     CASE I=2           
                                               IF AI1>0
                                                   T=T+1
                                                   APPEND BLANK                                              
                                                   REPLACE tran_no WITH PO_NO
                                                   REPLACE tran_date WITH left(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)+OMT3
                                                   REPLACE cus_no WITH C13_1.F03                                   
                                                   REPLACE cus_name1 WITH C01.F05
                                                   REPLACE Yymm WITH LEFT(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)
                                                   REPLACE crea_d WITH DATE()  
                                                   REPLACE  seq WITH  PADL(ALLTRIM(STR(T)),2,'0')
                                                   REPLACE acc_no WITH INT_144
                                                   REPLACE acc_name WITH '銷貨收入'
                                                   REPLACE amt_c WITH AI1                              
                                                   REPLACE Res_cont WITH 'C12對帳單轉入'+SPACE(2)+THISFORM.MTH_LIST.DISPLAYVALUE
                                               ENDIF
                                     CASE I=3
                                                IF AI2<0
                                                    T=T+1
                                                    APPEND BLANK                                                                                            
                                                    REPLACE tran_no WITH PO_NO
                                                    REPLACE tran_date WITH left(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)+OMT3
                                                    REPLACE cus_no WITH C13_1.F03                                   
                                                    REPLACE cus_name1 WITH C01.F05
                                                    REPLACE Yymm WITH LEFT(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)
                                                    REPLACE crea_d WITH DATE()  
                                                    REPLACE  seq WITH  PADL(ALLTRIM(STR(T)),2,'0')
                                                    REPLACE acc_no WITH INT_145
                                                    REPLACE acc_name WITH '銷貨退回'
                                                    REPLACE amt_d WITH AI2*(-1)                      
                                                    REPLACE Res_cont WITH C01.F05+SPACE(2)+THISFORM.MTH_LIST.DISPLAYVALUE                    
                                                ENDIF                               
                                     CASE I=4
                                                IF AI4<0
                                                    T=T+1
                                                    APPEND BLANK                                                                                            
                                                    REPLACE tran_no WITH PO_NO
                                                    REPLACE tran_date WITH left(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)+OMT3
                                                    REPLACE cus_no WITH C13_1.F03                                   
                                                    REPLACE cus_name1 WITH C01.F05
                                                    REPLACE Yymm WITH LEFT(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)
                                                    REPLACE crea_d WITH DATE()  
                                                    REPLACE  seq WITH  PADL(ALLTRIM(STR(T)),2,'0')
                                                    REPLACE acc_no WITH INT_146
                                                    REPLACE acc_name WITH '銷貨折讓'
                                                    REPLACE amt_d WITH AI4*(-1)
                                                    REPLACE Res_cont WITH C01.F05+SPACE(2)+THISFORM.MTH_LIST.DISPLAYVALUE
                                                ENDIF                                    
                                     CASE I=5
                                                IF AI3<>0
                                                    T=T+1
                                                    APPEND BLANK                                                                                            
                                                    REPLACE tran_no WITH PO_NO
                                                    REPLACE tran_date WITH left(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)+OMT3
                                                    REPLACE cus_no WITH C13_1.F03                                   
                                                    REPLACE cus_name1 WITH C01.F05
                                                    REPLACE Yymm WITH LEFT(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),6)
                                                    REPLACE crea_d WITH DATE()  
                                                    REPLACE  seq WITH  PADL(ALLTRIM(STR(T)),2,'0')
                                                    REPLACE acc_no WITH INT_148
                                                    REPLACE acc_name WITH '銷項稅額'
                                                    REPLACE Res_cont WITH 'C12對帳單轉入'+SPACE(2)+THISFORM.MTH_LIST.DISPLAYVALUE
                                                    IF AI3>0
                                                        REPLACE amt_c WITH AI3                                 
                                                    ELSE
                                                        REPLACE amt_d WITH AI3*(-1)
                                                    ENDIF    
                                                ENDIF                                  
                             ENDCASE
                     ENDFOR
                  ENDIF   
                  SELECT CUS
                  SEEK C13_1.F03
                  IF !FOUND()
                     APPEND BLANK
                     REPLACE cus_no WITH C13_1.F03
                     REPLACE cus_type WITH '1'                     
                     REPLACE cus_name WITH C01.F04
                     REPLACE cus_name_1 WITH C01.F05
                     REPLACE cus_add_1 WITH C01.F06
                     REPLACE cus_add_2 WITH C01.F07
                     REPLACE tel_1 WITH C01.F13
                     REPLACE fax WITH C01.F14
                     REPLACE comp_no WITH C01.F10
                     REPLACE comp_clr WITH C01.F12
                     REPLACE post_date WITH C01.F17
                     REPLACE add_sel WITH '1'
                  ENDIF
                  SELECT C13
                  SEEK C13_1.F03
                  IF FOUND()
                     DO WHILE F03=C13_1.F03
                        REPLACE F10 WITH PO_NO
                        SKIP
                     ENDDO
                  ENDIF
                  SELECT C13_1
                  REPLACE FTR WITH PO_NO
                  SKIP
          ENDDO
          SELECT CUS
          USE
          SELECT ACC
          USE
          SELECT A09
          USE
          =MESSAGEBOX('資料已轉入會計傳票檔'+ACC,0+48,'資料轉檔完成')          
          SELECT A23 
          SEEK DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01'))    
          IF FOUND()
              REPLACE F14 WITH .T.
          ENDIF    
          THISFORM.ACC_BOTT.ENABLED=.F.
       ENDIF   
      THISFORM.PAGEFRAME1.ACTIVEPAGE=1
      THISFORM.GRID1.SETFOCUS
      THISFORM.REFRESH
  ENDPROC    
  PROCEDURE ACD_BOTT.CLICK    &&刪除傳票
      IF messagebox('確定將已轉入之會計傳票全部刪除?',4+32+256,'請確認') = 6	                      
          OMT4=CHR(VAL(RIGHT(THISFORM.MTH_LIST.DISPLAYVALUE,2))+IIF(VAL(RIGHT(THISFORM.MTH_LIST.DISPLAYVALUE,2))>9,55,48))
          ACC='ACC'+ALLTRIM(SUBSTR(DTOS(CTOD(THISFORM.MTH_LIST.DISPLAYVALUE+'/01')),3,2)+OMT4)
          PTH1=ALLTRIM(INT_ACC)+'\ACS\DA'  
          SELECT 0
          USE &PTH1\&ACC ALIAS ACC INDEX &PTH1\&ACC          
          SET ORDER TO 1
          GO TOP
          SELECT C13_1
          GO TOP
          DO WHILE !EOF()
             IF !EMPTY(C13_1.FTR)
                SELECT ACC
                SEEK ALLTRIM(C13_1.FTR)
                IF FOUND()
                   DO WHILE tran_no=ALLTRIM(C13_1.FTR)  AND !EOF()              
                      DELETE 
                      SKIP
                   ENDDO  
                ENDIF             
                SELECT C13
                SEEK C13_1.F03
                IF FOUND()
                   DO WHILE F03=C13_1.F03 AND !EOF()
                      REPLACE F10 WITH ''
                      SKIP
                   ENDDO
                ENDIF             
             ENDIF                   
             SELECT C13_1
             REPLACE FTR WITH ''             
             SKIP
          ENDDO   
          SELECT A23
          REPLACE F14 WITH .F.
          SELECT ACC
          USE
          =MESSAGEBOX('已轉入之會計傳票已全部刪除!',0+48,'資料轉檔完成')                    
          SELECT C13_1
          THISFORM.PAGEFRAME1.ACTIVEPAGE=1     
          THISFORM.GRID1.SETFOCUS
          THISFORM.REFRESH
      ENDIF    
  ENDPROC
ENDDEFINE   
********************************************************
DEFINE CLASS ANS_CHK AS FORM
  AUTOCENTER=.T.
  CAPTION='請選擇資料排序方式'
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*146
  WIDTH=INT_015*210
  FONTSIZE=INT_015*9
  MOVABLE=.F.
  MAXBUTTON=.F.
  MINBUTTON=.F.     
  CONTROLBOX=.F.
  BORDERSTYLE=2
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WINDOWTYPE=1
  NAME='ANS_CHK'
ADD OBJECT DATA_OPTION AS OPTIONGROUP WITH;
      LEFT=INT_015*17,;
      TOP=INT_015*20,;
      AUTOSIZE=.T.,;
      FONTSIZE=INT_015*12,;
      BUTTONCOUNT=2,;
      OPTION1.CAPTION='依客戶編號排列',;
      OPTION1.TOP=0,;
      OPTION1.FONTSIZE=INT_015*9,;
      OPTION1.AUTOSIZE=.T.,;
      OPTION2.CAPTION='依統一編號排列',;
      OPTION2.TOP=25,;
      OPTION2.FONTSIZE=INT_015*9,; 
      OPTION2.AUTOSIZE=.T.,;
      NAME='DATA_OPTION'       
ADD OBJECT OUTTYPE_OPTION AS OPTIONGROUP WITH;
      LEFT=INT_015*17,;
      TOP=INT_015*70,;
      AUTOSIZE=.T.,;
      FONTSIZE=INT_015*12,;
      BUTTONCOUNT=2,;
      OPTION1.CAPTION='列印報表',;
      OPTION1.TOP=0,;
      OPTION1.FONTSIZE=INT_015*9,;
      OPTION1.AUTOSIZE=.T.,;
      OPTION2.CAPTION='轉EXCEL',;
      OPTION2.TOP=0,;
      OPTION2.LEFT=80,;
      OPTION2.FONTSIZE=INT_015*9,; 
      OPTION2.AUTOSIZE=.T.,;
      NAME='OUTTYPE_OPTION'             
  ADD OBJECT CMND1 AS COMMANDBUTTON WITH;
      LEFT=INT_015*43,;     
      TOP=INT_015*105,;  
      HEIGHT=INT_015*25,;
      FONTSIZE=INT_015*9,;     
      WIDTH=INT_015*50,;
      CAPTION='\<Y.確定',;
      TOOLTIPTEXT='確認所選擇的鍵值!快速鍵->ALT+Y',;
      NAME='CMND1'
  ADD OBJECT CMND2 AS COMMANDBUTTON WITH;
      LEFT=INT_015*143,;
      TOP=INT_015*105,;
      HEIGHT=INT_015*25,; 
      FONTSIZE=INT_015*9,;     
      WIDTH=INT_015*50,;
      CAPTION='\<C.取消',;
      TOOLTIPTEXT='取消作業!快速鍵->ALT+C',;
      NAME='CMND2'      
  *****    
  PROCEDURE CMND1.CLICK   
     
	 DO CASE 
        CASE THISFORM.DATA_OPTION.VALUE=1 &&客戶簡稱排列
             SELECT C13_1
             SET ORDER TO 1
             GO TOP
             IF THISFORM.OUTTYPE_OPTION.VALUE=1
                REPORT FORM ALLTRIM(INT_116)+'C12A' TO PRINT PROMPT PREVIEW  
             ELSE
                FILE_NAME=LEFT(DTOS(CTOD(CHK_STR+'/01')),6)+'帳款總表(依客戶簡稱)'+IIF(UKEF='1','僅銷貨','全部')
                IF UKEF='1'
                   SELECT C13_1.F03 客戶編號,C01.F05 客戶簡稱,C01.F24 付款條件,C13_1.F10 統一編號,C13_1.F06 出貨金額,C13_1.F08 出貨稅額 FROM C13_1,C01 WHERE C01.F01=C13_1.F03 ORDER BY C13_1.F03 NOWAIT
                   
                ELSE
                    SELECT C13_1.F03 客戶編號,C01.F05 客戶簡稱,C01.F24 付款條件,C13_1.F10 統一編號,C13_1.F06 出貨金額,C13_1.F07 退貨金額,C13_1.F09 折讓金額,C13_1.F08 銷貨稅額,C13_1.F11 折退稅額 FROM C13_1,C01 WHERE C01.F01=C13_1.F03 ORDER BY C13_1.F03 NOWAIT
                ENDIF
                GCDELIMFILE=PUTFILE('儲存路徑',FILE_NAME,'XLS')
                COPY TO (GCDELIMFILE) TYPE XL5   
                =MESSAGEBOX('儲存成功',0+64,'提示訊息視窗')
             ENDIF   
             
        CASE THISFORM.DATA_OPTION.VALUE=2	&&統一編號排列
             SELECT C13_1
             SET ORDER TO 2
             GO TOP
             IF THISFORM.OUTTYPE_OPTION.VALUE=1
                REPORT FORM ALLTRIM(INT_116)+'C12B' TO PRINT PROMPT PREVIEW  
             ELSE
                FILE_NAME=LEFT(DTOS(CTOD(CHK_STR+'/01')),6)+'帳款總表(依統一編號)'+IIF(UKEF='1','僅銷貨','全部')
                IF UKEF='1'
                   SELECT C13_1.F10 統一編號,C13_1.F03 客戶編號,C01.F05 客戶簡稱,C01.F24 付款條件,C13_1.F06 出貨金額,C13_1.F08 稅額 FROM C13_1,C01 WHERE C01.F01=C13_1.F03 ORDER BY C13_1.F10 NOWAIT
                   
                ELSE
                    SELECT C13_1.F10 統一編號,C13_1.F03 客戶編號,C01.F05 客戶簡稱,C01.F24 付款條件,C13_1.F06 出貨金額,C13_1.F07 退貨金額,C13_1.F09 折讓金額,C13_1.F08 銷貨稅額,C13_1.F11 折退稅額 FROM C13_1,C01 WHERE C01.F01=C13_1.F03 ORDER BY C13_1.F10 NOWAIT
                ENDIF
                GCDELIMFILE=PUTFILE('儲存路徑',FILE_NAME,'XLS')
                COPY TO (GCDELIMFILE) TYPE XL5   
                =MESSAGEBOX('儲存成功',0+64,'提示訊息視窗')                
             ENDIF   
	 ENDCASE 		
	 CLEAR  
	 SELECT C13_1
	 SET ORDER TO 1
	 GO R 
     THISFORM.RELEASE                         
  ENDPROC
 ***** 
  PROCEDURE CMND2.CLICK
      THISFORM.RELEASE
  ENDPROC      
ENDDEFINE 
**********************************************列印程序
PROCEDURE PNT_PRC  
     UKEF='0'
     PRCK='0'
     IF MESSAGEBOX('是否只印銷貨',4+32+256,'請確認') = 6	        
        UKEF='1'
     ENDIF
     S=0
     ANS_RANGE=CREATEOBJECT("ANS_RANGE")  
     ANS_RANGE.SHOW    
     IF S=0
        =MESSAGEBOX('無此範圍資料',0+48,'警示')
     ENDIF   
     UKEF='0'
     CLEAR     
ENDPROC
*******************************************************列印範圍選定
DEFINE CLASS ANS_RANGE AS FORM
  AUTOCENTER=.T.
  CAPTION='請輸入列印資料範圍'
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*150
  WIDTH=INT_015*500
  FONTSIZE=INT_015*9
  MAXBUTTON=.F.
  MINBUTTON=.F.
  MOVABLE=.F.
  CLOSABLE=.F.    
  CONTROLBOX=.F.
  BORDERSTYLE=2
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WINDOWTYPE=1
  NAME='ANS_RANGE'
  ADD OBJECT LABEL1 AS LABEL WITH;
      AUTOSIZE=.T.,;
      HEIGHT=INT_015*25,;
      LEFT=INT_015*25,;
      TOP=INT_015*40,;
      NAME='LABEL1'
  ADD OBJECT TEXT1 AS TEXTBOX WITH;
      AUTOSIZE=.T.,;
      TOP=INT_015*34,;
      LEFT=INT_015*78,;
      HEIGHT=INT_015*25,; 
      NAME='TEXT1'
  ADD OBJECT LABEL2 AS LABEL WITH;
      AUTOSIZE=.T.,;
      HEIGHT=INT_015*25,;
      LEFT=INT_015*25,;
      TOP=INT_015*90,;
      NAME='LABEL2'      
  ADD OBJECT TEXT2 AS TEXTBOX WITH;
      AUTOSIZE=.T.,;
      TOP=INT_015*84,;
      LEFT=INT_015*78,;
      HEIGHT=INT_015*25,;         
      NAME='TEXT2'    
 ADD OBJECT CRY_TPE AS OPTIONGROUP WITH;
      LEFT=INT_015*200,;
      TOP=INT_015*50,;
      HEIGHT=INT_015*40,;    
      WIDTH=INT_015*120,;      
      BUTTONCOUNT=2,;
      OPTION1.CAPTION='以本幣別顯示金額',;
      OPTION1.FONTSIZE=INT_015*9,;
      OPTION1.LEFT=INT_015*4,;
      OPTION1.TOP=INT_015*3,;
      OPTION1.AUTOSIZE=.T.,;
      OPTION2.CAPTION='以原幣別顯示金額',;
      OPTION2.FONTSIZE=INT_015*9,;
      OPTION2.LEFT=INT_015*4,;
      OPTION2.TOP=INT_015*23,;
      OPTION2.AUTOSIZE=.T.,;          
      NAME='CRY_TPE'                                          
  ADD OBJECT CMND1 AS COMMANDBUTTON WITH;
      LEFT=INT_015*400,;     
      TOP=INT_015*20,;  
      HEIGHT=INT_015*25,;    
      WIDTH=INT_015*70,;
      FONTSIZE=INT_015*10,;
      CAPTION='\<P.直接列印',;
      TOOLTIPTEXT='確認所選擇的鍵值!快速鍵->ALT+Y',;
      NAME='CMND1'
  ADD OBJECT CMND2 AS COMMANDBUTTON WITH;
      LEFT=INT_015*400,;     
      TOP=INT_015*60,;  
      HEIGHT=INT_015*25,;    
      WIDTH=INT_015*70,;
      FONTSIZE=INT_015*10,;
      CAPTION='\<V.預覽列印',;
      TOOLTIPTEXT='確認所選擇的鍵值!快速鍵->ALT+Y',;
      NAME='CMND2'      
  ADD OBJECT CMND3 AS COMMANDBUTTON WITH;
      LEFT=INT_015*400,;
      TOP=INT_015*100,;
      HEIGHT=INT_015*25,;    
      WIDTH=INT_015*70,;
      FONTSIZE=INT_015*10,;
      CAPTION='\<C.取   消',;
      TOOLTIPTEXT='取消作業!快速鍵->ALT+C',;
      NAME='CMND3'    
  PROCEDURE INIT 
      THISFORM.SETALL('FONTSIZE',INT_015*9,'TEXTBOX')
      THISFORM.SETALL('FONTSIZE',INT_015*9,'LABEL')      
      THISFORM.SETALL('FONTSIZE',INT_015*9,'COMMANDBUTTON')        
      THISFORM.LABEL1.CAPTION='起始客戶'
      THISFORM.LABEL2.CAPTION='截止客戶'
      THISFORM.TEXT1.WIDTH=INT_015*60
      THISFORM.TEXT2.WIDTH=INT_015*60 
      THISFORM.TEXT1.MAXLENGTH=5
      THISFORM.TEXT2.MAXLENGTH=5
      THISFORM.TEXT1.VALUE=C13_1.F03
      THISFORM.TEXT2.VALUE=C13_1.F03
      THISFORM.CRY_TPE.VALUE=1
  ENDPROC    
  PROCEDURE CRY_TPE.INTERACTIVECHANGE
    IF THIS.VALUE=2
       FTR_STR='1'
    ELSE
       FTR_STR='2'   
    ENDIF   
  ENDPROC
  PROCEDURE CMND1.CLICK      
     SELECT C13_1
     SEEK THISFORM.TEXT1.VALUE
        DO WHILE .T.
           LK=C13_1.F03          
           SELECT C13.F01,;
                  C13.F02,;
                  C13.F03,;
                  C13.F04,;
                  C13.F05,;
                  IIF(SEEK(C13.F05,'B01'),B01.F02,''),;
                  C13.F06,;
                  C13.F07,;                    
                  C13.F08,;                                
                  C13.F13,;
                  C13.F14,;
                  C13.F15,;
                  C13.F17,;
                  C13.F16,;
                  C13.F18,;
                  C01.F04,;
                  C01.F06,;
                  C01.F08,;
                  C01.F09,;            
                  C01.F10,;
                  C01.F12,;
                  C01.F13,;
                  C01.F14,;
                  C01.F24;                        
            FROM C13,C01 WHERE C13.F03=LK AND C01.F01=LK AND IIF(UKEF='1',C13.F08>0,.T.); 
            ORDER BY C13.F01 NOWAIT
            IF _TALLY >0
               S=S+1
               IF PRCK='0'
                  REPORT FORM ALLTRIM(INT_116)+'C12' TO PRINT					&&直接列印
               ELSE   
 				  REPORT FORM ALLTRIM(INT_116)+'C12' TO PRINT PROMPT PREVIEW  	&&預覽列印
 			   ENDIF
            ENDIF    
            SELECT C13_1
            SKIP
            IF EOF() OR C13_1.F03>THISFORM.TEXT2.VALUE
               EXIT
            ENDIF   
         ENDDO   
         SEEK THISFORM.TEXT2.VALUE
     PRCK='0'
     FTR_STR='2'
     THISFORM.RELEASE    
  ENDPROC
 PROCEDURE CMND2.CLICK 
    PRCK='1'
    THISFORM.CMND1.CLICK
 ENDPROC 
  ****
  PROCEDURE CMND3.CLICK
      FLG='1'   
      FTR_STR='2'
      THISFORM.RELEASE
  ENDPROC        
ENDDEFINE  
&&&&AND IIF(UKEF<>'1',.T.,C13.F08>0)

************************************************特殊輸入欄位的設定----料號
DEFINE CLASS TXTF05 AS TEXTBOX
  READONLY=.T.
  MAXLENGTH=43
  FONTSIZE=INT_015*9
  PROCEDURE INTERACTIVECHANGE
    IF AT('?',ALLTRIM(THIS.VALUE))<>0
       IF AT('?',ALLTRIM(THIS.VALUE))>1             
          SELECT F01,F02 FROM B01 INTO CURSOR MTR ORDER BY F01 WHERE RIGHT(F98,1)='*' AND LEFT(F01,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1)    
       ELSE
          SELECT F01,F02 FROM B01 INTO CURSOR MTR ORDER BY F01 WHERE RIGHT(F98,1)='*'   
       ENDIF        
       IF _TALLY>0
          MAN_SEEK=CREATEOBJECT("MTR_SEEK")  
          MAN_SEEK.SHOW    
          THIS.VALUE=FLG
          THIS.REFRESH
          FLG='0'     
       ENDIF    
    ENDIF  

  ENDPROC
ENDDEFINE

***************************************************特殊輸入欄位設定-----------客戶
DEFINE CLASS TXTF03 AS TEXTBOX
  READONLY=.T.
  MAXLENGTH=5
  FONTSIZE=INT_015*9
  PROCEDURE INTERACTIVECHANGE
    IF AT('?',ALLTRIM(THIS.VALUE))<>0 
       IF AT('?',ALLTRIM(THIS.VALUE))>1             
          SELECT F02,F01,F04 FROM C01 INTO CURSOR VDR ORDER BY F02 WHERE LEFT(F02,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1)
       ELSE
          SELECT F02,F01,F04 FROM C01 INTO CURSOR VDR ORDER BY F02 
       ENDIF
       IF _TALLY>0          
          VDR_SEEK=CREATEOBJECT("VDR_SEEK")  
          VDR_SEEK.SHOW    
          THIS.VALUE=FLG
          THIS.REFRESH
          FLG='0'        
       ENDIF   
    ELSE
       IF LEN(ALLTRIM(THIS.VALUE))=4
          SELECT F02,F01,F04 FROM C01 INTO CURSOR VDR ORDER BY F02 WHERE F02=ALLTRIM(THIS.VALUE)
          DO CASE
             CASE _TALLY=1
                  THIS.VALUE=VDR.F01
                  THIS.REFRESH
             CASE _TALLY>1
                  VDR_SEEK=CREATEOBJECT("VDR_SEEK")  
                  VDR_SEEK.SHOW    
                  THIS.VALUE=FLG
                  THIS.REFRESH
                  FLG='0'        
          ENDCASE      
       ENDIF    
    ENDIF      
       THISFORM.PAGEFRAME1.PAGE1.LBLF041.CAPTION=IIF(SEEK(THIS.VALUE,'C01'),C01.F04,'')  
  ENDPROC
ENDDEFINE
***************************************************特殊輸入欄位設定-----------業務人員
DEFINE CLASS TXTF19 AS TEXTBOX
   READONLY=.T.
   MAXLENGTH=5
   FONTSIZE=INT_015*9
   PROCEDURE INTERACTIVECHANGE
     IF AT('?',ALLTRIM(THIS.VALUE))<>0
        IF AT('?',ALLTRIM(THIS.VALUE))>1             
           SELECT F01,F03 FROM A01 INTO CURSOR MAN ORDER BY F01 WHERE LEFT(F01,AT('?',THIS.VALUE)-1)=LEFT(THIS.VALUE,AT('?',THIS.VALUE)-1)
        ELSE
           SELECT F01,F03 FROM A01 INTO CURSOR MAN ORDER BY F01    
        ENDIF   
        IF _TALLY>0
           MAN_SEEK=CREATEOBJECT("MAN_SEEK")  
           MAN_SEEK.SHOW    
           THIS.VALUE=FLG
           THIS.REFRESH
           FLG='0'        
        ENDIF   
     ENDIF  
      THISFORM.PAGEFRAME1.PAGE2.LBLF191.CAPTION=IIF(SEEK(THIS.VALUE,'A01'),A01.F03,'')  
  ENDPROC
ENDDEFINE
***************************************************幣別設定
DEFINE CLASS CRCY AS COMBOBOX
  HEIGHT=INT_015*25
  AUTOSIZE=.T.
  TOP=INT_015*28
  LEFT=INT_015*379
  FONTSIZE=INT_015*9
  BOUNDCOLUMN=1
  COLUMNCOUNT=1
  WIDTH=INT_015*84
  ROWSOURCETYPE=1
  STYLE=2
  NAME='CRCY'
  PROCEDURE INIT
    SELECT C00
    GO TOP 
    DO WHILE .NOT. EOF()
       L=4-LEN(ALLTRIM(F01))
       THIS.ADDITEM(F01)
       SKIP
    ENDDO
  ENDPROC
  PROCEDURE INTERACTIVECHANGE
    THISFORM.PAGEFRAME1.PAGE2.TXTF13.VALUE=THIS.DISPLAYVALUE
    THISFORM.PAGEFRAME1.PAGE2.TXTF14.VALUE=IIF(SEEK(THIS.DISPLAYVALUE,'C00'),C00.F02,1)
    THISFORM.PAGEFRAME1.PAGE2.TXTF13.REFRESH
    THISFORM.PAGEFRAME1.PAGE2.TXTF14.REFRESH
  ENDPROC
ENDDEFINE  

*******************************************   計算出貨金額
FUNC TTL1
     PARA BKK_NO
     qt_od=0
     sele C13
     SEEK BKK_NO
     IF FOUND()
         DO WHILE F03=BKK_NO            
                IF LEFT(C13.F02,2)='BC' AND LEFT(C13.F04,4)<>'稅額'
                     IF LEFT(C13.F16,2)<>'02'
                         qt_od=qt_od+f08
                      ELSE
                          qt_od=qt_od+ROUND(f08/(1+INT_002/100),INT_069)                 &&二聯式應稅                    
                      ENDIF    
                ENDIF   
                SKIP
          ENDDO
     ELSE
       qt_od=0
     ENDIF
     SELE C13_1
     RETURN ROUND(qt_od,INT_069)
**********************************************  計算退貨金額
FUNC TTL2
     PARA BKK_NO
     qt_od=0
     sele C13
     SEEK BKK_NO
     IF FOUND()
        DO WHILE F03=BKK_NO            
               IF LEFT(C13.F02,2)='BD' AND  LEFT(C13.F04,4)<>'稅額'  AND LEFT(C13.F18,2)<>'03'
                    IF LEFT(C13.F16,2)<>'02'
                        qt_od=qt_od+f08
                    ELSE
                        qt_od=qt_od+ROUND(f08/(1+INT_002/100),INT_069)               &&二聯式應稅
                    ENDIF
               ENDIF   
               SKIP
        ENDDO
     ELSE
       qt_od=0
     ENDIF
     SELE C13_1
     RETURN ROUND(qt_od,INT_069)
************************************************計算正稅額
FUNC TTL3_1
     PARA BKK_NO
     qt_od=0
     sele C13
     SEEK BKK_NO
     IF FOUND()
         DO WHILE F03=BKK_NO            
                IF LEFT(C13.F04,4)='稅額'  AND C13.F08>0                  
                     qt_od=qt_od+f08
                ELSE
                     IF LEFT(C13.F16,2)='02'  AND C13.F08>0                      
                          qt_od=qt_od+(F08-ROUND(f08/(1+INT_002/100),INT_069))    &&二聯式應稅
                     ENDIF                                                                                  
                ENDIF   
                SKIP
         ENDDO
     ELSE
       qt_od=0
     ENDIF
     SELE C13_1
     RETURN ROUND(qt_od,INT_069)
************************************************計算負稅額
FUNC TTL3_2
     PARA BKK_NO
     qt_od=0
     sele C13
     SEEK BKK_NO
     IF FOUND()
         DO WHILE F03=BKK_NO            
                IF LEFT(C13.F04,4)='稅額'  AND C13.F08<0                  
                     qt_od=qt_od+f08
                ELSE
                     IF LEFT(C13.F16,2)='02'  AND C13.F08<0                 
                          qt_od=qt_od+(F08-ROUND(f08/(1+INT_002/100),INT_069))    &&二聯式應稅
                     ENDIF                                                                                  
                ENDIF   
                SKIP
         ENDDO
     ELSE
       qt_od=0
     ENDIF
     SELE C13_1
     RETURN ROUND(qt_od,INT_069)     
**********************************************  計算折讓金額
FUNC TTL4
     PARA BKK_NO
     qt_od=0
     sele C13
     SEEK BKK_NO
     IF FOUND()
        DO WHILE F03=BKK_NO            
               IF LEFT(C13.F02,2)='BD' AND  LEFT(C13.F04,4)<>'稅額'  AND LEFT(C13.F18,2)='03'
                   IF LEFT(C13.F16,2)<>'02'                   
                          qt_od=qt_od+f08
                   ELSE     
                        qt_od=qt_od+ROUND(f08/(1+INT_002/100),INT_069)
                   ENDIF                                   
           ENDIF   
           SKIP
        ENDDO
     ELSE
       qt_od=0
     ENDIF
     SELE C13_1
     RETURN ROUND(qt_od,INT_069)     