close all
clear 
FLG='0'	&&搜尋畫面之結果判斷值或欲帶回值
FCH=''	&&紀錄目前之作用GRID值
AREA1='A14'	&&每一緩面基本主檔或表頭資料表格的代號
CHK=''	&&若有表頭表身檔案,紀錄表頭檔案之主鍵值以便於表身操作時加上表身次鍵值做搜尋用
IF !USED('A01')
   SELE 0
   USE A01 INDE A01
ELSE 
   SELE A01
ENDIF
SET ORDER TO A01      
IF !USED('A02')
   SELE 0
   USE A02 INDE A02
ELSE 
   SELE A02
ENDIF
SET ORDER TO A021      
SEEK sys_oper+'A02'	&&qqppwwoo.sys_oper:紀錄目前登陸系統者代號   
IF !USED('A14')
   SELE 0
   USE A14 INDE A14
ELSE 
   SELE A14
ENDIF
SET ORDER TO 1
SET FILTER TO F05='*' AND LEN(ALLTRIM(F01))=4
GO TOP

E01form=CREATEOBJECT('tkE01')
E01FORM.SHOW	&&使表單顯示出來，并可指定它的windowtype
DEFINE CLASS tkE01 AS Form
	CAPTION='E01.各部門產能設定'
	*!*	  autocenter=.t.
  controlbox=.F.
  BORDERSTYLE=1  
  MAXBUTTON=.F.
  MINBUTTON=.F.
  MOVABLE=.F.
  CLOSABLE=.F.
  controlcount=57
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*550
  showtips=.t.
  showwindow=1
  WIDTH=INT_015*789
  windowtype=1
  NAME='TKE01'
  add object shape1 as shape1 with;
      autocenter=.t.
  add object shape2 as shape2 with;
      autocenter=.t.
  add object shape3 as shape3 with;
      autocenter=.t.
  ADD OBJECT LBL_REC AS LBL_REC WITH;
      AUTOCENTER =.T.
  ADD OBJECT REC_COUNT AS REC_COUNT  with;
      caption=str(reccount())      

  ADD OBJECT LBLF01 AS LABEL WITH;
      LEFT=INT_015*244,;
      TOP=INT_015*27,;
      WIDTH=INT_015*50,;
      CAPTION='部門編號'
  ADD OBJECT LBLF02 AS LABEL WITH;      
      LEFT=INT_015*244,;
      TOP=INT_015*62,;
      WIDTH=INT_015*60,;
      CAPTION='部門名稱'
  ADD OBJECT LBLF08 AS LABEL WITH;&&
      LEFT=INT_015*244,;
      TOP=INT_015*97,;
      WIDTH=INT_015*50,;
      CAPTION='作業人數' 
  ADD OBJECT LBLF09 AS LABEL WITH;&&
      LEFT=INT_015*386,;
      TOP=INT_015*97,;
      WIDTH=INT_015*50,;
      CAPTION='作業時間' 
  ADD OBJECT LBLF091 AS LABEL WITH;&&
      LEFT=INT_015*517,;
      TOP=INT_015*97,;
      WIDTH=INT_015*50,;
      CAPTION=IIF(INT_030='1','秒',IIF(INT_030='2','分','時'))
  ADD OBJECT LBLF101 AS LABEL WITH;&&
      LEFT=INT_015*474,;
      TOP=INT_015*132,;
      WIDTH=INT_015*50,;
      CAPTION=IIF(INT_030='1','秒',IIF(INT_030='2','分','時'))
  ADD OBJECT LBLF10 AS LABEL WITH;
      LEFT=INT_015*244,;
      TOP=INT_015*132,;
      WIDTH=INT_015*50,;
      CAPTION='總 工 時'
  ADD OBJECT LBLF07 AS LABEL WITH;
      LEFT=INT_015*244,;
      TOP=INT_015*157,;
      WIDTH=INT_015*50,; 
      CAPTION='安全資料'   
  ADD OBJECT LBLF071 AS LABEL WITH;
      LEFT=INT_015*295,;
      TOP=INT_015*157,;
      AUTOSIZE=.T.
  ADD OBJECT TXTF01 AS TEXTBOX WITH;      
      LEFT=INT_015*295,;
      TOP=INT_015*23,;
      WIDTH=INT_015*49,;
      MAXLENGTH=5,;
      NAME='TXTF01'  
  ADD OBJECT TXTF02 AS TEXTBOX WITH;
      AUTOSIZE=.T.,;
      LEFT=INT_015*295,;
      TOP=INT_015*58,;
      WIDTH=INT_015*68,;
      MAXLENGTH=8,;
      NAME='TXTF02'
  ADD OBJECT TXTF08 AS TEXTBOX WITH;&&
      AUTOSIZE=.T.,;
      LEFT=INT_015*295,;
      TOP=INT_015*93,;
      WIDTH=INT_015*68,;
      ALIGNMENT=1,;
      MAXLENGTH=8,;
      NAME='TXTF08'
  ADD OBJECT TXTF09 AS TEXTBOX WITH;&&
      AUTOSIZE=.T.,;
      LEFT=INT_015*436,;
      TOP=INT_015*93,;
      WIDTH=INT_015*80,;
      ALIGNMENT=1,;
      MAXLENGTH=15,;
      NAME='TXTF09'                    
  ADD OBJECT TXTF10 AS TEXTBOX WITH;&&
      LEFT=INT_015*295,;
      TOP=INT_015*128,;
      WIDTH=INT_015*177,;            
      MAXLENGTH=15,;
      NAME='TXTF10'
                             
  ADD OBJECT KEY_LIST AS KEY_LIST WITH;
      AUTOCENTER=.T.
  ADD OBJECT GRID1 AS GRID1 WITH;
      columncount=2,;            
      RECORDSOURCE='A14',;      
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2'
  ADD OBJECT CMDGROUP AS CMDGROUP WITH;
      AUTOSIZE=.T.              
  ADD OBJECT ORPGROUP AS ORPGROUP WITH;    
      AUTOSIZE=.T.
  ADD OBJECT SHRGROUP AS SHRGROUP WITH;
      TOP=INT_015*455,;
      LEFT=INT_015*558
      
  PROC INIT
       THISFORM.ORPGROUP.NEW_BOTT.ENABLED=.F.	&&IIF(A02.F04='*',.T.,.F.)   判斷有無新增的權限
       THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.)  &&判斷有無修改的權限
       THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.	&&IIF(A02.F06='*',.T.,.F.)   &&判斷有無刪除的權限
       THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.	&&IIF(A02.F07='*',.T.,.F.)   判斷有無列印的權限
       THISFORM.SHRGROUP.VISIBLE=.F.
       THISFORM.SHRGROUP.ENABLED=.F.
       thisform.setall('height',INT_015*25,'textbox')
       thisform.setall('height',INT_015*17,'label')
       thisform.setall('FONTSIZE',INT_015*9,'textbox')
       thisform.setall('FONTSIZE',INT_015*9,'label')                    
       THISFORM.SETALL('READONLY',.T.,'TEXTBOX')
       THISFORM.GRID1.COLUMN1.WIDTH=INT_015*49
       THISFORM.GRID1.COLUMN2.WIDTH=INT_015*68
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'COLUMN')
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'HEADER')       
       THISFORM.GRID1.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)
       THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='部門編號'
	   THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='部門名稱'
	   THISFORM.GRID1.COLUMN1.CONTROLSOURCE='A14.F01'
	   THISFORM.GRID1.COLUMN2.CONTROLSOURCE='A14.F02'
       THISFORM.GRID1.READONLY=.T.  
       THISFORM.GRID1.SETFOCUS
       IF THISFORM.GRID1.ACTIVEROW=0
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.
       ELSE
          THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.      
       ENDIF       
       JK='部門編號'	&&紀錄表頭鍵值,以後加上表身鍵值,供搜尋用
  ENDPROC  

  PROC KEY_LIST.INIT 
       with this 
           .additem('依部門編號排列')
       endwith      
  ENDPROC 
 
 PROCEDURE GRID1.AFTERROWCOLCHANGE
 	LPARAMETERS nCO1INDEX
 	SELECT A14
 	THISFORM.TXTF01.VALUE=F01
 	THISFORM.TXTF02.VALUE=F02
 	THISFORM.TXTF08.VALUE=F08
 	THISFORM.TXTF09.VALUE=F09
 	THISFORM.TXTF10.VALUE=F10
 	THISFORM.LBLF071.CAPTION=F07
 	FCH=THISFORM.ActiveControl.NAME
 	CHK=''
 	THISFORM.Refresh
 ENDPROC
 
PROCEDURE ORPGROUP.EDIT_BOTT.CLICK
	THISFORM.TXTF01.READONLY=.T.
	THISFORM.GRID1.ENABLED=.F.
	THISFORM.TXTF02.READONLY=.T.
	THISFORM.TXTF08.READONLY=.F.
	THISFORM.TXTF09.READONLY=.F.
	THISFORM.TXTF10.READONLY=.T.
	THISFORM.TXTF08.SETFOCUS
	LOCK()
	IF !RLOCK()
		DO FILE_IMPACT
		RETURN
	ENDIF
ENDPROC
  
PROCEDURE SHRGROUP.SHURE2_BOTT.CLICK
    SELE A14
    A=THISFORM.TXTF08.VALUE
    B=THISFORM.TXTF09.VALUE
    IF RLOCK()
       REPLACE F02 WITH THISFORM.TXTF02.VALUE       
       REPLACE F08 WITH THISFORM.TXTF08.VALUE
       REPLACE F09 WITH THISFORM.TXTF09.VALUE   
       REPLACE F10 WITH A*B
       REPLACE F07 WITH IIF(INT_012=1,PADL(ALLTRIM(STR(YEAR(DATE())-1911)),3,' ')+RIGHT(DTOC(DATE()),6),dtoc(DATE())+' ')+IIF(SEEK(sys_oper,'A01'),A01.F03,'') 
    ELSE
      DO file_impact
      return   
    ENDIF   
    THISFORM.SHRGROUP.ABANDON_BOTT.CLICK    
ENDPROC
  
procedure SHRGROUP.ABANDON_BOTT.CLICK
      THISFORM.SHRGROUP.ENABLED=.F.
      THISFORM.SHRGROUP.VISIBLE=.F.      
      THISFORM.ORPGROUP.ENABLED=.T.
      THISFORM.ORPGROUP.SETALL('FORECOLOR',RGB(0,0,0),'COMMANDBUTTON')
      THISFORM.ORPGROUP.NEW_BOTT.ENABLED=.F.	&&IIF(A02.F04='*',.T.,.F.)   判斷有無新增的權限      
      THISFORM.ORPGROUP.EDIT_BOTT.ENABLED=IIF(A02.F05='*',.T.,.F.)  &&判斷有無修改的權限
      THISFORM.ORPGROUP.DEL_BOTT.ENABLED=.F.	&&IIF(A02.F06='*',.T.,.F.)   &&判斷有無刪除的權限
      THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.	&&IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限      
      THISFORM.CMDGROUP.ENABLED=.T.
      THISFORM.CMDGROUP.SETALL('ENABLED',.T.,'COMMANDBUTTON')
      THISFORM.CMDGROUP.SETALL('FORECOLOR',RGB(0,0,0),'COMMANDBUTTON')
      THISFORM.KEY_LIST.ENABLED=.T.      
      THISFORM.SETALL('READONLY',.T.,'TEXTBOX')   
      UNLOCK ALL
      SELE A01
      THISFORM.GRID1.ENABLED=.T.
      THISFORM.GRID1.SETFOCUS       
ENDPROC

ENDDEFINE     
	