**程式名稱:S12B.薪資所得年度查詢
SET EXCL OFF
CLOSE ALL
CLEAR 
AREA1='S12B_TEMP'
FLG='0'
FCH=''
CHK=''
YEAR_DATE=''		&&欲查詢之年度
IF !USED('A01')
   SELE 0
   USE A01
ELSE 
   SELE A01
ENDIF
SET ORDER TO A01      
IF !USED('S05')
   SELE 0
   USE S05 
ELSE
   SELE S05
ENDIF
SET ORDER TO S051
IF !USED('A02')
   SELE 0
   USE A02 INDE A02
ELSE
   SELE A02
ENDIF
SET ORDER TO A021     
SEEK SYS_OPER+'S05'  
IF FOUND()  AND A02.F09='*'   &&判斷是否有權限可處理所有員工
    SELECT F01 FROM S05 INTO CURSOR S05_TEMP
ELSE
    SELECT F01 FROM S05 WHERE F27=.T. INTO CURSOR S05_TEMP
ENDIF
SELECT A02      
SEEK SYS_OPER+'S12'    
IF !USED('S11')
   SELE 0
   USE S11 
ELSE
   SELE S11
ENDIF
SET ORDER TO S111
*********
S12BFORM=CREATEOBJECT("TKS12B")
S12BFORM.SHOW  
DEFINE CLASS TKS12B AS FORM
*!*	  AUTOCENTER=.T.
  CAPTION='S12B.薪資所得年度查詢  (請輸入西元年  例如:2004)'
  TOP=INT_015*200
  LEFT=INT_015*235      
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*100
  WIDTH=INT_015*310
  MAXBUTTON=.F.
  MINBUTTON=.F.
  MOVABLE=.F.    
  CONTROLBOX=.F.
  BORDERSTYLE=1
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WINDOWTYPE=1
  NAME='TKS12B'
  ADD OBJECT LBLF01 AS LABEL WITH;
      LEFT=INT_015*20,;
      TOP=INT_015*46,;
      AUTOSIZE=.T.,;
      CAPTION='請輸入查詢之西元年份'
  ADD OBJECT TXTF01 AS TEXTBOX WITH;
      LEFT=INT_015*155,;
      TOP=INT_015*40,;
      HEIGHT=INT_015*25,;
      WIDTH=INT_015*40,;
      MAXLENGTH=4,;
      INPUTMASK='9999',;   
      NAME='TXTF01'      
  ADD OBJECT CMND1 AS COMMANDBUTTON WITH;
      LEFT=INT_015*220,;
      TOP=INT_015*20,;
      HEIGHT=INT_015*25,;
      WIDTH=INT_015*50,;
      FONTSIZE=INT_015*10,;
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;        
      CAPTION='\<Y.確認',;
      TOOLTIPTEXT='確認所輸入之內容->ALT+Y',;
      NAME='CMND1'
 ADD OBJECT CMND2 AS COMMANDBUTTON WITH;
      LEFT=INT_015*220,;
      TOP=INT_015*55,;
      HEIGHT=INT_015*25,;
      WIDTH=INT_015*50,;
      FONTSIZE=INT_015*10,;
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;        
      CAPTION='\<C.取消',;
      TOOLTIPTEXT='取消此畫面!快速鍵->ALT+C'
      NAME='CMND2'
********************
 PROCEDURE INIT 
         THISFORM.SETALL('FONTSIZE',INT_015*10,'LABEL')
         THISFORM.SETALL('FONTSIZE',INT_015*10,'TEXTBOX')
         THISFORM.SETALL('FONTSIZE',INT_015*10,'COMMANDBUTTON')
         THISFORM.TXTF01.SETFOCUS
 ENDPROC   
********    
 PROC CMND1.MOUSEENTER      
       LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND1.FORECOLOR=RGB(255,0,0)
             THISFORM.CMND1.TOP=INT_015*21
             THISFORM.CMND1.LEFT=INT_015*221
  ENDPROC     
  PROC CMND1.MOUSELEAVE      
        LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND1.FORECOLOR=RGB(0,0,0)  
             THISFORM.CMND1.TOP=INT_015*20
             THISFORM.CMND1.LEFT=INT_015*220        
  ENDPROC 
 PROC CMND2.MOUSEENTER      
       LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND2.FORECOLOR=RGB(255,0,0)
             THISFORM.CMND2.TOP=INT_015*56
             THISFORM.CMND2.LEFT=INT_015*221
  ENDPROC     
  PROC CMND2.MOUSELEAVE      
        LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND2.FORECOLOR=RGB(0,0,0)  
             THISFORM.CMND2.TOP=INT_015*55
             THISFORM.CMND2.LEFT=INT_015*220                
  ENDPROC   
********確認鍵******
PROCEDURE CMND1.CLICK   
       IF EMPTY(THISFORM.TXTF01.VALUE)  
           =MESSAGEBOX('年份不得為空白',0+64,'提示視窗')
           THISFORM.TXTF01.SETFOCUS
           RETURN      
       ENDIF 	       
       IF LEN(ALLTRIM(THISFORM.TXTF01.VALUE))<4 
           =MESSAGEBOX('年份長度不能小於4碼',0+64,'提示視窗')
           THISFORM.TXTF01.SETFOCUS
           RETURN      
       ENDIF        
       YEAR_DATE=THISFORM.TXTF01.VALUE
       SELECT S11.F01,S11.F02,S11.F31 FROM S11,S05_TEMP  ORDER BY S11.F02;
       WHERE LEFT(DTOS(S11.F01),4)=ALLTRIM(THISFORM.TXTF01.VALUE) AND ALLTRIM(S11.F02)=ALLTRIM(S05_TEMP.F01) INTO CURSOR S11_TEMP        
       IF  _TALLY>0
	    SELECT S11.F02,S11.F03,S11.F04,S11.F05 FROM S11,S05_TEMP  GROUP BY S11.F02 ORDER BY S11.F02;
	    WHERE LEFT(DTOS(S11.F01),4)=ALLTRIM(THISFORM.TXTF01.VALUE) AND ALLTRIM(S11.F02)=ALLTRIM(S05_TEMP.F01) INTO CURSOR S11A_TEMP
 	    CREATE CURSOR S12B_TEMP;
	    (F02 C(4),F03 C(8),F04 C(4),F05 C(8),JAN N(7),FEB N(7),MAR N(7),APR N(7),MAY N(7),JUN N(7),JUL N(7),AUG N(7),SEP N(7),OCT N(7),NOV N(7),DEC N(7),TOAL N(10))
	     INDE ON F02 TAG S12B_TEMP1
	     INDE ON F04 TAG S12B_TEMP2
	     SELECT S12B_TEMP
	     SET ORDER TO S12B_TEMP1
	     SELECT S11A_TEMP
	     GO TOP
	     DO WHILE !EOF()
		    SELECT S12B_TEMP
		    APPEND BLANK 
		    REPLACE S12B_TEMP.F02 WITH  S11A_TEMP.F02
		    REPLACE S12B_TEMP.F03 WITH  S11A_TEMP.F03
		    REPLACE S12B_TEMP.F04 WITH  S11A_TEMP.F04
		    REPLACE S12B_TEMP.F05 WITH  S11A_TEMP.F05
		    SELECT S11A_TEMP
		    SKIP
             ENDDO
	     SELECT S11A_TEMP
	     USE	
	     SELECT S05_TEMP
	     USE				  		  
	     SELECT S11_TEMP
	     GO TOP
	     DO WHILE !EOF()
		    SELECT S12B_TEMP
	            SEEK S11_TEMP.F02
	            IF FOUND()    
	                SELECT S12B_TEMP
	                DO  CASE
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='01'
  					    REPLACE S12B_TEMP.JAN WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='02'
  					    REPLACE S12B_TEMP.FEB WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='03'
  					    REPLACE S12B_TEMP.MAR WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='04'
  					    REPLACE S12B_TEMP.APR WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='05'
  					    REPLACE S12B_TEMP.MAY WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='06'
  					    REPLACE S12B_TEMP.JUN WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='07'
  					    REPLACE S12B_TEMP.JUL WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='08'
  					    REPLACE S12B_TEMP.AUG WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='09'
  					    REPLACE S12B_TEMP.SEP WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='10'
  					    REPLACE S12B_TEMP.OCT WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='11'
  					    REPLACE S12B_TEMP.NOV WITH  S11_TEMP.F31
	                        CASE  SUBSTR(DTOS(S11_TEMP.F01),5,2)='12'
  					    REPLACE S12B_TEMP.DEC WITH  S11_TEMP.F31 					                   					                   					                   					                   					                   					                   					                   					                   					                   					                   					                 
  			ENDCASE	      
  			REPLACE S12B_TEMP.TOAL WITH  S12B_TEMP.TOAL+S11_TEMP.F31      
		   ENDIF
	           SELECT S11_TEMP
	           SKIP       
	    ENDDO
	    SELECT S11_TEMP
	    USE
	    SELECT S12B_TEMP
	    SET ORDER TO  S12B_TEMP1
	    GO TOP
	    TKS12B_SEEK=CREATEOBJECT("TKS12B_SEEK")  
	    TKS12B_SEEK.SHOW		 
	    CLOSE TABLE ALL
 	    THISFORM.RELEASE 	
       ELSE
            =MESSAGEBOX('此年度範圍並無資料',0+64,'提示視窗')
            THISFORM.TXTF01.SETFOCUS
       ENDIF    
ENDPROC       
********離開鍵***********
 PROCEDURE CMND2.CLICK     
       CLOSE TABLE ALL
       THISFORM.RELEASE 
*!*	          RETURN 
       DO S12.PRG
 ENDPROC      
ENDDEFINE      
************************
DEFINE CLASS TKS12B_SEEK AS FORM      
*!*	  AUTOCENTER=.T.  
  CAPTION='S12B.薪資所得年度查詢'+SPACE(25)+'查詢年度：'+YEAR_DATE+' 年'
  FONTSIZE=INT_015*9
  HEIGHT=INT_015*548
  WIDTH=INT_015*791
  FONTSIZE=INT_015*12
  CONTROLBOX=.F.
  MAXBUTTON=.F.
  MINBUTTON=.F.  
  MOVABLE=.F.
  CLOSABLE=.F.
  BORDERSTYLE=2
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WINDOWTYPE=1
  NAME='TKS12B_SEEK'         
  ADD OBJECT KEY_LIST AS KEY_LIST WITH;
     WIDTH=INT_015*180,;
      AUTOCENTER=.T.
  ADD OBJECT GRID1 AS GRID1 WITH;
      COLUMNCOUNT=17,;            
      RECORDSOURCE='S12B_TEMP',; 
      HEIGHT=INT_015*500,;     
      WIDTH=INT_015*780,;      
      COLUMN1.NAME='COLUMN1',;
      COLUMN2.NAME='COLUMN2',;
      COLUMN3.NAME='COLUMN3',; 
      COLUMN4.NAME='COLUMN4',; 
      COLUMN5.NAME='COLUMN5',;             
      COLUMN6.NAME='COLUMN6',;       
      COLUMN7.NAME='COLUMN7',;       
      COLUMN8.NAME='COLUMN8',;
      COLUMN9.NAME='COLUMN9',;   
      COLUMN10.NAME='COLUMN10',;
      COLUMN11.NAME='COLUMN11',; 
      COLUMN12.NAME='COLUMN12',;
      COLUMN13.NAME='COLUMN13',;
      COLUMN14.NAME='COLUMN14',;
      COLUMN15.NAME='COLUMN15',;
      COLUMN16.NAME='COLUMN16',;
      COLUMN17.NAME='COLUMN17'
   ADD OBJECT CMDGROUP AS CMDGROUP WITH;
      TOP=INT_015*0,;
      LEFT=INT_015*205,;
      ENABLED=.T.,;
      VISIBLE=.T.            
  ADD OBJECT ORPGROUP AS ORPGROUP WITH;      
      TOP=INT_015*0,;
      LEFT=INT_015*405                                                  
  PROCEDURE INIT
       THISFORM.ORPGROUP.NEW_BOTT.VISIBLE=.F.
       THISFORM.ORPGROUP.EDIT_BOTT.VISIBLE=.F.
       THISFORM.ORPGROUP.DEL_BOTT.VISIBLE=.F.
       THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限    
       THISFORM.GRID1.BACKCOLOR=IIF(SEEK(sys_oper,'A01'),IIF(A01.F11=0,10009146,A01.F11),10009146)   
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'COLUMN')
       THISFORM.GRID1.SETALL('FONTSIZE',INT_015*9,'HEADER')   
       THISFORM.GRID1.COLUMN1.WIDTH=INT_015*50
       THISFORM.GRID1.COLUMN2.WIDTH=INT_015*50
       THISFORM.GRID1.COLUMN3.WIDTH=INT_015*50
       THISFORM.GRID1.COLUMN4.WIDTH=INT_015*50
       THISFORM.GRID1.COLUMN5.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN6.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN7.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN8.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN9.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN10.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN11.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN12.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN13.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN14.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN15.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN16.WIDTH=INT_015*55
       THISFORM.GRID1.COLUMN16.WIDTH=INT_015*60
           THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='人員編號'
	   THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='人員姓名'
	   THISFORM.GRID1.COLUMN3.HEADER1.CAPTION='部門編號'	   
	   THISFORM.GRID1.COLUMN4.HEADER1.CAPTION='部門名稱'	   
	   THISFORM.GRID1.COLUMN5.HEADER1.CAPTION='一月份'	
  	   THISFORM.GRID1.COLUMN6.HEADER1.CAPTION='二月份'
  	   THISFORM.GRID1.COLUMN7.HEADER1.CAPTION='三月份'
  	   THISFORM.GRID1.COLUMN8.HEADER1.CAPTION='四月份' 
  	   THISFORM.GRID1.COLUMN9.HEADER1.CAPTION='五月份'
  	   THISFORM.GRID1.COLUMN10.HEADER1.CAPTION='六月份'  	  
  	   THISFORM.GRID1.COLUMN11.HEADER1.CAPTION='七月份'  	 
  	   THISFORM.GRID1.COLUMN12.HEADER1.CAPTION='八月份'  	
  	   THISFORM.GRID1.COLUMN13.HEADER1.CAPTION='九月份'  
  	   THISFORM.GRID1.COLUMN14.HEADER1.CAPTION='十月份'  
  	   THISFORM.GRID1.COLUMN15.HEADER1.CAPTION='十一月份' 
  	   THISFORM.GRID1.COLUMN16.HEADER1.CAPTION='十二月份' 
  	   THISFORM.GRID1.COLUMN17.HEADER1.CAPTION='年度總所得' 
	   THISFORM.GRID1.COLUMN1.CONTROLSOURCE='S12B_TEMP.F02'
	   THISFORM.GRID1.COLUMN2.CONTROLSOURCE='S12B_TEMP.F03'
	   THISFORM.GRID1.COLUMN3.CONTROLSOURCE='S12B_TEMP.F04'
	   THISFORM.GRID1.COLUMN4.CONTROLSOURCE='S12B_TEMP.F05'
	   THISFORM.GRID1.COLUMN5.CONTROLSOURCE='S12B_TEMP.JAN'
	   THISFORM.GRID1.COLUMN6.CONTROLSOURCE='S12B_TEMP.FEB'
	   THISFORM.GRID1.COLUMN7.CONTROLSOURCE='S12B_TEMP.MAR'
	   THISFORM.GRID1.COLUMN8.CONTROLSOURCE='S12B_TEMP.APR'
	   THISFORM.GRID1.COLUMN9.CONTROLSOURCE='S12B_TEMP.MAY'
	   THISFORM.GRID1.COLUMN10.CONTROLSOURCE='S12B_TEMP.JUN'
	   THISFORM.GRID1.COLUMN11.CONTROLSOURCE='S12B_TEMP.JUL'
	   THISFORM.GRID1.COLUMN12.CONTROLSOURCE='S12B_TEMP.AUG'
	   THISFORM.GRID1.COLUMN13.CONTROLSOURCE='S12B_TEMP.SEP'
	   THISFORM.GRID1.COLUMN14.CONTROLSOURCE='S12B_TEMP.OCT'
	   THISFORM.GRID1.COLUMN15.CONTROLSOURCE='S12B_TEMP.NOV'
	   THISFORM.GRID1.COLUMN16.CONTROLSOURCE='S12B_TEMP.DEC'
	   THISFORM.GRID1.COLUMN17.CONTROLSOURCE='S12B_TEMP.TOAL'
       THISFORM.GRID1.READONLY=.T.       
       THISFORM.GRID1.SETFOCUS    
        IF  THISFORM.GRID1.ACTIVEROW=0 
              THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.F.      
	      THISFORM.CMDGROUP.UP_BOTT.ENABLED=.F.
	      THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.F.
	      THISFORM.CMDGROUP.END_BOTT.ENABLED=.F.    
	      THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.F.	        
	      THISFORM.ORPGROUP.PNT_BOTT.ENABLED=.F.   
        ELSE
              THISFORM.CMDGROUP.TOP_BOTT.ENABLED=.T.      
	      THISFORM.CMDGROUP.UP_BOTT.ENABLED=.T.
	      THISFORM.CMDGROUP.NEXT_BOTT.ENABLED=.T.
	      THISFORM.CMDGROUP.END_BOTT.ENABLED=.T.    
	      THISFORM.CMDGROUP.SEEK_BOTT.ENABLED=.T.	        
	      THISFORM.ORPGROUP.PNT_BOTT.ENABLED=IIF(A02.F07='*',.T.,.F.)   &&判斷有無列印的權限       
        ENDIF          
       JK='人員編號'
  ENDPROC    
  PROC KEY_LIST.INIT 
       WITH THIS 
           .ADDITEM('依人員編號排列')
           .ADDITEM('依部門編號排列')      
       ENDWITH      
  ENDPROC 
  PROC KEY_LIST.INTERACTIVECHANGE                 
       SELE S12B_TEMP
       DO CASE
          CASE THIS.DISPLAYVALUE='依人員編號排列'    
                     THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='人員編號'
		     THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='人員姓名'
		     THISFORM.GRID1.COLUMN3.HEADER1.CAPTION='部門編號'	   
		     THISFORM.GRID1.COLUMN4.HEADER1.CAPTION='部門名稱'	   	
		     THISFORM.GRID1.COLUMN1.CONTROLSOURCE='S12B_TEMP.F02'
		     THISFORM.GRID1.COLUMN2.CONTROLSOURCE='S12B_TEMP.F03'
		     THISFORM.GRID1.COLUMN3.CONTROLSOURCE='S12B_TEMP.F04'
		     THISFORM.GRID1.COLUMN4.CONTROLSOURCE='S12B_TEMP.F05'		        
                     SET ORDER TO S12B_TEMP1
          CASE THIS.DISPLAYVALUE='依部門編號排列'         
		     THISFORM.GRID1.COLUMN1.HEADER1.CAPTION='部門編號'	   
		     THISFORM.GRID1.COLUMN2.HEADER1.CAPTION='部門名稱'	   	
                     THISFORM.GRID1.COLUMN3.HEADER1.CAPTION='人員編號'
		     THISFORM.GRID1.COLUMN4.HEADER1.CAPTION='人員姓名'		     
		     THISFORM.GRID1.COLUMN1.CONTROLSOURCE='S12B_TEMP.F04'
		     THISFORM.GRID1.COLUMN2.CONTROLSOURCE='S12B_TEMP.F05'	
		     THISFORM.GRID1.COLUMN3.CONTROLSOURCE='S12B_TEMP.F02'
		     THISFORM.GRID1.COLUMN4.CONTROLSOURCE='S12B_TEMP.F03'		     	        
                     SET ORDER TO S12B_TEMP2       
       ENDCASE 
       JK=THISFORM.GRID1.COLUMN1.HEADER1.CAPTION
       THISFORM.GRID1.REFRESH
       THISFORM.GRID1.SETFOCUS
  ENDPROC             
*******        
  PROC GRID1.AFTERROWCOLCHANGE
       LPARAMETERS NCOLINDEX
       FCH=THISFORM.ACTIVECONTROL.NAME
       CHK=''
       THISFORM.REFRESH
  ENDPROC       
ENDDEFINE        
***********************************************列印程序
PROCEDURE PNT_PRC  
   SELE S12B_TEMP
   ANS_RANGE=CREATEOBJECT("ANS_RANGE")  
   ANS_RANGE.SHOW       
ENDPROC 
***********************************************列印範圍選定
DEFINE CLASS ANS_RANGE AS FORM
*!*	  AUTOCENTER=.T.
  CAPTION='請輸入列印資料範圍'
  TOP=INT_015*200
  LEFT=INT_015*250  
  HEIGHT=INT_015*120
  WIDTH=INT_015*280
  FONTSIZE=INT_015*9
  MOVABLE=.F.
  MAXBUTTON=.F.
  MINBUTTON=.F. 
  CONTROLBOX=.F.
  BORDERSTYLE=2
  SHOWTIPS=.T.
  SHOWWINDOW=1
  WINDOWTYPE=1
  NAME='ANS_RANGE'
  ADD OBJECT LABEL1 AS LABEL WITH;
      AUTOSIZE=.T.,;
      HEIGHT=INT_015*25,;
      LEFT=INT_015*30,;
      TOP=INT_015*30,;
      CAPTION='起始員工編號',;
      NAME='LABEL1'
  ADD OBJECT TEXT1 AS TEXTBOX WITH;
      TOP=INT_015*24,;
      LEFT=INT_015*110,;
      HEIGHT=INT_015*25,; 
      WIDTH=INT_015*60,; 
      MAXLENGTH=4,;
      NAME='TEXT1'      
  ADD OBJECT LABEL2 AS LABEL WITH;
      AUTOSIZE=.T.,;
      HEIGHT=INT_015*25,;
      LEFT=INT_015*30,;
      TOP=INT_015*61,;
      CAPTION='截止員工編號',;
      NAME='LABEL2'
  ADD OBJECT TEXT2 AS TEXTBOX WITH;
      TOP=INT_015*55,;
      LEFT=INT_015*110,;
      HEIGHT=INT_015*25,;   
      WIDTH=INT_015*60,;     
      MAXLENGTH=4,;   
      NAME='TEXT2'    
  ADD OBJECT CMND1 AS COMMANDBUTTON WITH;
      LEFT=INT_015*190,;    
      HEIGHT=INT_015*25,; 
      WIDTH=INT_015*70,;    
      TOP=INT_015*14,;  
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;        
      CAPTION='\<P.列         印',;
      TOOLTIPTEXT='列印所輸入的範圍鍵值!快速鍵->ALT+Y',;
      NAME='CMND1'
  ADD OBJECT CMND2 AS COMMANDBUTTON WITH;
      LEFT=INT_015*190,;    
      HEIGHT=INT_015*25,; 
      WIDTH=INT_015*70,;    
      TOP=INT_015*45,;  
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;        
      CAPTION='\<E.轉EXCEL',;
      TOOLTIPTEXT='將資料轉至EXCEL格式!快速鍵->ALT+Y',;
      NAME='CMND2'      
  ADD OBJECT CMND3 AS COMMANDBUTTON WITH;
      LEFT=INT_015*190,;
      TOP=INT_015*76,;
      HEIGHT=INT_015*25,;
      WIDTH=INT_015*70,; 
      MOUSEPOINTER=99,;
      MOUSEICON='BMPS\harrow.cur',;        
      CAPTION='\<C.取        消',;
      TOOLTIPTEXT='取消作業!快速鍵->ALT+C',;
      NAME='CMND3'
  PROCEDURE INIT 
      THISFORM.SETALL('FONTSIZE',INT_015*10,'TEXTBOX')
      THISFORM.SETALL('FONTSIZE',INT_015*10,'LABEL')      
      THISFORM.SETALL('FONTSIZE',INT_015*10,'COMMANDBUTTON')    
      DO CASE  
             CASE KEY()='F02'     
                        THISFORM.LABEL1.CAPTION='起始員工編號' 
                        THISFORM.LABEL2.CAPTION='截止員工編號' 
                        THISFORM.TEXT1.VALUE=S12B_TEMP.F02
                        THISFORM.TEXT2.VALUE=S12B_TEMP.F02
             CASE KEY()='F04'    
                        THISFORM.LABEL1.CAPTION='起始部門編號' 
                        THISFORM.LABEL2.CAPTION='截止部門編號'        
                        THISFORM.TEXT1.VALUE=S12B_TEMP.F04
                        THISFORM.TEXT2.VALUE=S12B_TEMP.F04                              
      ENDCASE     
  ENDPROC    
  **
  PROCEDURE CMND1.CLICK 
      IF  EMPTY(THISFORM.TEXT1.VALUE)
           =MESSAGEBOX('起始編號不得為空白!',0+64,'提示訊息視窗')
           THISFORM.TEXT1.SETFOCUS
  	   RETURN 
      ENDIF
      IF  EMPTY(THISFORM.TEXT2.VALUE)
           =MESSAGEBOX('截止編號不得為空白!',0+64,'提示訊息視窗')
           THISFORM.TEXT2.SETFOCUS
  	   RETURN 
      ENDIF      
      DO CASE  
             CASE KEY()='F02'     
                        SELECT  * FROM S12B_TEMP WHERE F02>=THISFORM.TEXT1.VALUE AND F02<=THISFORM.TEXT2.VALUE  ORDER BY F02 NOWAIT
		        IF  _TALLY >0
		             REPORT FORM ALLTRIM(INT_116)+'S12B_1'  TO PRINTER PROMPT  PREVIEW  
		        ELSE
		             =MESSAGEBOX('查無此範圍資料',0+48,'警示')
		             THISFORM.TEXT1.SETFOCUS
		             RETURN     
		        ENDIF                          
             CASE KEY()='F04'    
                        SELECT  * FROM S12B_TEMP WHERE F04>=THISFORM.TEXT1.VALUE AND F04<=THISFORM.TEXT2.VALUE  ORDER BY F04 NOWAIT                     
		        IF  _TALLY >0
		             REPORT FORM ALLTRIM(INT_116)+'S12B_2' TO PRINTER PROMPT  PREVIEW
		        ELSE
		             =MESSAGEBOX('查無此範圍資料',0+48,'警示')
		             THISFORM.TEXT1.SETFOCUS
		             RETURN     
		        ENDIF                               
      ENDCASE         
           THISFORM.CMND3.CLICK
  ENDPROC  
  ***
  PROCEDURE CMND2.CLICK 
      IF  EMPTY(THISFORM.TEXT1.VALUE)
           =MESSAGEBOX('起始編號不得為空白!',0+64,'提示訊息視窗')
           THISFORM.TEXT1.SETFOCUS
  	   RETURN 
      ENDIF
      IF  EMPTY(THISFORM.TEXT2.VALUE)
           =MESSAGEBOX('截止編號不得為空白!',0+64,'提示訊息視窗')
           THISFORM.TEXT2.SETFOCUS
  	   RETURN 
      ENDIF      
      FILENAME='S12B 薪資所得年度資料'+YEAR_DATE+'年'
      DO CASE  
             CASE KEY()='F02'     
                        SELECT F02 員工編號,F03 員工姓名,F04 部門編號,F05 部門名稱,JAN 一月,FEB 二月,MAR 三月,APR 四月,MAY 五月,JUN 六月,JUL 七月,;
                                       AUG 八月,SEP 九月,OCT 十月,NOV 十一月,DEC 十二月,TOAL 年度所得 FROM S12B_TEMP WHERE F02>=THISFORM.TEXT1.VALUE AND F02<=THISFORM.TEXT2.VALUE  ORDER BY F02 NOWAIT
		        IF  _TALLY >0
	                     GCDELIMFILE=PUTFILE('儲存路徑',FILENAME,'XLS')
			     IF !EMPTY(GCDELIMFILE) 
			          ON ERROR DO FILE_IMPACT
			          COPY TO (GCDELIMFILE) TYPE XL5     
			          =MESSAGEBOX('儲存成功',0+64,'提示訊息視窗') 
			     ELSE
		                 THISFORM.TEXT1.SETFOCUS
		                 RETURN			     
			     ENDIF  	
			ELSE
		             =MESSAGEBOX('查無此範圍資料',0+48,'警示')
		             THISFORM.TEXT1.SETFOCUS
		             RETURN     
		        ENDIF                          
             CASE KEY()='F04'    
                        SELECT F04 部門編號,F05 部門名稱,F02 員工編號,F03 員工姓名,JAN 一月,FEB 二月,MAR 三月,APR 四月,MAY 五月,JUN 六月,JUL 七月,;
                                       AUG 八月,SEP 九月,OCT 十月,NOV 十一月,DEC 十二月,TOAL 年度所得 FROM S12B_TEMP WHERE F04>=THISFORM.TEXT1.VALUE AND F04<=THISFORM.TEXT2.VALUE  ORDER BY F02 NOWAIT
		        IF  _TALLY >0
	                    GCDELIMFILE=PUTFILE('儲存路徑',FILENAME,'XLS')
			     IF !EMPTY(GCDELIMFILE) 
			          ON ERROR DO FILE_IMPACT
			          COPY TO (GCDELIMFILE) TYPE XL5     
			          =MESSAGEBOX('儲存成功',0+64,'提示訊息視窗') 
			     ELSE
		                 THISFORM.TEXT1.SETFOCUS
		                 RETURN			    
			     ENDIF  		       
		        ELSE
		             =MESSAGEBOX('查無此範圍資料',0+48,'警示')
		             THISFORM.TEXT1.SETFOCUS
		             RETURN     
		        ENDIF                               
      ENDCASE         
           THISFORM.CMND3.CLICK
  ENDPROC   
  ***         
  PROCEDURE CMND3.CLICK
      THISFORM.RELEASE
  ENDPROC      
  PROC CMND1.MOUSEENTER      
       LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND1.FORECOLOR=RGB(255,0,0)
             THISFORM.CMND1.TOP=INT_015*15
             THISFORM.CMND1.LEFT=INT_015*191
  ENDPROC     
  PROC CMND1.MOUSELEAVE      
        LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND1.FORECOLOR=RGB(0,0,0)  
             THISFORM.CMND1.TOP=INT_015*14
             THISFORM.CMND1.LEFT=INT_015*190                  
  ENDPROC     
  PROC CMND2.MOUSEENTER      
       LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND2.FORECOLOR=RGB(255,0,0)
             THISFORM.CMND2.TOP=INT_015*46
             THISFORM.CMND2.LEFT=INT_015*191
  ENDPROC     
  PROC CMND2.MOUSELEAVE      
        LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND2.FORECOLOR=RGB(0,0,0)  
             THISFORM.CMND2.TOP=INT_015*45
             THISFORM.CMND2.LEFT=INT_015*190                  
  ENDPROC     
  PROC CMND3.MOUSEENTER      
       LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND3.FORECOLOR=RGB(255,0,0)
             THISFORM.CMND3.TOP=INT_015*77
             THISFORM.CMND3.LEFT=INT_015*191
  ENDPROC     
  PROC CMND3.MOUSELEAVE      
        LPARAMETERS nButton, nShift, nXCoord, nYCoord 
             THISFORM.CMND3.FORECOLOR=RGB(0,0,0)  
             THISFORM.CMND3.TOP=INT_015*76
             THISFORM.CMND3.LEFT=INT_015*190                  
  ENDPROC     
ENDDEFINE    