****程式名稱 INVCRT發票轉帳作業
CLEAR ALL
SET TALK OFF
SET EXCL OFF
SET DELE ON
SET CENT OFF
SET SAFE OFF
SET DECIMALS TO 6
SET REPROCESS TO 1
_SCREEN.CAPTION=''
_SCREEN.CONTROLBOX=.F.
ZOOM WIND SCREEN MIN
CLEAR ALL
CLOS DATA ALL
CLOS TABL ALL
SET TALK OFF
SET EXCL OFF
SET DELE ON
SET CENT OFF
SET SAFE OFF
SET DECIMALS TO 6
SET ENGINEBEHAVIOR 70 
SET REPORTBEHAVIOR 80
SET REPROCESS TO 1
_SCREEN.CAPTION=''
_SCREEN.CONTROLBOX=.F.
ZOOM WINDOW  SCREEN MAX
HIDE WINDOW SCREEN
DEACTIVATE WIND SCREEN
SET SYSMENU OFF
SET STATUS BAR OFF
SET MULTILOCKS ON
DECLARE _FPRESET IN msvcrt20.dll 
CAPSLOCK(.T.)

SET DATE TO YMD

DO FORM TAIBYO
