FUNC TG
     PARA DK
     OL=''
     DO CASE
        CASE DK='1'
             OL='¥Ò'
        CASE DK='2'
             OL='¤A'
        CASE DK='3'
             OL='¤þ'
        CASE DK='4'
             OL='¤B'
        CASE DK='5'
             OL='¥³'
        CASE DK='6'
             OL='¤v'
        CASE DK='7'
             OL='©°'
        CASE DK='8'
             OL='¨¯'
        CASE DK='9'
             OL='¤Ð'
        CASE DK='0'
             OL='¬Ñ'
     ENDCASE
     RETURN OL